### ISSUE TITLE
Lookup Tool: Query Caller Name

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#100]
**Is your feature request related to a problem? Please describe.**
The [lookups tool](https://acceleratenetworks.com/Lookup) claims "Enter a phone number and we'll hunt down any information we can find on it.", but we actually can get more data on a phone number, specifically the caller name attached to a phone number by querying the Line Info Database (LIDB). This type of query is often called a CNAM dip, as we are dipping into the LIDB database.

**Describe the solution you'd like**
Query the data247.com API to get the caller name and add it as a column in the lookups tool. API has been emailed to you, change ast to json to get a nice json response.

**Comment by uncheckederror** [comment]
@danry25 does this look good?

![image](https://user-images.githubusercontent.com/11726956/96397541-9cd9c100-117e-11eb-89fc-3fd6259a459e.png)
