### ISSUE TITLE
Quote Checkbox and workflow

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#105]
**Is your feature request related to a problem? Please describe.**
Customers often ask us for a quote of what our services and initial hardware would cost. If we could enable them to build their own quote through the website, that would make things easier on the sales team.

**Describe the solution you'd like**
At the checkout page where we gather their address, name, business name, etc, add a checkbox for "Please send a quote"

If this checkbox is selected, generate a customer profile in InvoiceNinja, then create a hardware/one time fee quote, and a second quote containing just recurring billing items, then send an email titled Quote `<quote # here>` from Accelerate Networks
Body of email if product & service is in cart:
```
Hello <potential client>,

Thanks for considering Accelerate Networks, take a look at the monthly service cost here, and the upfront cost here.

Let us know if you have any questions!

Sincerely,
Accelerate Networks
206-858-8757 (call or text)
```
Body of email if product is in cart:
```
Hello <potential client>,

Thanks for considering Accelerate Networks, take a look at the upfront cost here.

Let us know if you have any questions!

Sincerely,
Accelerate Networks
206-858-8757 (call or text)
```
Body of email if service is in cart:
```
Hello <potential client>,

Thanks for considering Accelerate Networks, take a look at the monthly service cost here.

Let us know if you have any questions!

Sincerely,
Accelerate Networks
206-858-8757 (call or text)
```

**Additional context**
When creating a quote, it appears that InvoiceNinja hits the /invoices endpoint with a POST request containing entityType: quote and template_type: quote to create  the quote, hopefully accessing the invoice creation API in the same manner results in a quote being created?

Update: See these issues for API details:
https://github.com/invoiceninja/invoiceninja/issues/851
https://github.com/invoiceninja/invoiceninja/issues/2769

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/96525257-5a23f180-122f-11eb-86d2-003ddba1fe82.png)

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/96525276-6445f000-122f-11eb-853c-152efaf6c4e2.png)

**Comment by uncheckederror** [comment]
@danry25 @scottstrong206 this functionality is live. Please verify that it meets your requirements.

**Comment by uncheckederror** [comment]
The code for this feature is in c881609

**Comment by uncheckederror** [comment]
@danry25 We can't get the public facing URL of an invoice or quote via the invoice ninja API. So to send the two invoices/quotes to the customer will need to send them as separate emails from the billing system.

**Comment by uncheckederror** [comment]
Per @danry25 we can get the public facing invite URL for the invoices/quotes this way: https://github.com/AccelerateNetworks/NumberSearch/issues/106#issuecomment-713295917
