### ISSUE TITLE
800/Vanity support

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#107]
**Is your feature request related to a problem? Please describe.**
Somos (the North American Toll Free administrator) has a database of available toll free numbers that is quite vast. We would like to tap into that

**Describe the solution you'd like**
[This API endpoint](https://apidocs.teleapi.net/api/order-phone-numbers/search-vanity-tollfree) seems very limited and performs best with a 10 digit query (eg: *****hello or 888***test). We can only get 10 results at a time, so caching them is unlikely to work well for our use case.

Extend Number Search with an asynchronous search for vanity toll free numbers that calls back to this API?

**Comment by uncheckederror** [comment]
Closing this as we've worked out a better solution/method in issue #90.
