### ISSUE TITLE
Switch to BulkVS REST API

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#108]
**Is your feature request related to a problem? Please describe.**
BulkVS now has [a Rest API](https://portal.bulkvs.com/api/v1.0/documentation), perhaps we should start using this?

**Additional context**
/orderTN GET is what you'll need to search available numbers, and use POST to buy a particular number.

**Comment by uncheckederror** [comment]
I have reenabled our tests of the BulKVS REST API and it's working again. Which means this work is unblocked.

**Comment by uncheckederror** [comment]
I have switched over the number ingest process to use the BulkVS REST API. Although we have identified an issue where we can only capture the first 1000 results for a given area code from BulkVS.

**Comment by uncheckederror** [comment]
Switched phone number ordering over in b4b3f4b.

**Comment by danry25** [comment]
What is left on the SOAP API? Querying for the numbers we own? The [get_tnRecord](https://portal.bulkvs.com/api/v1.0/documentation#/Origination/get_tnRecord) endpoint can be used to get this information.

**Comment by uncheckederror** [comment]
Yes, that's the last piece. I am actively developing it now.
