### ISSUE TITLE
Handle port requests where a list of numbers is submitted in Bulk

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#110]
**Is your feature request related to a problem? Please describe.**
Is there a way I could have a large text field that worked just like Lookups, but instead it added numbers to my cart that were then being ported?

**Comment by uncheckederror** [comment]
@danry25 do you want this to be public facing, unlisted, or part of the Ops app?

**Comment by danry25** [comment]
Lets make this part of the Ops app.

**Comment by uncheckederror** [comment]
@danry25 please verify that you're good with this feature.

**Comment by danry25** [comment]
Looks good, but I will hold off on closing this issue till I fully test it with a real order.

**Comment by danry25** [comment]
This works! Thanks Tom!
