### ISSUE TITLE
Update text on Phone Service section

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#117]
**Describe the solution you'd like**
- Add a sentence to the bottom saying "Buy 1 Seat per phone ordered"
- Update Concurrent Seats to just be Seats
- Update Standard Lines to Lines

**Additional context**
Our current text is vague and does not tell the customer what a seat is.

**Comment by uncheckederror** [comment]
@danry25 can you verify that you're good with this? https://acceleratenetworks.com/Services
