### ISSUE TITLE
Create a Features page to explain the features on our phones

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#118]
**Is your feature request related to a problem? Please describe.**
Right now we don't have a page on the website that explains what features are available when using our phones.

**Describe the solution you'd like**
I'd like to have a page on the website that lists all of the features we offer and what they do.

**Comment by uncheckederror** [comment]
@Chattaeus could you provide the list of features and their descriptions here?

**Comment by uncheckederror** [comment]
Okay the features page is now live here: https://acceleratenetworks.com/Home/Features

Please add your feedback below @kylek206, @scottstrong206, @Chattaeous.

**Comment by danry25** [comment]
Title should be just Features, and we should add an image/gif in the whitespace to the right/left of the feature that relates to the feature.

**Comment by uncheckederror** [comment]
@danry25 are you going to provide the images/gifs?

**Comment by danry25** [comment]
Ah, not sure, will need to think about it.

**Comment by scottstrong206** [comment]
Hi Tom,

We are planning on putting together the images this weekend. 

Sincerely,
Scott Strong
Director of Sales
206-408-3008 (call/text)
 (http://acceleratenetworks.com)

November 28, 2020 12:48 PM, "Dan" <notifications@github.com (mailto:notifications@github.com?to=%22Dan%22%20<notifications@github.com>)> wrote:
	Ah, not sure, will need to think about it.

**Comment by kylek206** [comment]
Please add these:

Bluetooth – Most of our phones support Bluetooth, our newer phones support the latest and greatest Bluetooth 5.0 (connect your air pods or any Bluetooth device).

WIFI Compatibility – No need to worry about staying connected with just Ethernet, stay mobile with our new WIFI phones!

LTE Backup – Similar to a backup generator for your internet, detects when your internet is going down and is able to support your internet and phones until your ISP (Internet Service Provider) can get out and resolve the underlying issue.

Please combine these two:

Fax to Email – Incoming faxes appear in your email inbox, and sending faxes is a snap from the portal!

Voicemail to Email – Check your voicemail right from your email!

I think we should consider removing these features because they are boring and don't help us stand out:

- Transfer Calls
- Conference Calling
- Speakerphone
- Speed Dial
- Work from Home

**Comment by danry25** [comment]
Add this under Phone Features too:
Wired Headsets - Every deskphone supports wired headsets using the built in RJ9 port on the rear of the phone. Crisp, clear and dependable, wired headsets are an effective way to enable a hands free experience! 
Intercom - With the press of a button instantly start a conversation with a particular person! When using intercom, their phone will answer immediately on speakerphone.
History - See recent calls or sort by incoming, outgoing, missed and internal calls right from the onscreen menu of your phone.

**Comment by uncheckederror** [comment]
I am also adding emoji to each of the feature titles per our feedback discussion today,

**Comment by uncheckederror** [comment]
All of these changes are now live on our website: https://acceleratenetworks.com/Home/Features

Please add your feedback below @kylek206, @scottstrong206, @Chattaeus, and @danry25.

**Comment by danry25** [comment]
@Chattaeus What is the status on the feature videos? Reassigning this to you since your handling this.

**Comment by uncheckederror** [comment]
After the shoot today we are waiting on @Chattaeus to edit the final videos, upload them to NextCloud and then @danry25 to post them on YouTube so we can embed them on our features and support pages.

**Comment by uncheckederror** [comment]
@Chattaeus can you paste the links to the YouTube videos here?

**Comment by Chattaeus** [comment]
This is the first in the playlist for the 2615:
https://www.youtube.com/watch?v=ZvnveaC6an8&list=PLy8FSfLD62uOCqDyG130sZvnZO97rLygm
This is the first video in the playlist for the 2170:
https://www.youtube.com/watch?v=hB2VfAYuLic&list=PLy8FSfLD62uMbuJIjxrjBsCMKsZ2Wpknp
This the first video in the playlist for the 2135:
https://www.youtube.com/watch?v=xkIBKdGjHuM&list=PLy8FSfLD62uME4KaKtMl5LKJ5zAGN6z05

I recommend starting with video 1 in each playlist and then following the playlist down to grab each URL.

**Comment by uncheckederror** [comment]
Excellent thanks @Chattaeus!

**Comment by uncheckederror** [comment]
https://acceleratenetworks.com/Phones/GRP2615

@Chattaeus @danry25 what say you?

**Comment by Chattaeus** [comment]
That's fresh. How do you get to it from the main website though? Can we make the features page look this good?

**Comment by uncheckederror** [comment]
@Chattaeus it's under the support drop down for now. Yes, we can, eventually.

**Comment by danry25** [comment]
@uncheckederror I like this, but I feel like we need to link to it from the Knowledgebase rather than just adding a phone model in the support dropdown. It also creates a weird bifurcation between the embedded Erxes Knowledgebase and the phone specific support articles.

Is there a reasonable way to make our knowledgebase/phone video page more coherent? Should we bring these in as native pages and end the knowledgebase?

**Comment by uncheckederror** [comment]
The phone specific pages are good for SEO and hard linking to content as opposed to the Erxes Knowledgebase which doesn't help with either of those items.

**Comment by danry25** [comment]
Is there an existing Dotnet Core module for Knowlegebases we can import? I don't want to have to update these pages by editing HTML (which is what we would have to do [for the current GRP2615 page](https://github.com/AccelerateNetworks/NumberSearch/commit/07f217c153b5ebb3494ce8d11649c3dc97923d55)), as I doubt I could convince @Chattaeus or anyone else to do so.

Need a WSIWYG or markdown editor for knowledgebase pages that can handle formatting text (bold, italics, underline), emojis, embedding images and videos and tables. Take a look at the Comcast and MicroSIP articles in the current Erxes knowledgebase as examples. We also need a way for users to search said knowledgebase

**Comment by danry25** [comment]
For the GRP2615 Page, a table of contents with links to each subsection would be helpful so that users can easily navigate the page without having to scroll through the whole page.

**Comment by uncheckederror** [comment]
@danry25 I have added a table of contents, try it out.

https://acceleratenetworks.com/Phones/GRP2615

**Comment by Chattaeus** [comment]
Hey @uncheckederror can we get a typo correction on "Create a Voice Mail Greeting" and make it "Create a Voicemail Greeting?"

**Comment by uncheckederror** [comment]
@Chattaeus you'll have to teach me how to speel and fix my dyslexia first. 🤣

Glad you like it.

**Comment by danry25** [comment]
@uncheckederror It appears the header for Confrence is also misspelled, but this is correctly spelled as Conference in the text below the video.

**Comment by uncheckederror** [comment]
@Chattaeus @danry25 okay, fixed.

**Comment by danry25** [comment]
@Chattaeus Can you record a video showing how to change the ringtone for each model of phone?

**Comment by Chattaeus** [comment]
Can add that to list so it gets done with the next round. Need to do a series for the Yealink too. I will need another GRP2615 to do that one though. My demo model is now in use elsewhere.

**Comment by uncheckederror** [comment]
All three phones are up on the support page now: https://acceleratenetworks.com/Home/Support

**Comment by danry25** [comment]
The word received is misspelled as [recieve](https://github.com/AccelerateNetworks/NumberSearch/search?q=recieve)

**Comment by uncheckederror** [comment]
@danry25 typos fixed.
