### ISSUE TITLE
Porting Information email not suppressed when information put into Notes field

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#125]
**Describe the bug**
When information is put in the Notes field on an order, this should cause all emails about the order to be suppressed. 

**To Reproduce**
1. Transfer a few numbers
2. Fill out the Order Information and put information in a note
3. Add porting information to the order
4. See an email thanking the user for adding porting information to the order.

**Expected behavior**
No email should be sent to the user.

**Additional context**
See order at 12/14/2020 12:31:15 AM. Additionally, the email lists one number twice as being ported in, this seems like another bug.

**Comment by uncheckederror** [comment]
Oh, wow the content of that email is a heck of a bug. Thanks for filing this @danry25.

**Comment by uncheckederror** [comment]
@danry25 Right now if you add porting information to an order you will always get an email. Adding notes to an email only blocks the sending of the order confirmation email it has no impact on the porting information process as that's handle separately on another page.

Do you want to block these porting information added confirmation emails? And if so under what circumstances?

**Comment by danry25** [comment]
In retrospect, lets leave it as is for now.
