### ISSUE TITLE
BulkVS injest uses too much memory

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#126]
**Describe the bug**
The ingest app consumes ~400 MBs of memory while doing a complete BulkVS ingest. The causes unexpected closure of other apps on the production server as the box runs out of memory.

![image](https://user-images.githubusercontent.com/11726956/102119322-c79a6b80-3df5-11eb-908c-e21b959b234b.png)

**Comment by danry25** [comment]
I have added a gigabyte sized swap file to prevent OOM Killer from killing this process.

**Comment by uncheckederror** [comment]
After we capture all of the numbers from BulkVS we assign number types to them and then submit them to the database.

As part of the submission process we take all of the items in the table and add them to a dictionary so we can quickly check if a number already exists in the database. I think this dictionary is what's eating up all the memory as it grows linearly with the number of rows we have in the table.

**Comment by uncheckederror** [comment]
We can see from this snapshot of the managed memory heap that the "Dictionary<Int32, Task>" is the largest memory consumer.

![image](https://user-images.githubusercontent.com/11726956/102120441-66739780-3df7-11eb-93f6-e66684ce47fa.png)

**Comment by uncheckederror** [comment]
I have reduced the amount of memory consumed by this dictionary by simplifying it. In order to check if a number already exists in the database we only really need the Dialed Number. To that end we can drop the rest of the data that we were capturing from the database and grab only the Dialed Number as a string. Then our dictionary becomes just a lookup on strings rather than on objects which should save us from allocating all of the objects and their fields.

This has reduced the memory consumption of the BulkVS ingest down to ~250 MBs from ~400 MBs for a savings of ~150 MBs.

![image](https://user-images.githubusercontent.com/11726956/102123839-4d211a00-3dfc-11eb-8afd-9db383c1014c.png)

**Comment by uncheckederror** [comment]
Because this change is in the shared database submission code it should offer a similar reduction in memory consumption for each of the ingest providers.
