### ISSUE TITLE
Port request showing a port request # but also showing unsubmitted

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#127]
**Describe the bug**
A port request shows a port order number but also has the Unsubmitted warning.

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/PortRequests/
2. Search for  12/14/2020 12:56:02 AM 
3. See the unsubmitted port request warning just below the port request # from the upstream vendor

**Additional context**
The port request is submitted with the upstream vendor, the status is just not accurate.

**Comment by danry25** [comment]
An Ops app user was able to submit a port request to Teli twice:
![signal-2020-12-17-135053](https://user-images.githubusercontent.com/1683673/102548106-025b0880-406f-11eb-921d-fa5749279ff8.jpeg)

When this occurred the Ops app saved the first port request # but munged the date that the port request was submitted:
![Screenshot from 2020-12-17 13-54-05](https://user-images.githubusercontent.com/1683673/102548553-b0ff4900-406f-11eb-9b64-bbad392c3570.png)

**Comment by uncheckederror** [comment]
To resolve this issue we'll need to prevent duplicate submissions of port requests.
