### ISSUE TITLE
Change Page Title for Numbers

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#128]
**Describe the bug**
We are getting calls from people that think we are spam calling them since they found the number that called them on our Numbers page and see it as purchasable. This seems to be happening by people using Google Search to find out who called them, compounded with an unclear page title. [Here is the 3rd most popular search query that takes people to our site](https://www.google.com/search?client=firefox-b-1-e&q=206-208-9282).

![Screenshot from 2020-12-16 17-55-04](https://user-images.githubusercontent.com/1683673/102431272-e3556b80-3fc7-11eb-95fb-50b99867de36.png)

![Screenshot from 2020-12-16 17-53-45](https://user-images.githubusercontent.com/1683673/102430776-c28d1600-3fc7-11eb-981e-9986f7789492.png)

**Expected behavior**
Update the page title to say "Buy <phone number - Accelerate Networks" rather than <phone number> - Accelerate Networks.

If we could detect the referrer is Google/Bing/Yahoo and they navigated onto a Numbers page that lists available phone numbers for purchase, perhaps we should show them a warning saying "If you recently received a call from any of the unassigned numbers listed on this page, it was likely a scam call!"

**Comment by danry25** [comment]
Hmm, would you mind if we added those tags back? I would prefer to have our available phone numbers listed in Google Search results even if that means the occasional irate caller.

**Comment by uncheckederror** [comment]
I'm not sure that's a good idea. The numbers we offer change all the time and we don't want people click on search results to dead or failed numbers like they are currently doing. Additionally though we have been allowing Google to index our results for the last year, it hasn't resulted in any sales. So we can be pretty confident that looking up specific phone numbers on Google and purchasing them through our website is not how our customers are using our services.
