### ISSUE TITLE
Sound effect clicking button(s) on website

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#130]
**Describe the bug:**
I love to click buttons on the Accelerate Networks website but yet I don't hear anything when I click...

https://www.youtube.com/watch?v=JCGqMvWmWUI

Add effect here
![AN Website home bar](https://user-images.githubusercontent.com/71784487/102473446-51238680-400c-11eb-9d41-fbb49d0e157b.PNG)

**Expected Behavior**
Every time somebody clicks a button on our website I want a dial-pad sound effect similar to the youtube video I shared.

**Comment by uncheckederror** [comment]
@danry25 👀

**Comment by danry25** [comment]
Oh jeez I think this was an actual feature that the client @scottstrong206 had me set up on Wednesday had in the accounting/inventory software they use.

@scottstrong206 you should come with me for their internet installation next week and see what adding DTMF to random buttons looks like in action, its hilarious as an outsider, but a great way to torment the users :P

**Comment by scottstrong206** [comment]
@danry25 what about just a sound effect anytime someone clicks the Accelerate Networks logo on our website?

We need to be thinking outside the phone box here fellas! @uncheckederror

**Comment by danry25** [comment]
I don't particularly like the idea @scottstrong206 , I swear this was one of those "features" implemented by websites in the late 1990s and early 2000s that died off due to it driving people away from the website.

**Comment by danry25** [comment]
@scottstrong206 Closing this as #wontfix as no business justification was provided for this feature request.

**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
