### ISSUE TITLE
Permit blank caller ID on port request submission in Ops app

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#134]
**Describe the bug**
AccelerateNetworks.com tries to force users to enter a caller ID when porting in a phone number, but if the user enters a space as the caller ID it will let you add porting information. This is then trimmed to an empty string, preventing the port request from being submitted in the Ops app.

We discussed adding a checkbox that says "Do not set Caller ID", this would be a decent option for clients that do not want to set their caller name in the line info database.

**Expected behavior**
Permit submitting a port request from the Ops app without setting the Caller ID Name.

**Additional Information**
caller_id is an optional parameter when [submitting a port request to teleapi](https://apidocs.teleapi.net/api/lnp-portability/create-order), we can skip submission of this parameter when the caller ID name is empty and nothing bad will occur.

**Comment by uncheckederror** [comment]
CallerId is no longer a required field on the submission form.
