### ISSUE TITLE
Switch LRN providers

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#135]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Switching will result in significant cost savings, see out of band email @uncheckederror

**Is your feature request related to a problem? Please describe.**
Currently we use [LRNLookup](https://github.com/AccelerateNetworks/NumberSearch/blob/master/NumberSearch.DataAccess/TeleMessage/LRNLookup.cs) from Teli as our primary LRN data source. If we use [LRNBulkCnam](https://github.com/AccelerateNetworks/NumberSearch/blob/master/NumberSearch.DataAccess/BulkVS/LrnBulkCnam.cs) instead we will get a similar dataset.

**Comment by uncheckederror** [comment]
@danry25 The data returned by the BulkVS LRN lookup is not the same as what we're getting from Teli.

For example BulkVS does not return either the date the the number was last ported or the date that the number was first created.

**Comment by danry25** [comment]
The activation date from the BulkVS LRN lookup is the last port date. Do we use the date the number was first created anywhere? I know we stopped showing that data on the Lookups page, not sure if we use it anywhere else.

**Comment by uncheckederror** [comment]
I have remove the date the number was first created and set the last ported date to the activation date.

**Comment by uncheckederror** [comment]
These changes are now live.
