### ISSUE TITLE
Avoid reloading the page when buying phone numbers

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#137]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Customers are confused when the Numbers page reloads when adding a phone number to the cart, as it resets the viewport of their browser causing them to lose track of what else they wish to buy on that same page. 

During the 1 to 2 seconds it takes to reload the user cannot press the Add to cart button to buy another number.

**Describe the solution you'd like**
Create an Add to Cart endpoint and Remove from Cart endpoint that accepts phone numbers, then write javascript to handle the onclickevent of adding a phone number to cart or removing a phone number from cart.

**Additional context**
Split off from issue #124

**Comment by uncheckederror** [comment]
@danry25 I am going to need a gallon of light grey paint to implement this feature.

**Comment by danry25** [comment]
@uncheckederror On it, do you have a particular shade of light grey paint in mind?

**Comment by uncheckederror** [comment]
@danry25 ![image](https://user-images.githubusercontent.com/11726956/104828322-010f2e00-581d-11eb-971c-eb946589b415.jpeg)

**Comment by uncheckederror** [comment]
@danry25 okay this is live try it out.

**Comment by danry25** [comment]
Neat, it works! I did find a way to cause a UI inconsistency, if I press Add to Cart on multiple numbers at the same time, the counter only increments up by 1 (until I do a full page refresh or click on the cart, all numbers are present in the cart as expected):
![Screenshot from 2021-01-17 20-03-20](https://user-images.githubusercontent.com/1683673/104871181-40ae4680-58ff-11eb-8f96-fd25f89c8e60.png)

**Comment by uncheckederror** [comment]
@danry25 the cart counter bug is fixed now. Please try it out.

**Comment by danry25** [comment]
@uncheckederror Seems to work really well, thanks for all your hard work on this!
