### ISSUE TITLE
Hardware Inventory System

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#139]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uncheckederror** [comment]
@danry25 please try it out. https://ops.acceleratenetworks.com/Home/Inventory

**Comment by danry25** [comment]
Can we modify the header on Inventory to have a dropdown on Name and hide the product ID? This would make it similar to how Shipments work at the bottom of the page.
![Screenshot from 2021-02-10 12-06-54](https://user-images.githubusercontent.com/1683673/107565391-84ac0880-6b98-11eb-9594-7974aec45f72.png)

**Comment by uncheckederror** [comment]
Well so that form is for creating a product. Therefore you wouldn't know what the name is prior to its creation.

**Comment by danry25** [comment]
How would I go about editing the Price, Description, name or Publicly Visible status of a product?

**Comment by uncheckederror** [comment]
I have updated this to use the shipments to total up the available product quantities.

**Comment by danry25** [comment]
This system works, @Chattaeus and I just need to true up our inventory to make full use of it.
