### ISSUE TITLE
[MOONSHOT] Automatically Order Additional Hardware from TeleDynamics

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#140]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uncheckederror** [comment]
This work is blocked until we resolve issue #139.

**Comment by danry25** [comment]
Can we create a draft order of hardware to order with TeleDynamics perchance? Or maybe make a page or email of suggested items and quantities to order?

**Comment by uncheckederror** [comment]
Yeah, we could do something like that. I'm not sure what the exact shape would look like or what would trigger the creation of the draft TeleDynamics order. We might have to figure that out as we build this feature.

**Comment by danry25** [comment]
What we have discussed is for customers that seek direct fulfillment (eg: ship our new hardware to the client's office address), we can enable one click submission of the hardware order just like we do with port requests.

Once the order is submitted to TeleDynamics we get an order number back, which we should check once an hour for tracking information (which we should relay to the client) and for the MAC addresses and serial numbers of the devices that shipped so we can provision them in GDMS/YDMS and FusionPBX. Once the order has switched to closed status we should stop querying TeleDynamics for order information.

Indirect Fulfilment is TBD

**Comment by uncheckederror** [comment]
How should I fill out these parameters when creating the order?

```
{
  "OrderNumber": "string",
  "PONumber": "string",
  "Status": "string",
  "SubTotal": 0,
  "OrderTotal": 0,
  "BillingType": "NetTerms",
  "HoldRequest": true,
  "IsProvisioningOrder": true,
  "ServiceProvider": "string",
  "ShippingType": "PartialBlind",
  "Shipping": {
    "Carrier": "string",
    "ShippingMethod": "FED_2DY",
    "Quote": 0
  },
  "TrackingInformation": [
    {
      "Carrier": "string",
      "TrackingNumber": "string",
      "Status": "string",
      "ShipDate": "2021-10-30T22:02:19.851Z",
      "ProductNumbers": [
        {
          "PartNumber": "string",
          "Quantity": 0
        }
      ]
    }
  ],
  "ShippingAddress": {
    "Label": "string",
    "Address1": "string",
    "Address2": "string",
    "City": "string",
    "State": "State",
    "ZipCode": "string",
    "Country": "USA",
    "StateOrProvince": "string"
  },
  "EndUserAddrses": {
    "Label": "string",
    "Address1": "string",
    "Address2": "string",
    "City": "string",
    "State": "State",
    "ZipCode": "string",
    "Country": "USA",
    "StateOrProvince": "string"
  },
  "ShipmentTypeAddressKey": 0,
  "OrderLines": [
    {
      "ProductName": "string",
      "PartNumber": "string",
      "Quantity": 0,
      "UnitPrice": 0,
      "ExtPrice": 0,
      "Firmware": "string",
      "SerializationInformation": [
        {
          "MAC": "string",
          "SerialNumber": "string"
        }
      ],
      "IsBackorder": true,
      "QtyBackOrdered": 0,
      "ShouldProvision": true
    }
  ],
  "CreateDate": "2021-10-30T22:02:19.851Z",
  "LastChangeDate": "2021-10-30T22:02:19.851Z",
  "SignatureRequired": true,
  "UseTPP": true,
  "ProvisionUrl": "string",
  "ServerUserName": "string",
  "ServerPassword": "string",
  "Notes": "string",
  "JobReferenceNumber": "string",
  "CalculateShipping": true
}
```

**Comment by danry25** [comment]
I have emailed Brad at TeleDynamics to clarify which of these fields are required and get an example of this JSON body.

Also inquired about how to get shipping estimates (ETA for each option and the shipping costs). Figure we can round this up to the nearest $10 increment for everything besides ground shipping?

**Comment by uncheckederror** [comment]
Yes, rounding up is ideal.

**Comment by uncheckederror** [comment]
Create a quote with the correct quantities and SKUs using the Telodynamic API. Then we need to convert the quote into an order by attaching a shipping address, shipping type, and a payment method.

**Comment by danry25** [comment]
Deliverables for Dan:
- Provide a tested submitted JSON for an order

**Comment by danry25** [comment]
Closing as wontfix
