### ISSUE TITLE
No date picker shown in Firefox when placing an order

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#144]
**Describe the bug**
When placing an order on AccelerateNetworks.com, the field that requests a preferred install date is just a freeform text field. Should this be a date picker?

**Comment by uncheckederror** [comment]
Can you clear your cache and get screenshot of the issue? Are there any errors in the browser console?

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/106845614-25ae3700-6660-11eb-96da-c2a416b92bce.png)

It looks like a text box on iOS until you click on it, at which point it prompts you with the image above.

**Comment by danry25** [comment]
It appears [Firefox does not support type="datetime-local"](https://caniuse.com/input-datetime), @uncheckederror could you either split this into [separate type="date" and type="time" inputs](https://stackoverflow.com/questions/26495326/alternative-to-datetime-local) or use a polyfill?

**Comment by uncheckederror** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

It's a webstandard, what are they doing?

We already have a text fall back that provides data in the same format. I don't see an advantage to breaking this functionality for all other browsers to make it a slightly less awkward experience for Firefox users.

**Comment by danry25** [comment]
@uncheckederror That is reasonable, can you put a polyfill in place then?

**Comment by danry25** [comment]
Currently in Firefox you are unable to submit the order unless you guess the right format (which is 2021-02-22T11:43 or similar).

Thoughts on using a polyfill @uncheckederror or hiding this when Firefox is detected and making the field optional moving forward?

![Screenshot from 2021-02-08 11-45-24](https://user-images.githubusercontent.com/1683673/107279172-8dbb9f00-6a0b-11eb-85a4-92aa5d649521.png)

**Comment by uncheckederror** [comment]
Still considering the our options. If we wait long enough Firefox might get around to implementing this standard. This field is now, and has always been optional. As are all the fields under the "Installation Information" header.

**Comment by danry25** [comment]
Hmm, I was unable to submit the order without filling in the Preferred Installation Date with a valid value. Firefox does not seem to be handling that this form field is optional...

Datetime-local is a web standard, but Apple only started supporting it a few months ago in Safari, and Mozilla has made no progress in implementing it [over the last 8 years](https://bugzilla.mozilla.org/show_bug.cgi?id=888320) in Firefox Desktop. I wouldn't hold my breath on Mozilla getting their act together on datetime-local.

**Comment by uncheckederror** [comment]
Looks like they are going to implement it: https://bugzilla.mozilla.org/show_bug.cgi?id=1283388#c2

**Comment by danry25** [comment]
This appears to work properly in Firefox Android now, woo!
