### ISSUE TITLE
Billing Client Id and Owned By are not set when a phone number is ordered

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#145]
**Describe the bug**
When a customer orders or ports a number on AccelerateNetworks.com and a bill or quote is generated, we should set the Billing Client ID to what is held by InvoiceNinja.

Is Owned By supposed to be the human readable name of the client? Perhaps we shouldn't allow setting of this field by humans, and instead the Ingest app will pull this from InvoiceNinja based on the Billing client ID

**Expected behavior**
The Billing client ID should be associated with an owned phone number when the order is initially submitted.

**Comment by uncheckederror** [comment]
Fake News

**Comment by uncheckederror** [comment]
This feature is now being tracked in #147.
