### ISSUE TITLE
Owned Phone Numbers - Multi-select edit

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#146]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This feature saves labor when updating records by enabling many phone numbers to be selected and updated simultaneously in the Ops application under Owned Numbers.

**Describe the solution you'd like**
A checkbox next to each number, which when checked triggers a bulk changes menu that enables you to update the Notes and Billing Client ID of an owned phone number.

**Additional context**
Here is an example of Teli's implementation of this same feature:
![image](https://user-images.githubusercontent.com/1683673/107588057-cd26ee80-6bb7-11eb-86b4-ba355d797ea9.png)

**Comment by uncheckederror** [comment]
Building this would require an authenticated REST API to be part of the Ops app. Adding something like that would be a significant increase in complexity and maintenance burden.
