### ISSUE TITLE
Tax Rates - Failed to create a Tax Rate

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#149]
**Describe the bug**
I tried to generate a tax rate for a specific address in ZIP 98372, then I tried generating a tax rate for 98372 in the Ops app, but all attempts failed. Is the Washington State API down again?

**To Reproduce**
1. Go to ops.acceleratenetworks.com
2. Click on Tax Rates
3. Scroll down to Tax Rate by Address
4. Enter an address or Zip code, then press Create
5. See error (picture below)

**Expected behavior**

**Screenshots**

![Tax Rates](https://user-images.githubusercontent.com/71784487/107695754-e0909300-6c65-11eb-8ae2-123f9c02ca7e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by uncheckederror** [comment]
Huh, seems to work for me?

![image](https://user-images.githubusercontent.com/11726956/107697107-a88a4f80-6c67-11eb-9ed3-820437dfbaec.png)

**Comment by uncheckederror** [comment]
2021-02-11 13:49:14.302 -08:00 [FTL] Call failed. The SSL connection could not be established, see inner exception: GET https://webgis.dor.wa.gov/webapi/AddressRates.aspx?output=xml&addr=4415%2031st%20Ave%20W&ci$2021-02-11 13:49:14.314 -08:00 [FTL]    at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveStream(Task`1 response)
   at NumberSearch.DataAccess.SalesTax.GetAsync(String streetAddress, String city, String zip) in /home/vsts/work/1/s/NumberSearch.DataAccess/SalesTax/WA.cs:line 117
   at NumberSearch.Ops.Controllers.HomeController.TaxRatesCreate(TaxRateResult location) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/HomeController.cs:line 594

**Comment by uncheckederror** [comment]
@danry25 based on our conversation can you work some ngnix magic?

**Comment by danry25** [comment]
I think the [openssl config is setting the system level too high](https://www.reddit.com/r/freeswitch/comments/duzzt2/problems_with_tls_after_upgrading_from_debian_9/) for TLS, as Washington State's API webserver appears to use obsolete ciphers, has a 1 second clock skew, and is likely behind an F5 Networks load balancer (the same ones that caused TLSv1 breakage).

I have altered this, let me fix Nginx and then you can restart the app @uncheckederror ?

**Comment by uncheckederror** [comment]
Sounds good @danry25

**Comment by danry25** [comment]
I restarted nginx and numbersearchops after making this change, but the tax rate lookup still returns "Failed to create a Tax Rate for 2318 E Cherry St, Seattle, 98199."

@uncheckederror Is the HTTPS connection to https://webgis.dor.wa.gov/webapi/ opened by the Ops app or by the Ingest app?

**Comment by uncheckederror** [comment]
By the Ops app

**Comment by danry25** [comment]
Crumb, I am not sure what is wrong then. [Can you get what URL is being constructed here](https://github.com/AccelerateNetworks/NumberSearch/blob/6e1a31d0d68494a0441be6fe98c22d04d4afc1be/NumberSearch.DataAccess/SalesTax/WA.cs#L92) and I can test further?

**Comment by uncheckederror** [comment]
Well I could write something to selfhost this service this weekend, and then we can just be done with this dependency. Or you could file a ticket with the state?

**Comment by danry25** [comment]
I emailed the state already, hopefully they will fix their API.

**Comment by uncheckederror** [comment]
@kylek206 @scottstrong206, @danry25 is communicating with the tech support people at the State to get this issue resolved.

**Comment by danry25** [comment]
@uncheckederror I have made no progress getting the State of Washington to acknowledge that there is a TLS issue breaking queries to the tax rates API from DigitalOcean.

We could move AccelerateNetworks.com to a different host like Linode, where these queries do work fine from, or downgrade to not using TL[S when querying this API](https://github.com/AccelerateNetworks/NumberSearch/blob/master/NumberSearch.DataAccess/SalesTax/WA.cs#L84).

**Comment by uncheckederror** [comment]
@scottstrong206 I've release an update that should fix this issue, can you try it again? Thanks

**Comment by danry25** [comment]
@uncheckederror The tax rates API still fails over HTTP inconsistently when accessed from DigitalOcean. One minute it will work, the next it will fail to give a valid response.

**Comment by uncheckederror** [comment]
@danry25 I don't have any options to offer until I finish reimplementing this Tax Rates API.

**Comment by danry25** [comment]
@uncheckederror Guessing you already added retry logic to this API?

**Comment by uncheckederror** [comment]
@danry25 The query will be retry 10 times before failing out now.

**Comment by scottstrong206** [comment]
Invoice 2443 generated without a tax rate. Perhaps the suite number broke the tax rate lookup?

**Comment by uncheckederror** [comment]
Yep, that's probably what happened. It should fall back to the zip code only method if that happens though. I'll investigate.

**Comment by uncheckederror** [comment]
I have deployed new builds of the Mvc and Ops apps where the dependency on the state's sale tax API is replace with our own Sale Tax API.
