### ISSUE TITLE
Port Request Bill Image upload breaks on large files

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#150]
**Describe the bug**
Files that are more than 1 MB can't be uploaded during the port request process on the website.

**To Reproduce**
Attempt to upload a large PDF into the port request process.

**Expected behavior**
File of up to 100 MBs should be uploadable.

**Comment by uncheckederror** [comment]
Based on our conversation @danry25 needs to update the ngnix configuration to allow for larger files to be handled by the web server.

**Comment by danry25** [comment]
I implemented a fix for this, but when I try to upload a bill it still says Choose File and I don't see the file getting uploaded in Dev Tools. I tested in Firefox 78.7.0esr (64-bit) and Chromium Version 87.0.4280.141 (Developer Build) built on Debian 10.7, running on Debian 10.7 (64-bit).

**Comment by uncheckederror** [comment]
Look in the ops app, it's there.

The file gets uploaded when you submit the page, not before.
________________________________

**Comment by danry25** [comment]
@scottstrong206 This bug is now fixed, feel free to upload bills along with port requests!
