### ISSUE TITLE
Port completion date not set in notification email body or title on mixed port requests

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#153]
**Describe the bug**
When only some phone numbers have a port completion date set, the first sentence in the body of the email does not mention a date on which the port request will complete. The title also fails to include the date the port request is set to complete on.

**To Reproduce**
1. Go to AccelerateNetworks.com
2. Submit a port request where some numbers are actually on a different account (causing them to not get FOC)
3. Look at email sent to client when only a subset of phone numbers associated with the port request have a FOC date set
4. See incomplete first sentence with date missing just before the exclamation point

**Expected behavior**
The FOC date that we just detected should be inserted into the end of the first sentence just before the exclamation point.

**Screenshots**
![image](https://user-images.githubusercontent.com/1683673/108587511-d37c3f80-7308-11eb-84e5-d1d3c18f9dd7.png)

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Mail Client: Thunderbird

**Comment by uncheckederror** [comment]
The reason that the number and FOC date are blank in this email is because the first number in the list does not have an FOC date set.
