### ISSUE TITLE
Refer user directly to quote or invoice

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#157]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
We should direct users to the InvoiceNinja invoice or quote after order submission (maybe embed this on the order confirmation page?). This will enable clients to pay us sooner, improving revenue.

**Additional context**
Currently the client has a link to the quote or invoice emailed to them, but this is not a strong call to action to take the next step.

**Comment by uncheckederror** [comment]
So we are skipping the order submission success page, and then bumping them into the link we currently include in the email?

**Comment by danry25** [comment]
Not sure if that is an ideal workflow, maybe open the Order Confirmation page in a new tab and redirect the current page to InvoiceNinja?

Or perhaps embed the customer view of the invoice in the Order Confirmation page?

**Comment by uncheckederror** [comment]
Is the one time link to InvoiceNinja really a one time link? It looks like you can click on it repeatedly and it will take you to the same invoice in the billing system.

If this is the case, then we can use it in the order submission success page and in the confirmation email.

**Comment by uncheckederror** [comment]
@danry25 I have pushed these changes to the site, please complete a test order to try them out.
