### ISSUE TITLE
Call to action on Hardware, Services and Numbers pages

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#158]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
When you add a service, product or phone number to the cart you need to scroll to the top of the page and click on Cart to check out.

The call to action to move to the next page (eg: Phone Numbers or Hardware is hidden at the bottom of the page, and the user isn't guided to look at the Services page if they do not start there, nor is the Hardware page recommended to the user if they start by purchasing or porting a phone number.

**Is your feature request related to a problem? Please describe.**
The current structure of the Products, Services and Numbers pages burys the lede and requires that a sales agent shepherds a new client through the process. We should try sheperding them by adding buttons to the unused left and right sides of these pages?

**Describe the solution you'd like**
If a user has only a Service, Product or Phone Number in cart we should provide a button that is a call to action on the left and right sides of the Hardware, Services and Numbers page to head to the other pages and checkout.

**Comment by uncheckederror** [comment]
I get that we want to take a more aggressive approach to pushing customers through to checking out their cart, but I'm not sure exactly what this will look like. 

The right and left hand sides of the page aren't unused per se, rather they are the margins of the page that we expand and contract to keep the design of website responsive to changes in screen-size. 

We could add a column on the right hand side of the page that shows the users current cart and has a call to action for checking out on every page. The column would be the same as the "Your Order" column on the submitted Order form here: https://acceleratenetworks.com/cart/order/9b89cdec-6c61-4840-92e9-e4f9c62b9866

But a permanently visible cart would add clutter to these pages and would have to be disappeared on mobile devices. So this change would not be without costs.

**Comment by danry25** [comment]
After further discussion the plan is to fix the top bar to the top of the viewport (like done in [the Bootstrap documentation](https://getbootstrap.com/docs/4.3/layout/overview/)).

Additionally, on the Services page we should move the Add Hardware button to a row at the bottom of the viewport to prompt our clients to move to the next step in the ordering process. The Hardware page should have two buttons fixed to the bottom of the viewport, (left arrow here) Services and Numbers (right arrow here), and the Numbers page should have buttons like (left arrow here) Hardware and Checkout (Shopping cart icon) fixed to the bottom of the viewport.

On the checkout page, we still need to add a call to action if the user's cart does not contain at least a Service, Hardware and Number. Whatever the missing category of item is, we should invite the user to add these to their cart (though this is not mandatory, we are just trying to encourage them to add these to their order).
