### ISSUE TITLE
Show Number Search above the fold on the home page

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#159]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Highlighting a key differentiator where people can find a phone number and emotionally invest in buying that particular number will improve sales and ensure they complete the checkout process.

**Describe the solution you'd like**
Adding the Number Search form right below the video on the home page should hopefully improve conversions of visitors to paying clients.

**Comment by uncheckederror** [comment]
I am not sure this is a good idea. If we put a specific product on the home page, it will define what external groups see as our core business.

As an example of an alternative direction, we could put the top two items (lines and seats) from the Services page on the home page.

Do we want to be a phone number sales service (which so far hasn't produced significant organic revenue) or do we want to sell VOIP service and accessories (the bulk of our current direct-sales revenue)?
