### ISSUE TITLE
Always Charge Port Fees

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#160]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This will improve revenue by capturing additional revenue for a process that requires manual time and effort. 

**Is your feature request related to a problem? Please describe.**
This feature would help solve the confusion of when a customer is going to pay a port fee. 

**Describe the solution you'd like**
Whenever a new client is going to submit a port request they will automatically get charged a port fee unless in the notes field we indicate "waive port" (please make this case insensitive and search for this string inside the notes field, as there may be other notes included)

**Describe alternatives you've considered**
We discussed manually adding or removing the port fee but that causes confusion with the sales team and customers of when a port fee will be charged. 

**Additional context**
N/A

**Comment by danry25** [comment]
@uncheckederror Yes, remove the automatic discounting process.

Perhaps we should add a promotions field in addition to notes? The goal is to have the initially generated invoices be accurate moving forward.

**Comment by uncheckederror** [comment]
We could do promo codes where the codes are added like items to your cart so you can see it in the order before you submit it.

**Comment by uncheckederror** [comment]
I have removed the code that automatically discounted ported phone numbers and I have added a coupon system to allow for the discounting of all the ported phone numbers in an order.
