### ISSUE TITLE
HTTP ERROR 405 when porting number

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#161]
**Describe the bug**
I was going to submit a port request I added the first number to the cart and it worked normally. However, the next number I got an error code on the website "HTTP ERROR 405"

**To Reproduce**
1) add number to cart
2) attempted to add 2nd number to cart

**Expected behavior**
it would add to cart like normal

**Screenshots**
![image](https://user-images.githubusercontent.com/71784487/109885200-f83eb400-7c32-11eb-9782-21802c2b12c5.png)

**Desktop (please complete the following information):**
 - On my windows laptop
 - chrome
 
**Additional context**
N/A

**Comment by uncheckederror** [comment]
Hey Scott, thanks for reporting this issue. I will investigate.

**Comment by danry25** [comment]
@scottstrong206 This seems to work fine for me, if you could provide the affected numbers to us via email along with how they were formatted (eg: 206-858-8757, (206) 858-8757, etc) when submitted and whether you ran this through the Lookups page or the Numbers page, that would be quite helpful!
