### ISSUE TITLE
Charge money for on site installations

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#163]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
We will make more money by charging for installing phone hardware on site.

**Is your feature request related to a problem? Please describe.**
Currently the website sets an expectation that every order gets an installation date set, even when no hardware is ordered. Calendar invites are sent immediately without being approved in the Ops app.

**Describe the solution you'd like**
We should only show the installation date picker when hardware is ordered, and we should default to Remote Install (We guide you through plugging in your pre-configured phones!), with an option for In Person Installation (Only available in the Greater Seattle Area, $60 for the first half hour and $98/hr thereafter).

If In Person Installation is selected, charge $60 for installation of the first piece of hardware and add 15 minutes of billable labor for each phone thereafter. Mark the hours as an estimate!

We should also add a way to use a promotion to waive the installation fee.

**Comment by uncheckederror** [comment]
When there are no products in the order the install date is greyed out:

![image](https://user-images.githubusercontent.com/11726956/110015366-a0f31f00-7cd8-11eb-818b-de313482b6f6.png)

When you add any piece of hardware, the install date becomes settable again.

![image](https://user-images.githubusercontent.com/11726956/110015467-bcf6c080-7cd8-11eb-8f34-70637d80287e.png)

**Comment by uncheckederror** [comment]
> we should default to Remote Install (We guide you through plugging in your pre-configured phones!), with an option for In Person Installation (Only available in the Greater Seattle Area, $60 for the first half hour and $98/hr thereafter).
> 
> If In Person Installation is selected, charge $60 for installation of the first piece of hardware and add 15 minutes of billable labor for each phone thereafter. Mark the hours as an estimate!
> 
> We should also add a way to use a promotion to waive the installation fee.

How should we show remote install versus in-person installation option on this checkout page and explain the terms and work rates?

**Comment by uncheckederror** [comment]
I have update the Mvc add so that when hardware is part of your order you are presented with a choice between Remote or Onsite installation and added some flavor text to explain the options. If onsite installation is selected a $60 call out charge is added to the upfront invoice.

![image](https://user-images.githubusercontent.com/11726956/110230267-9eedb380-7ec4-11eb-9958-72679893ab69.png)
