### ISSUE TITLE
Link to Phone specific pages from Hardware page

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#164]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
By adding a hyperlink to each phone card that links to the adjoining Phone specific videos/quick guide material, we will enable customers to easily envision themselves using these phones. Perhaps we should just add this as a user settable field in the Ops app for each hardware item?

**Is your feature request related to a problem? Please describe.**
Potential customers do not know where to go to get more information on a specific model of phone, if we can steer them to the right destination without googling we can improve our full price conversion rate.

**Comment by uncheckederror** [comment]
I have added this as text link that can be defined in the Ops app. Support links will not be shown on the Hardware page unless a link actually exists.

**Comment by uncheckederror** [comment]
This feature only applies to 2 of the phones on the Hardware page because we no longer list the GXP2135 for sale.

![image](https://user-images.githubusercontent.com/11726956/109912812-a9f4d980-7c61-11eb-8b5c-daad3632e8d7.png)

**Comment by danry25** [comment]
@uncheckederror We should fix that and list it at $115ea (MSRP), as Scott & Kyle sell it on a daily basis. We are listing even older phones like the GXP2140...

**Comment by uncheckederror** [comment]
@danry25 I have added it to our listings.

![image](https://user-images.githubusercontent.com/11726956/109917000-7322c180-7c69-11eb-8064-9ca515d1b963.png)
