### ISSUE TITLE
Add an image of each phone to Support Page

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#165]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Customers will be able to navigate to the correct phone specific support page (containing our videos) without getting confused trying to figure out what model of phone they have.

**Is your feature request related to a problem? Please describe.**
Most Grandstream phones do not have their model number shown on the front of the phone.

**Describe the solution you'd like**
Add a moderately sized image of each phone to the relevant button on [the support page](https://acceleratenetworks.com/Home/Support).

**Comment by uncheckederror** [comment]
@danry25 how about this?

![image](https://user-images.githubusercontent.com/11726956/109908706-95144800-7c59-11eb-8f3d-42aea04dadbb.png)

**Comment by danry25** [comment]
Looks quite nice!
