### ISSUE TITLE
Additional Hardware Videos

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#166]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Making additional videos about each model of phone will help potential clients envision using our phones. Additionally, new clients can setup and use their phones more easily thanks to these videos

**Is your feature request related to a problem? Please describe.**
Clients often feel an inability to perform basic functions on their phone or setup/move their phone despite the relative simplicity of these tasks. Providing visual guidance by showing how easy it is to do this will make our clients happier!

**Describe the solution you'd like**
We should do a setup video for each model of phone we sell (assembly, plugging in power/network/WiFi), cover using Bluetooth, adjusting ringtones, volume, wired headsets, etc

**Additional context**
@Chattaeus Can you block out time this week to work on this? I want to cover all hardware that is listed on the hardware page (@uncheckederror The GRP2612/2613 can link to the GRP2615 page, and the GXP2135/2140/2160 can link to the GXP2170 page) and also cover the Yealink T54W and Yealink CP930W.

**Comment by uncheckederror** [comment]
@danry25 I have update the links on the hardware page to direct the GRP2612, GRP2612 Wifi, and GRP2613 to the GRP2615 support videos page. I have also update the links so that the GXP2140 and GXP2160 link to the GXP2170 support videos page. The GXP2135 has it's own support videos page so I've left that alone rather than redirecting it to the GXP2170 page.

We do not have support videos for any Yealink devices.

**Comment by uncheckederror** [comment]
@Chattaeus filmed videos for one of the Yealink (pronounced Yay-link) devices last night. I am waiting for links to the videos to be provided before I can create a support page for it.

**Comment by Chattaeus** [comment]
Have the first 9 uploaded to a playlist and on Youtube. They can be viewed here. Waiting on the last 2 to upload.

**Comment by uncheckederror** [comment]
We currently don't list either of the Yealink T54W and Yealink CP930W on our website.

**Comment by uncheckederror** [comment]
@Chattaeus plz review the text steps https://acceleratenetworks.com/Phones/T54W

**Comment by uncheckederror** [comment]
This work was completed as part of #183.
