### ISSUE TITLE
Update homepage flavor text

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#168]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
A more concise description of the Number Search feature will encourage more people to try it!

**Is your feature request related to a problem? Please describe.**
The current flavor text is not concise in the context of being above the fold on the front page.

**Describe the solution you'd like**
Update the text under Number Search title on the homepage to say:
Find the perfect number! Enter an area code or word and press Search to see what is available.

Hide the transfer button as well. Also, update our phone number to (206) 858-8757 (adding a dash).

**Comment by uncheckederror** [comment]
Here's the result of these changes on the homepage:

![image](https://user-images.githubusercontent.com/11726956/111061129-9f52f500-8456-11eb-87cc-afe660d0c010.png)
