### ISSUE TITLE
Add images for hardware page

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#177]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Offering more items for sale will enable us to improve revenue

**Is your feature request related to a problem? Please describe.**
We don't currently list all of the phones we sell on the website.

**Describe the solution you'd like**
Add the photos for the following items so we can add the items to the hardware page:
https://www.teledynamics.com/#/productdetails/YEA-WH62-DUAL-UC - $200
https://www.teledynamics.com/#/productdetails/YEA-WH63-UC - $200
https://www.teledynamics.com/#/productdetails/YEA-WH62-MONO-UC - $180
https://www.teledynamics.com/#/productdetails/YEA-SIP-T54W - $280
https://www.teledynamics.com/#/productdetails/YEA-SIP-T57W - $360

**Comment by uncheckederror** [comment]
ok

**Comment by uncheckederror** [comment]
These images and products are live on the hardware page. The prices and descriptions need to be updated for accuracy.

**Comment by danry25** [comment]
I have updated the description for these items, and I am sure @scottstrong206 would appreciate your slight price bump on the Yealink WH62 Mono :D

Can we also add these items? I have already built out the item in the Ops app, just add the image path and make it publicly visible.
https://www.teledynamics.com/#/productdetails/YEA-BLT60
https://www.teledynamics.com/#/productdetails/YEA-CP960-WM

**Comment by uncheckederror** [comment]
Those two images are now live on the hardware page.
