### ISSUE TITLE
Current Version File for Linphone Android

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#180]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Linphone Android checks a RELEASE file to see if there is a new version available, this is hosted on a website. Currently we have not overriden this string in our custom build, meaning the Linphone release on April 6th 2021 causes our build to warn that it is out of date.

This creates additional support burden needlessly, which can be eliminated by hosting our own version of [the RELEASE file](https://www.linphone.org/releases/android/RELEASE).

**Describe the solution you'd like**
Host a RELEASE file at https://acceleratenetworks.com/releases/android/RELEASE containing the following string:
```
4.3.1	https://play.google.com/store/apps/details?id=com.acceleratenetworks.linphone
```

**Comment by uncheckederror** [comment]
@danry25 can you provide an example "release" file? I'd like to review the formatting, or is it literally just this one line?

**Comment by danry25** [comment]
@uncheckederror See Linphone's Release file linked to at the end of the second paragraph of the "How will this improve revenue or reduce our costs? Please provide a complete explanation!" section. It appears to just be a plain text file containing just one line.

**Comment by uncheckederror** [comment]
Okay, this change has been shipped. 

https://acceleratenetworks.com/releases/android/RELEASE

**Comment by uncheckederror** [comment]
@danry25 can you close this if we're good?
