### ISSUE TITLE
Number Search by Location/Ratecenter

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#181]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Currently customers ask about why our numbers show up as Vashon or why they can't find a number for the specific city they operate in when they're available, just further down the list. It would allow customers to feel more comfortable with ordering numbers on their own if they can search them just by the city they want.

**Is your feature request related to a problem? Please describe.**
Customers have asked before why they can't find a number for their specific city, when it is available just down the list. This would make them happier more likely to order numbers on their own.

**Describe the solution you'd like**
It would be nice if we were able to search by ratecenter, (e.g. type in Bellevue and all the numbers in that rate center show up). It would help in the ways described elsewhere.

**Describe alternatives you've considered**
The only alternative I'm aware of is to change the caller ID on every new number. That takes support time and costs $5/ea.

**Comment by danry25** [comment]
@Chattaeus Please use the correct template for feature requests, and label the issue appropriately (is this internal facing only (eg: Ops app) or external (acceleratenetworks.com), are you asking for a new feature (enhancement) or is a current feature broken (bug)?

Here is a list of ratecenters for [360](https://localcallingguide.com/lca_listexch.php?npa=360) and [541](https://localcallingguide.com/lca_listexch.php?npa=541), note that a ratecenter is a small geographical area served by a handful of central offices by the incumbent telecom company (eg: Centurylink, Frontier, Verizon), and [the LATA](https://en.wikipedia.org/wiki/Local_access_and_transport_area) is the local calling area for ratecenters within those boundaries. [Here is a bit more background on LATAs](http://www.longdistancephonedepot.com/latas.htm).

@uncheckederror We can use [this XML API](https://localcallingguide.com/xmlquery.php) to fill in data for Endstream/FirstPoint numbers that do not have LATA information.

**Comment by Chattaeus** [comment]
@danry25 When I created the issue I thought I answered all the questions is asks you to answer when creating the issue, where is the correct template? I filed this under feature requests, wouldn't everything under that category be an "enhancement" since we're requesting a feature?

Regardless it seems like something @uncheckederror might be able to do. My number being listed as Vashon has generated a lot of questions and I'm sure customers would feel more comfortable with purchasing numbers on their own if it shows the city of their choosing and they can find that easily.

**Comment by danry25** [comment]
@Chattaeus When you create a new issue you should see this: 
![image](https://user-images.githubusercontent.com/1683673/114598235-8781b300-9c46-11eb-83b7-b03c1df5e196.png)
Both choices will send you to a template that asks you a few questions:
![image](https://user-images.githubusercontent.com/1683673/114598411-b6982480-9c46-11eb-82db-242c894a316a.png)

Guessing you cleared this template out when creating your issue. That is not acceptable, and @uncheckederror generally refuses to work these types of issues (we're lucky he hasn't closed it with a tag of wontfix).

You can edit your original comment and the title (not sure why this has "Request for" prefixed, aren't all these issues just requests?), also ensure that you tag this as internal or external like I mentioned earlier.

This feature request is possible, but perhaps hiding ratecenters by default might be the better UX choice. For most customers, the last time a ratecenter mattered was in the early 2000s.

**Comment by Chattaeus** [comment]
I'll add the template in.

I disagree on the last point, that city that shows up in the caller ID by default generates a lot of questions. It may not make much difference on our end but people tend to assume you are from exactly where it says. Unless we want to change caller ID for every number people will ask about it.

**Comment by danry25** [comment]
We should be setting the caller ID for every number used for outbound calling. It is on the issue backlog for us currently.

**Comment by uncheckederror** [comment]
> This feature request is possible, but perhaps hiding ratecenters by default might be the better UX choice. For most customers, the last time a ratecenter mattered was in the early 2000s.

Should I remove the city/state column from the number search results?

**Comment by danry25** [comment]
@uncheckederror No, lets keep it. By Recommended and Sequential, could a third button be added to filter by ratecenter?

**Comment by uncheckederror** [comment]
Try it out here: https://acceleratenetworks.com/Search?Query=hello&View=Location&Page=1

The results are ordered by the ratecenter/city name from A to Z.

**Comment by Chattaeus** [comment]
Looks good. Is there any way to search by location? About the only way I could find was to sort by location and then change the page number in the URL since you can only scroll through one page at a time. If not this is still definitely an improvement.

**Comment by uncheckederror** [comment]
@Chattaeus there is currently no way to search by location. We could add this ability @danry25.

**Comment by danry25** [comment]
@uncheckederror I thought I was asking to filter by ratecenter in my comment yesterday, not just sort by ratecenter?

Additionally, the ratecenter names in your example link from earlier today are ugly, I think it would be best if we replaced them with the actual city name and 2 character state from [this API](https://localcallingguide.com/xmlprefix.php?npa=774&nxx=355) (specifically see the nicely formatted rc and region tags). Showing Buzzards Bay, MA is much better than showing BUZZARDSBY, MA (which is what we show for 774-355 currently).

**Comment by uncheckederror** [comment]
I have integrated the API you provided into the ingest process to clean up the ratecenter/region names. We preform lookups on numbers ingested from BulkVS and FirstCom as the data they provide is lame or non existent.

**Comment by uncheckederror** [comment]
How are we going to handle the mixing of location names and phone numbers? The existing search process will convert all text characters to the matching number on a telephone dial pad. We could have a completely separate search page that only looks through ratecenters and regions. The primary search page would be search by dialed number and the secondary page would be search by location name. I am thinking aloud here.

**Comment by danry25** [comment]
@uncheckederror When someone clicks on Location why don't we just show them a list of ratecenters with available numbers, and place a checkbox next to each ratecenter?

In most area codes we only stock numbers in a handful of ratecenters.

**Comment by uncheckederror** [comment]
@danry25 @Chattaeus ok, try this out: https://acceleratenetworks.com/Search?Query=425&City=Halls%20Lake&View=Location&Page=1

**Comment by Chattaeus** [comment]
Oh that's good. That's really good. You're like a wizard or something.
