### ISSUE TITLE
Website Video Updates

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#183]
**Describe the bug**
We have an video that has a newer version (T54W Initial Setup) and 2 missing videos wifi and change ringtone for the T54W. The current list of T54W videos is here:

https://www.youtube.com/playlist?list=PLy8FSfLD62uOI8IdA_GYBCo7fjFN-v6Hd

The same changes will need to be made for the 2615 and 2170, 2135 less wifi for the latter models. Playlists below:

https://www.youtube.com/playlist?list=PLy8FSfLD62uOCqDyG130sZvnZO97rLygm

https://www.youtube.com/playlist?list=PLy8FSfLD62uMbuJIjxrjBsCMKsZ2Wpknp

https://www.youtube.com/playlist?list=PLy8FSfLD62uME4KaKtMl5LKJ5zAGN6z05

Also we now have videos for 3 models of cordless handset available. Playlists below:

https://www.youtube.com/playlist?list=PLy8FSfLD62uOADcIic97BbY1gmfDoHTa5

https://www.youtube.com/playlist?list=PLy8FSfLD62uPCyGUdT1bpxa5nCPiIzof_

https://www.youtube.com/playlist?list=PLy8FSfLD62uO1DDFDp9iiivRi1nusdGnD

On a grammatical note, there are typos on the videos page e.g. "Perform a blind Call Transfer" should be either "Perform a blind call transfer" or preferably be "Perform a Blind Call Transfer" since it's a title. Most titles in the table of contents are having the same issue. Please capitalize where appropriate.

**To Reproduce**
Visit website.

**Expected behavior**

**Screenshots**
Okay it won't let me paste these in even though that's what it says to do and it's like 1am so just visit the link and look at the video titles in the table of contents.

https://acceleratenetworks.com/Phones/T54W#setup

**Desktop (please complete the following information):**
 Windows 10, Firefox 87

**Smartphone (please complete the following information):**

**Additional context**

**Comment by danry25** [comment]
@Chattaeus Would you feel comfortable editing this yourself, then make a pull request to merge it back into the master branch?

[Here is where](https://github.com/AccelerateNetworks/NumberSearch/tree/master/NumberSearch.Mvc/Views/Phones) those 4 phone files are at, just press the pencil in the upper right corner, make your changes, choose " Create a new branch for this commit and start a pull request." and say something like "Fixing issue #183 by adding new videos" then press Commit Changes.

If you need any help, ping me and I can walk you through it! (Ideally before you commit your changes :P)

**Comment by uncheckederror** [comment]
@Chattaeus did you intend to remove the T54W card and link from the Support page?

**Comment by danry25** [comment]
@uncheckederror 95% sure he didn't mean to remove the T54W card and link from the Support page, I don't see any commit from @Chattaeus doing that.

The point of this issue is to update some of the existing videos used in the T54W card and add a few other cards for other models of phones.

**Comment by uncheckederror** [comment]
Interesting, when I run the branch he made, that card is removed.

**Comment by uncheckederror** [comment]
Okay all of the changes are live. Enjoy! 😋 @Chattaeus @danry25
