### ISSUE TITLE
Suggest and validate addresses

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#184]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Customers are currently submitting invalid and poorly formatted addresses through our website, preventing us from easily registering them for 911 service and shipping/delivery. Validating addresses will lower our ongoing support cost.

**Describe the solution you'd like**
We should validate the address using the [USPS Address Information API](https://www.usps.com/business/web-tools-apis/address-information-api.pdf), and implement typeahead/autocomplete suggestions using [Mapbox Search](https://www.mapbox.com/mapbox-search), [Smartystreets US Autocomplete](https://www.smartystreets.com/products/apis/us-autocomplete-pro-api#demo) or similar partial address suggestion API

**Comment by uncheckederror** [comment]
I have reviewed these API and the UPS and USPS API's and I believe that we should go with another alternative API from ESRI that responds to public requests and is designed for autocomplete: https://developers.arcgis.com/rest/geocode/api-reference/geocoding-suggest.htm

Here is a sample query that returns JSON:

https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/suggest?text=4415 31st Ave W&maxSuggestions=5&countryCode=USA&f=pjson

**Comment by uncheckederror** [comment]
@danry25 Autocomplete has been implemented for the "Address" field.

![image](https://user-images.githubusercontent.com/11726956/119743607-1a655e00-be3f-11eb-9fd3-9c864b2e2c26.png)

**Comment by uncheckederror** [comment]
@danry25 has suggested that we convert the address fields from being multiple boxes to being a single omni box and then breaking up the address once it's been submitted through the form.

**Comment by danry25** [comment]
I would like us to accept only validated address in the omnibox, and rename Address 2 to be Unit (optional) with a dropdown of the following choices followed by a freeform text box for a unit # or letter.

Unit Types:
Apartment
Basement
Building
Department
Floor
Front
Hanger
Lobby
Lot
Lower
Office
Penthouse
Pier
Rear
Room
Side
Space
Suite
Trailer
Unit
Upper

This corresponds to the [Unit type and number for E911 addresses for Teleapi](https://apidocs.teleapi.net/api/911-emergency/create-911-record).

**Comment by uncheckederror** [comment]
@danry25 like this?

![image](https://user-images.githubusercontent.com/11726956/119930707-ca68c300-bf34-11eb-9f2a-953a1a5e4852.png)

**Comment by uncheckederror** [comment]
More work on refining this page:
![localhost_44316_Cart_Checkout](https://user-images.githubusercontent.com/11726956/119935033-abb9fa80-bf3b-11eb-9e98-b9fcd811f2b5.png)

**Comment by uncheckederror** [comment]
The revised checkout page is now live.

**Comment by uncheckederror** [comment]
@danry25 are we good on this now?

**Comment by danry25** [comment]
Looks good to me @uncheckederror !
