### ISSUE TITLE
Add Google Reviews to the Landing Page

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#185]
Adding google reviews to our landing page will gives users confidence in our services and highlight our successful prior work.

**Comment by uncheckederror** [comment]
@danry25 please select 3 google reviews of the business that you would like to see on the home page and paste the text here.

**Comment by uncheckederror** [comment]
This change is in:

![image](https://user-images.githubusercontent.com/11726956/119741405-7e395800-be3a-11eb-94fc-c63524370813.png)

@danry25 please verify that this is fix and close the issue.

**Comment by danry25** [comment]
@andrewstiefel @scottstrong206 Please review the change and close the issue if resolved. We also need to create issues for the other changes @andrewstiefel has suggested.

**Comment by andrewstiefel** [comment]
Looks great, thank you!
