### ISSUE TITLE
Address Validation Failing in Ops

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#187]
**Describe the bug**
Trying to update an order in Ops shows "Please match requested format." warning below Address field unless full address (eg: 2318 E Cherry St, Seattle, WA, 98122, USA rather than the prefilled building number and suite) is entered into the Address field in the Ops app.

**To Reproduce**
1. Go to an incomplete order on https://ops.acceleratenetworks.com
2. Click on Update
3. See error

**Expected behavior**
Pressing update should update the order without complaining that the address we verified at time of order submission does not match the requested format.

**Desktop:**
 - OS: Debian 10.9
 - Browser: Firefox
 - Version: 78.10.0esr (64-bit)

**Additional context**
This issue appears to have been triggered by issue #184 , perhaps we get rid of the city, state and zip in the Ops app too and bring over the validation/prefill to the Ops app?

**Comment by danry25** [comment]
To recap the conversation between @uncheckederror and myself, the address field in the Ops app should become an omnibox for all address components excluding the unit type and number, and we will enforce that the address field contains five commas and is found in Esri's API for valid addresses.

Additionally, when someone clicks into an address field that has more than a few characters in it we will query the Esri Address API (rather than waiting for a character to be entered).

**Comment by uncheckederror** [comment]
@danry25 can you verify that you're good with the current state of the address box in the Ops app?
