### ISSUE TITLE
Syncing with InvoiceNinja, Discounts & Refurb Hardware

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#188]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Currently our sales team is creating orders on the website then modifying the hardware invoice in the billing system (eg: $20 off per phone, or refurb phone discount), causing the order copy shown on acceleratenetworks.com to be inaccurate, which makes some of our team and a subset of customers nervous and in need of reassurance (eating into support time).

**Additional context**
Not sure what the best architectural way to solve this is, but tactics we have discussed include:
- Pulling the invoice data from the invoices on page load for each order
- Adding a code or button to make the item cost and description in the cart editable

**Comment by uncheckederror** [comment]
I think in the end we'll need to sync data from the billing system back into the Mvc app. But it will be limited to what data we can query out of InvoiceNinja for the invoice related to the order in question. I will have to research this topic more.

**Comment by danry25** [comment]
Regenerating invoices appears to work well!

All that is left for this issue is handling discount cases like refurbished hardware.

**Comment by uncheckederror** [comment]
Great, how would you like to handle discounts? We could have a discount coupon with a configurable dollar value.

**Comment by danry25** [comment]
Sure, a whitelisted discount coupon would be fine

**Comment by danry25** [comment]
Discounts appear to work, though there appears to be no validation logic to prevent invoices from going negative or preventing irrelevant discounts from being applied:

![image](https://user-images.githubusercontent.com/1683673/146659903-10f1c662-aff6-4c7a-8165-19bc8821110c.png)

Could we scope a discount to a certain SKU to ensure the discount never exceeds the sum of that SKU's price? For example
Waive Installation should only apply if an Onsite Installation is chosen.

**Comment by uncheckederror** [comment]
What you are asking for can be done, but its a completely different model and system than what you requested for this feature. In fact it's what we started with before I did this work.

If you want a specific coupon to perform a scoped function you can file a new GitHub issue and I build that single coupon and its business rules + validation logic. In the meantime, I am removing this custom coupons feature.

**Comment by uncheckederror** [comment]
I have added validation rules so that you cannot use the porting coupon unless there are ported numbers in your cart. The onsite hardware installation coupon also cannot be added to your cart unless you've got some hardware in it.
