### ISSUE TITLE
E911 Connectivity Fee not charged

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#189]
**Describe the bug**
We aren't charging e911 connectivity fee automatically for each line or seat.

**To Reproduce**
1. Go to Acceleratenetworks.com
2. Click on Add services and check out
3. See no e911 fee on billing system

**Expected behavior**
An e911 fee is $2.71, should be billed for each line or seat.

**Comment by uncheckederror** [comment]
@scottstrong206 @danry25 I'm thinking that this fee shows as a separate line item on the checkout page? Or should we just add it to the base cost of a line/seat?

Do you want the ability to remove this fee from an order? Like a checkbox that says "Skip E911 registration".

**Comment by uncheckederror** [comment]
This will be a separate billing item that only shows up when you go to the checkout page.

**Comment by uncheckederror** [comment]
@danry25 @scottstrong206 this feature is now live. Here's an example order with it: https://acceleratenetworks.com/cart/order/0b064c56-5400-460e-b8b6-53f1369e20ce
