### ISSUE TITLE
Add Quentin sales drop down

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#190]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This will help connect customers to Quentin as they order.

**Describe the solution you'd like**
Add Quentin to the sales drop down
Quentin@acceleratenetworks.com

**Comment by uncheckederror** [comment]
Okay, Quentin is now on the list of selectable Sale Reps on the checkout page:

![image](https://user-images.githubusercontent.com/11726956/121981714-07112880-cd43-11eb-92b4-626db2b959ab.png)

**Comment by uncheckederror** [comment]
@scottstrong206 do we need to get Quentin's headshot on the about us page too? https://acceleratenetworks.com/Home/About

**Comment by danry25** [comment]
@uncheckederror We do need to do headshots for both @scottstrong206 and Quentin, would you be willing to do some headshots with these two? We really like how your other headshots came out.

@scottstrong206  was also wondering if there could be a way to link to a particular card [on the About page](https://acceleratenetworks.com/Home/About), as that way we could put a QR code on business cards and other paper media to take people to the relevant profile.

**Comment by uncheckederror** [comment]
@danry25 sure we can do headshots. 

@scottstrong206 yeah, I've added little id tags to the page to support linking ( ex. Scott is https://acceleratenetworks.com/About#scott )

**Comment by scottstrong206** [comment]
@uncheckederror I'll check with Quentin to see his schedule. Maybe we can meet on Saturday or Sunday?

**Comment by uncheckederror** [comment]
@scottstrong206 yeah, this weekend works good.
