### ISSUE TITLE
Respect Quote Checkbox in Ops

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#191]
**Describe the bug**
Currently when the quote checkbox is selected, our team is presented with an order that needs to be worked (porting information gathered, hardware shipped out, or port request submitted) in the Ops app.

**To Reproduce**
1. Go to the Ops page
2. Click on Orders
3. See many "orders" that are actually quotes for new potential clients

**Expected behavior**
Add a new tab for Quotes perhaps? Change their status to pending quote approval, and only move to Orders when the client approves the quote in InvoiceNinja.

**Comment by uncheckederror** [comment]
In order to check if a quote has been converted into an order in the billing system we'll need to poll the billing system to get the status of the quotes related to each order on a regular basis.

**Comment by danry25** [comment]
@uncheckederror To check on a quote and see if it has been converted to an invoice, run it through the invoices endpoint and look for "quote_invoice_id" which will be zero if the quote is not approved, or it will be set to the new invoice ID (a higher number than the quote #) if the quote has been approved.

```
curl -X GET --header "Accept: application/json" "https://billing.acceleratenetworks.com/api/v1/invoices/3934" -H "X-Ninja-Token: YOUR_TOKEN_HERE"
``

It looks like we can also do a put to update existing invoices if we need to alter them [per the Swagger docs](https://web.archive.org/web/20160324124553/https://app.invoiceninja.com/api-docs#!/invoice/put_invoices).

**Comment by uncheckederror** [comment]
@danry25 How often would we want to check on the status of invoices to see if they've been approved in the billing system? Once per day like the owned numbers or once every 15 minutes like the priority numbers?

**Comment by danry25** [comment]
Lets do it once every 15 minutes, our sales team likes to alter invoices as the clients change their orders to fit their actual business needs.

**Comment by uncheckederror** [comment]
@danry25 this change is live.
