### ISSUE TITLE
Button Labels Show Quotes as Invoices

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#192]
**Describe the bug**
When the Quote box is checked on our website, a quote is generated as part of the order, but the text of the link to the quote in the Ops app references these as an Upfront Invoice or Recurring Invoice rather than as a quote.

Additionally the status of a quote isn't "Pending quote approval", but rather another status like "⭕ Ship the hardware to the customer for self-install" which is misleading for our support team and could cause us to ship out hardware by accident.

**To Reproduce**
1. Go to ops.acceleratenetworks.com
2. Click on Orders
3. See mislabeled quotes

**Expected behavior**
Update the word invoice to be quote for each link in the Ops app on a order that is just generating quotes for a new potential client.

Additionally, set the order status to "Pending Quote Approval"

**Comment by uncheckederror** [comment]
@danry25 this change is live. Please close this issue if you approve.

**Comment by danry25** [comment]
![Screenshot from 2021-06-24 16-11-25](https://user-images.githubusercontent.com/1683673/123343607-f14ff000-d506-11eb-9e3c-2131540d5bcb.png)
Looks good to me @uncheckederror!
