### ISSUE TITLE
Set E911 address for main number

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#194]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Currently our support team sets the E911 address for the main phone number by hand. Automating this process will simplify our support workflow.

**Is your feature request related to a problem? Please describe.**
Occasionally this process is not fully adhered to, causing data entry errors that result in costly non-compliance fees.

**Describe the solution you'd like**
Take the main phone number as designated by the business and register it for E911 service using this API endpoint and the address submitted in the order. 

Set E911 address for a phone number: https://apidocs.teleapi.net/api/911-emergency/create-911-record
Board a phone number if its not already in Teli's system: https://apidocs.teleapi.net/api/offnet-provisioning/submit-number

**Comment by uncheckederror** [comment]
@danry25 how do we tell what the main phone number is for a business?

**Comment by danry25** [comment]
In the interim (before we have clients using the new client form), can we have a button and dropdown list of phone numbers on each order that will register the address and phone number selected from the order for E911 service?

The person handling the order would select which number will be registered for E911 service, then press the Register for E911 button, at which point we will register the phone number for E911 service with Teli.

**Comment by uncheckederror** [comment]
@danry25 what endpoint should we use in the Teli API to submit the E911 registration?

**Comment by danry25** [comment]
First we need to check if the phone number is on the Teli platform as a [local number](https://apidocs.teleapi.net/api/my-phone-numbers/list-all) or [offnet number](https://apidocs.teleapi.net/api/offnet-provisioning/list-offnet-numbers), if not register the phone number as an [offnet number on Teli](https://apidocs.teleapi.net/api/offnet-provisioning/submit-number), then [create the E911 record](https://apidocs.teleapi.net/api/911-emergency/create-911-record) once the number shows up in Local or Offnet numbers.

**Comment by uncheckederror** [comment]
@danry25 okay, a functional implementation of e911 registration is live in the Ops app and I have successfully completed a test of it. You will need to test it further to ensure that it is robust.

**Comment by danry25** [comment]
E911 registration works now! It would be easier to use if the dropdown menu of numbers could be searchable, and you didn't need to save the change to the form prior to submitting the E911 address in Ops.

**Comment by uncheckederror** [comment]
> E911 registration works now! It would be easier to use if the dropdown menu of numbers could be searchable, and you didn't need to save the change to the form prior to submitting the E911 address in Ops.

Both of these changes are now live.

**Comment by danry25** [comment]
This appears to work well, thanks @uncheckederror!
