### ISSUE TITLE
Add Accessories Tab to Hardware Page

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#198]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**

We can offer spare GRP or GXP deskphone handsets, batteries, belt clips and rear covers for our cordless handsets and other parts without having these be one off support requests requiring more manual labor.

**Is your feature request related to a problem? Please describe.**
Customers break, wear through or lose parts of their phones and need replacement parts. We often don't bill for this, but we should.

**Describe the solution you'd like**
Add a tab for Accessories to the hardware page?

**Comment by uncheckederror** [comment]
@danry25 please close if we're good.

**Comment by danry25** [comment]
How do I mark an item as an accessory?

Additionally, can you add the following images:
https://www.teledynamics.com/#/productdetails/GS-GXP-HAND21xx
https://www.teledynamics.com/#/productdetails/GS-GRP-HAND26xx
https://www.teledynamics.com/#/productdetails/YEA-HNDST-T46
https://www.teledynamics.com/#/productdetails/YEA-HNDST-T53-T54
https://www.teledynamics.com/#/productdetails/YEA-STAND-T54
https://www.teledynamics.com/#/productdetails/YEA-STAND-T46
https://www.teledynamics.com/#/productdetails/YEA-DD10K
https://www.teledynamics.com/#/productdetails/YEA-STAND-T54W
https://www.teledynamics.com/#/productdetails/YEA-HC-T46
https://www.teledynamics.com/#/productdetails/YEA-BT50
https://www.teledynamics.com/#/productdetails/YEA-WF50
https://www.teledynamics.com/#/productdetails/YEA-WMB-T5W
https://www.teledynamics.com/#/productdetails/GS-GRP-WM-A (use image for GS-GRP-WM-S and GS-GRP-WM-L as we do not sell the GRP2601 or similar).

I also need to get a better picture for this: https://www.pcliquidations.com/p26609-grandstream-gxp2130-wall-mount

**Comment by uncheckederror** [comment]
@danry25 You need to select the "Accessory" option in for the "Type" field on that item's page in the Ops app. It defaults to "Phone".

**Comment by danry25** [comment]
Hmm, maybe I am looking right past the accessory field? Here is a screengrab:

![image](https://user-images.githubusercontent.com/1683673/124666127-6b1a9e80-de62-11eb-9c3a-4053501f7734.png)

**Comment by uncheckederror** [comment]
@danry25 try it now. I have deployed a new build of the Ops app.

**Comment by uncheckederror** [comment]
@danry25 these two don't actually have pictures.

https://www.teledynamics.com/#/productdetails/YEA-STAND-T54W
https://www.teledynamics.com/#/productdetails/YEA-HC-T46

**Comment by uncheckederror** [comment]
@danry25 bump

**Comment by danry25** [comment]
@uncheckederror I don't have good images for either of these Yealink accessories, let me corral those.

Can we also add these accessories?
http://www.grandstream.com/products/ip-voice-telephony/extension-modules/product/gbx20-extension-module
https://www.teledynamics.com/#/productdetails/YEA-EXP50

**Comment by uncheckederror** [comment]
> @uncheckederror I don't have good images for either of these Yealink accessories, let me corral those.
> 
> Can we also add these accessories?
> http://www.grandstream.com/products/ip-voice-telephony/extension-modules/product/gbx20-extension-module
> https://www.teledynamics.com/#/productdetails/YEA-EXP50
I have added these images.

**Comment by uncheckederror** [comment]
@danry25 please create entries in the hardware system for these phones: 
https://www.teledynamics.com/#/productdetails/YEA-STAND-T54
https://www.teledynamics.com/#/productdetails/YEA-STAND-T46
https://www.teledynamics.com/#/productdetails/YEA-DD10K
https://www.teledynamics.com/#/productdetails/YEA-STAND-T54W
https://www.teledynamics.com/#/productdetails/YEA-HC-T46
https://www.teledynamics.com/#/productdetails/YEA-BT50
https://www.teledynamics.com/#/productdetails/YEA-WF50
https://www.teledynamics.com/#/productdetails/YEA-WMB-T5W
https://www.teledynamics.com/#/productdetails/GS-GRP-WM-A

**Comment by uncheckederror** [comment]
@danry25 All of these are live now.

**Comment by danry25** [comment]
Perfect, I have reviewed these changes and ensured they are what I expected. Thanks for your hard work @uncheckederror!
