### ISSUE TITLE
Add new hardware

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#199]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**

This will reduce the effort our sales team has to out into building new quotes.

**Is your feature request related to a problem? Please describe.**
DP730 Handsets, Yealink DECT handsets, the DP750 and DP752 base stations all need to be added to the website.

**Describe the solution you'd like**
I need to add them to the website and make a pull request with the new images

**Comment by uncheckederror** [comment]
I will images with transparent background for these phones: DP730 Handsets, Yealink DECT handsets, the DP750 and DP752 base stations.

Then you can use this page to create new entries for these additional hardware items: https://ops.acceleratenetworks.com/Home/Product

**Comment by danry25** [comment]
DP730:
https://helpdesk.grandstream.com/system/upload_files/data/000/002/145/original/DP730.png
https://helpdesk.grandstream.com/system/upload_files/data/000/002/142/original/DP730-1.png
https://helpdesk.grandstream.com/system/upload_files/data/000/002/143/original/DP730-2.png

DP750:
https://helpdesk.grandstream.com/system/upload_files/data/000/000/002/original/DP750.png
https://helpdesk.grandstream.com/system/upload_files/data/000/000/326/original/DP750.png
https://helpdesk.grandstream.com/system/upload_files/data/000/000/327/original/DP750_720_combination_3.png
https://helpdesk.grandstream.com/system/upload_files/data/000/000/325/original/DP750_front.png

DP752:
https://helpdesk.grandstream.com/system/upload_files/data/000/002/146/original/DP752-1.png
https://helpdesk.grandstream.com/system/upload_files/data/000/002/147/original/DP752-2.png
https://helpdesk.grandstream.com/system/upload_files/data/000/002/148/original/DP752-3.png

I will work on the Yealink DECT handset pictures.

**Comment by danry25** [comment]
Can we add https://www.teledynamics.com/#/productdetails/GS-GRP2624 as well?

**Comment by uncheckederror** [comment]
@danry25 all of these are live on the website now except the Yealink DECT handset sets. Can you be specific about which SKUs you want? https://www.teledynamics.com/#/catalog/keyword/Yealink%20DECT%20Conference%20Phone

**Comment by danry25** [comment]
Closing as we have resolved all but Yealink DECT Pictures (pending Yealink's help in getting these).
