### ISSUE TITLE
Provide phone images for homepage that have transparent backgrounds

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#200]
**Describe the bug**
One of the images (The Yealink T54W one) has a non-transparent background, blocking changing the background color on the homepage

**To Reproduce**
1. Go to AccelerateNetworks.com
2. Open Dev Tools and change the background color
3. See the white background of the Yealink T54W

**Expected behavior**
The background should be transparent.

**Comment by uncheckederror** [comment]
@danry25 can you provide a link to an image of the Yealink T54W with a transparent background?
