### ISSUE TITLE
Change Language on Website for Installation Fee

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#207]
**Describe the bug**
On the website it shows installation as a $98/hr fee AFTER a $60 call out. It should have language indicating that it costs $60 for the call out PLUS $98/hr
**To Reproduce**
1. Go to our website
2. Start a new order

**Expected behavior**
Should reflect cost of $60 call out charge plus $98/hr

**Comment by uncheckederror** [comment]
@Chattaeus @scottstrong206 @danry25 how about this?

"Onsite installation is available in the Greater Seattle Area for a $60 call out charge. Time spent onsite is billed at $100 per hour."

**Comment by uncheckederror** [comment]
@Chattaeus plz respondio 🙏

**Comment by Chattaeus** [comment]
Oh sh!t my bad, that language is good. Might have to run the price hike by @danry25, but I'm okay with it.

**Comment by uncheckederror** [comment]
@Chattaeus big thank!

**Comment by Chattaeus** [comment]
@uncheckederror No Problem

**Comment by danry25** [comment]
I approve @uncheckederror and @Chattaeus, our minimum billed should be $160 for a callout. $60 fee plus $100 an hour.
