### ISSUE TITLE
Add links to login page in Ops

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#208]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This will reduce labor costs by providing an organized page of links to our other internal tooling.

**Is your feature request related to a problem? Please describe.**
We have many internal applications that our team needs to use. By providing links on the login page to Ops, we create a single reference page that will take them to where they need to be.

**Describe the solution you'd like**
Please add links to:
invoiceNinja - https://billing.acceleratenetworks.com
Lookup a phone number -https://acceleratenetworks.com/Lookup
FusionPBX - https://acceleratenetworks.sip.callpipe.com
Teli - https://accelerate.voicecontrols.net/login
Erxes - https://acceleratenetworks.app.erxes.io
Webmail - https://mail.seattlemesh.net
Nextcloud - https://cloud.aidanis.online/login

**Comment by uncheckederror** [comment]
![localhost_44327_Identity_Account_Login_ReturnUrl=%2F(iPad Pro)](https://user-images.githubusercontent.com/11726956/126059408-8684f7de-aeaf-40fa-8ada-8e3cbce687ce.png)

**Comment by uncheckederror** [comment]
A bit more refinement: 
![image](https://user-images.githubusercontent.com/11726956/126081782-8f63b908-70c1-42cf-a4a4-db45bf8f34b2.png)

**Comment by danry25** [comment]
I think this resolves this issue @uncheckederror, thanks for your diligent work on this!
