### ISSUE TITLE
Change bio and phone number on about us page

### ISSUE THREAD

**Issue by qscherger** [AccelerateNetworks/NumberSearch#209]
BIO: With his background in business development Quentin has a keen ability to pinpoint issues in productivity and budgeting.
Phone: Change to 206 237 2202

**Comment by qscherger** [comment]
Also if we could change my title to Sales Representative instead of Customer Evangelist that'd be great!

**Comment by uncheckederror** [comment]
@qscherger here your raw photo: https://github.com/AccelerateNetworks/NumberSearch/blob/master/NumberSearch.Mvc/wwwroot/images/scaled/IMG_1505-2.jpg

**Comment by uncheckederror** [comment]
@qscherger these changes are now live on our website: https://acceleratenetworks.com/About
