### ISSUE TITLE
Public website updates

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#211]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
The punch list of changes below will improve the customer experience when using our website, improving our ability to bring in new customers by making the site more visually appealing. This is accomplished by hiding visual clutter and adding significant additional content.

**Describe the solution you'd like**
### Home Page
- [x] Get back to business section (copy four boxes, put Start Now to the right and drop upper two lines of text, move to directly below video)
- [x] Improve Find the perfect phone number box (grey across whole screen width, left align text and add green check marks next to text)
- [x] Bigger round on box corners
- [x] Make Read Reviews button on Google bigger
- [x] Uplift Easily manage your business communications (from Andrew template), add it below Read Reviews on Google
- [x] Add call to action to bottom of page (TBD, talk about after rest of changes complete)
Notes: Static image of person/start now is much less interactive than video, keep video

### Title Bar
- [x] Hide cart on homepage when no products in cart
- [x] Add sales # to upper right corner of every page, bump to the right when someone adds product to cart
- [x] Combine Support and About under Resources
Notes: Decided not to dropdownify Services/Hardware/Numbers due to workflow breakage

### About us
- [x] Make Our Mission big and wide, copy Andrew Stiefel text edits
- [x] Grey background on We Proudly participate in

### Services
- [x] Tabify additional services (Split Lines/Seats from Additional Services)
- [x] Uplift Simple, fair pricing flavor text

### Footer
- [x] Copy wholesale, with nav links to other pages and social links (Github, Twitter, etc)

**Comment by danry25** [comment]
Update flavor text to Lookup page:

- Enter a multiple phone numbers and we'll hunt down any information we can find for each number and check if we can port the number to our network.
- We check to see who the underlying telecom provider is and when the phone number was last transferred between telecom providers.
- Find out how your caller ID displays on other people's phones!

**Comment by uncheckederror** [comment]
Tried to address the "phones on a blue ocean" feedback by grouping them together on a light grey background.

![localhost_44316_ (2)](https://user-images.githubusercontent.com/11726956/127812272-90c3954a-9913-4e71-ac31-52711c87b5d7.png)

**Comment by danry25** [comment]
@uncheckederror Here is the EnviroStars logo: https://envirostars.org/wp-content/uploads/2020/12/EnviroStars2020-e1608007992822.png

**Comment by uncheckederror** [comment]
Condensing the outstanding items here:

Axe in video: 
- [ ] Shot in the car, fist bump, Kyle hand action

Home Page:
- [ ] Put Grandstream Phone in center between Yealinks

**Comment by danry25** [comment]
For the homepage pictures please use the two images below:

https://helpdesk.grandstream.com/system/upload_files/data/000/002/722/original/GRP2615-front.png
![Yealink T57W](https://user-images.githubusercontent.com/1683673/144779774-9afcfa0f-c95d-40db-bf5d-50edfec23c71.jpg)

**Comment by uncheckederror** [comment]
These images are now live on the website.

In response to requests by @danry25 and @Chattaeus you can now link directly to an item on the Hardware page by using its name. For example: https://acceleratenetworks.com/Hardware/GRP2615 or https://acceleratenetworks.com/Hardware/Wall-Mount%20for%20Grandstream%20GXP%20Phones

**Comment by danry25** [comment]
@uncheckederror Can we update the video to https://ttm.sh/eat.m4v (kindly edited by Vanta Black ([portfolio](https://verticallyalignedcarbonnano.tube))) and then close this issue?

**Comment by uncheckederror** [comment]
@danry25 the new video is live.
