### ISSUE TITLE
User Roles in Ops

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#212]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Salespeople currently see way too much complexity in the Ops App. Reducing the amount of duplicate options will make their jobs easier, improving the amount of time they can focus on selling rather than spending time in our backend processes.

**Describe the solution you'd like**
Add 2 user roles, Support and Sales. Support has access to all menu options in Ops app, while Sales has the Phone Numbers & Tools menus hidden and the Tax Rates/Sent emails submenus hidden as well.

Sales users should also only be shown orders or quotes they were selected as the agent on.

**Comment by uncheckederror** [comment]
This feature is now live.

![image](https://user-images.githubusercontent.com/11726956/128658955-95a58420-ff82-4447-bb97-5455a5ed41bf.png)

@danry25 please try it out.

**Comment by danry25** [comment]
I really like the work you did @uncheckederror! The users roles are well scoped and you made some nice navigation improvements
