### ISSUE TITLE
Rename job title

### ISSUE THREAD

**Issue by lookwhatitdid** [AccelerateNetworks/NumberSearch#213]
Could we change my title on the website from Sales Rep to Sales Manager? We decided to make that change in my title when we brought fischer and erik aboard and that is what is reflected on my business card. Thanks!
-Quentin

**Comment by uncheckederror** [comment]
Yep, will do!

**Comment by uncheckederror** [comment]
@lookwhatitdid your new title is live on the website, Mr. Sales Manager. 🐱‍🏍

https://acceleratenetworks.com/About
