### ISSUE TITLE
Lookup/Port page - Add all numbers to cart

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#219]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Customers and our team members would like to be able to add all numbers queried to their cart by pressing a single button, rather than clicking an add to cart button adjacent to each phone number.

**Is your feature request related to a problem? Please describe.**
It is quite repetitive to press the add to cart button for each number when doing large port requests. This can cause avoidable repetitive stress injuries when.

**Describe the solution you'd like**
Place an Add All to Cart button on the page, when pressed this button should add all phone numbers to the cart.

**Comment by uncheckederror** [comment]
@danry25 if you're pleased with how all the numbers are now added to the cart automatically then can we close this issue?

**Comment by danry25** [comment]
This seems to work well now!
