### ISSUE TITLE
Lookup/Port page - Highlight mismatched carriers

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#221]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This reduces errors when porting in phone numbers by highlighting phone numbers that are perhaps incorrectly being ported.

**Is your feature request related to a problem? Please describe.**
Scenario: You go to port 50 numbers from Comcast, but a dozen of these numbers are actually with T-Mobile, flagging these numbers from T-Mobile would encourage the website user to clean up these numbers that were erroneously included.

**Describe the solution you'd like**
Show a Bootstrap red warning modal at the top of the page when the Carrier strings do not match across all queried numbers, and change the text color to red for the minority non-matching numbers (eg: if 20% of the numbers do not have the same carrier, change these ones to have a red text color)

**Describe alternatives you've considered**
Sharp eyed humans have been considered, but occasionally these are flakey and giving them assistance should help them perform better :D

**Comment by TakoyakiAllenC** [comment]
I would recommend just color coding carriers rather than highlighting red. T-mobile could be pink. Comcast blue. Verizon red. Att purple. Etc. You don't need to assign a carrier to color mapping but have at least 15 distinct colors to cover worst case scenario of 15 different providers (god forbid you have 16)

**Comment by danry25** [comment]
@TakoyakiAllenC Color coding by carrier is possible, but it can be a bit troublesome to sort which OCN (operating carrier number) should have which color applied for carriers that are amalgamations of many carriers (eg: Verizon Wireless has many OCNs from the various regional and local carriers they acquired, same for AT&T, Frontier, Centurylink, etc).

@uncheckederror If I provide a spreadsheet of the hex codes and the OCNs ([which we get here](https://github.com/AccelerateNetworks/NumberSearch/blob/db29e6ee664f51152e4d88db654744b6d838cba0/NumberSearch.DataAccess/BulkVS/LrnBulkCnam.cs#L12) as part of the LRN query), would you be willing to color code these?

**Comment by uncheckederror** [comment]
@danry25 yes, I can look into doing that.

**Comment by danry25** [comment]
@uncheckederror Please email me an export of all queried numbers so I can classify them with colors and carrier names. Thank you!

**Comment by danry25** [comment]
@uncheckederror I emailed you back a list of 25 carriers, I recommend matching the carrier logo and color based on the OCN returned by the lookup.

**Comment by uncheckederror** [comment]
@danry25 could you triage the Lookups page and create the required carriers? https://ops.acceleratenetworks.com/Lookups

**Comment by danry25** [comment]
@uncheckederror Will do! I like the 50% transparency change you made by the way!

**Comment by danry25** [comment]
@uncheckederror Good work! I think there are some related issues like #244 and #245 but I have split these off.

@TakoyakiAllenC Mind submitting a variety of phone numbers from carriers we have yet to see? Then we can classify these carrier's Operating Carrier Numbers (OCNs) and they will have a pretty logo and color associated :D
