### ISSUE TITLE
Call48 Ingest is impaired

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#228]
**Describe the bug**
We are ingesting only 14678 numbers from Call48, whereas in the past we could ingest millions of phone numbers.

**To Reproduce**
1. Go to https://acceleratenetworks.com/ingest
2. Scroll down to the Provider section below Prority Area Codes

**Expected behavior**
Call48 should show at least a few hundred thousand numbers being ingested. Additionally Prority is misspelled on the Ingest webpage.

**Additional context**
Call48 changed the names of the fields in their API response and broke our ingests recently, and has not documented their new response format.

**Comment by uncheckederror** [comment]
No matter what value we set for the "limit" parameter we get 50 maximum back. A few weeks ago when we originally implemented this API integration we got up to 5000 results back.

**Comment by uncheckederror** [comment]
@danry25 the ingest appears to be working. But we are not capturing as many numbers as before they updated their API.
