### ISSUE TITLE
Poor support for PO boxes

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#230]
**Describe the bug**
Typeahead does not play nice with PO Boxes, and it is unclear to the user what format we expect these addresses in.

**To Reproduce**
1. Go to AccelerateNetworks.com
2. Check out a cart full of products using a PO Box
3. See how no suggestions are made and no typeahead is provided.

**Expected behavior**
Perhaps show a help text when we can't provide a typeahead, eg: Format the address this way for PO Boxes and this way for Canadian Addresses?

**Comment by uncheckederror** [comment]
Can you give an example of an address with a PO Box?

**Comment by danry25** [comment]
Hi Tom,

PO Box 130, Maple Falls, WA, 98266, USA would be an example.

**Comment by uncheckederror** [comment]
Per this test order the current form allows the submission of PO Box address even if they can't be found by the type-ahead API.

https://ops.acceleratenetworks.com/Home/Order/efcd6cbf-a0fd-471b-9df6-3c0b2ea83957

@danry25 Is this the behavior what you are looking for?

**Comment by danry25** [comment]
Yes, this behavior is acceptable.
