### ISSUE TITLE
Canadian Addresses break Port Request form

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#231]
**Describe the bug**
Entering a Canadian Address at checkout seems to break the porting form. The order loses track of the $20 porting charge and the customer cannot submit the port request form with the account number and bill attachment.

**To Reproduce**
1. Go to AccelerateNetworks.com
2. Add a number to cart to port from another vendor
3. Checkout with an address like 43 Puckett Road, Cheryville, BC, V0E 2G3 then complete the Port Request form
4. See error when clicking on Customers View of the order from the Ops app. Note how the order is for $0 and you cannot navigate to the Port Request form.

**Expected behavior**
The order should retain the associated products and provide a link to the Port Request form for the customer to fill out.

**Comment by uncheckederror** [comment]
Right now address results are limited to just address inside the USA. Should we change this to allow non-USA addresses?

**Comment by danry25** [comment]
I was thinking we could just show a help text when the address recommendation API returns no results?

**Comment by uncheckederror** [comment]
The API will never return no results. It return results based on similarity, even if the similarity level is low. This change was made based on feedback from prior version of this address entry box.

**Comment by danry25** [comment]
Could we just enable Canadian address recommendation in addition to USA addresses?

**Comment by uncheckederror** [comment]
Canadian addresses will now be recommended by the type ahead API. But the specific address you provided is unknown by the API so it still won't work in the way that you expect.
