### ISSUE TITLE
Ops - Updating order to mark as complete shows error

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#236]
**Describe the bug**
Attempting to mark the order below as completed results in an error (screenshot below).

**To Reproduce**
1. Go to [https://ops.acceleratenetworks.com/Home/Order/4c1aa4c3-7e4b-4799-b43f-63ed870fbbd3](https://ops.acceleratenetworks.com/Home/Order/4c1aa4c3-7e4b-4799-b43f-63ed870fbbd3)
2. Check the "Mark This Order as Completed" box
3. Click on Update at bottom of page

**Expected behavior**
The order should be updated to reflect that it is now complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/1683673/135948221-d4a1288c-90c0-4294-b48e-0abc2687e90a.png)

**Comment by uncheckederror** [comment]
@danry25 thank you for submitting this bug. Please contact @Chattaeus for after hours support and he can walk you through the troubleshooting steps.

**Comment by uncheckederror** [comment]
This was fixed in 3bfa533

**Comment by danry25** [comment]
Thank you for your help @uncheckederror & @Chattaeus, I have verified that this issue is resolved!
