### ISSUE TITLE
Ops - Merge two orders

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#238]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This will simplify the the handling of orders and reduce the complexity of ordering from us for our clients

**Is your feature request related to a problem? Please describe.**
Often clients place more than 1 order in a short period of time.

**Describe the solution you'd like**
Merging two orders together with the push of a button would show clients what they owe us and what they will be receiving in one consolidated place, easing the mental workload on our clients.

**Comment by uncheckederror** [comment]
Links to either of the invoice will go to the new merged invoice. When the merge is executed in the Ops app, a message will appear telling the user to go fix up the invoices associated with the merged order. In the Ops app you can search for an email and be presented with a list of order Id's related to that email then copy paste those id's into a pair of input boxes and hit a merge button to submit them.

**Comment by danry25** [comment]
I tried merging an order for a GRP2615 into a base order that had just a ported phone number, and while the order shows up correctly in the Ops site when looking under Orders, clicking on Customer View or Edit Order in Ops shows just the GRP2615 on the order as an item, not the ported phone number or the waive port fee associated with this order.

To find this order search Mike and see the 9/15/2021 order.
