### ISSUE TITLE
Erxes Integration

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#24]
We use Erxes to handle our clients and leads. Perhaps an integration would be useful, prepopulating a company and customer when an order is submitted. [API Docs](https://docs.erxes.io/developer/graphql-api) & [Erxes API](https://github.com/erxes/erxes-api) are here.

**Comment by uncheckederror** [comment]
Is the idea here to take the info we are currently sending by email and send it via this API instead?

**Comment by danry25** [comment]
Yes, exactly. We could even turn it into a todo item with checkboxes and such.

**Comment by uncheckederror** [comment]
@danry25 Please provide sample requests and responses for this API.

**Comment by danry25** [comment]
@uncheckederror I will reach out to Erxes and request an example of how to do the following via their GraphQL API:
- Create customer
- Create company with customer associated
- Create deal in sales pipeline with the following properties:
   - Attach Customer & Company
   - Create checklist of tasks to be done
   - Attach products & services and their value
   - Tag to specific user (Need to refine this on our side)
   
@Chattaeus @scottstrong206 @kylek206 Can you take a peek at the Example Customer in Erxes under Sales Pipeline => Accelerate Networks => Follow Up perchance? I am thinking a new order gets placed, it creates a card that looks like that and is assigned to the support team, then we triage it.

Initial triage would be:
- Setting reminder date and assigning to installer or salesperson
- Verifying any hardware ordered is getting prepared
- Verifying port request is submitted
- Ensuring the customer has paid for any hardware prior to installation/shipment
- Building out the account in FusionPBX
- Sending welcome email to customer

**Comment by uncheckederror** [comment]
@danry25 what is the current status on getting examples from Erxes?

**Comment by danry25** [comment]
No luck getting working API examples from Erxes thus far.

**Comment by danry25** [comment]
Closing as Won't Fix
