### ISSUE TITLE
Export Metrics

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/NumberSearch#242]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
this feature will provide visibility into the state of the application

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i have to dig through logs to figure out what's going on with the application

**Describe the solution you'd like**
instrument the application to export prometheus-compatible metrics.

**Describe alternatives you've considered**
* reading logs

**Additional context**
https://github.com/prometheus-net/prometheus-net

**Comment by uncheckederror** [comment]
@thefinn93 @danry25 

https://ops.acceleratenetworks.com/metrics

and 

https://acceleratenetworks.com/metrics

Enjoy!

**Comment by thefinn93** [comment]
```
$ curl -i https://ops.acceleratenetworks.com/metrics
HTTP/2 302 
server: nginx/1.14.2
date: Fri, 05 Nov 2021 23:52:38 GMT
content-length: 0
location: http://ops.acceleratenetworks.com/Identity/Account/Login?ReturnUrl=%2Fmetrics
```

can we get this to be either unauthenticated or use some kind of non-browser auth mechanism?

other one looks good

**Comment by uncheckederror** [comment]
`$ curl -i https://ops.acceleratenetworks.com/metrics`

Should work now
