### ISSUE TITLE
Some Jumplinks Broken on Website

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#246]
**Describe the bug**
Some jump links on hardware support pages not working. You click the jump link and it takes you nowhere or just slightly down the page, not to the corresponding video. Known examples include:

2170 Page: Create a Voicemail Greeting?
2135 Page: Create a Voicemail Greeting?
T54W Page: Create a Voicemail Greeting?
2615 Page: Create a Voicemail Greeting?

**To Reproduce**
1. Go to support page for one of phones above
2. Click on the jump link at the top to "Create a Voicemail Greeting?"
3. Scroll down to nowhere. It should auto scroll down to the correct spot but it doesn't.
4. See error. Yes, see error.

**Expected behavior**
When clicking a jump link it should express the page to the corresponding video for my viewing pleasure.

**Screenshots**
If applicable, add screenshots to help explain your problem. Eh, I think you can figure it out without them.

**Desktop (please complete the following information):**
 - OS: Craprosoft Windows 10
 - Browser Firefox
 - Version IDK, like 93 or something? They update this like twice a month, I can't keep up.

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
Not this exact problem but if you're going to be fixing things there shouldn't be a question mark in the jump link title. Maybe that's why it's broken, the website doesn't know if it's going to take you where it should or not. Or maybe it's just a mystery, will this jump link work? No, okay, damn. Seriously, the question mark is on every one of the jump link titles for create a voicemail and those are the only ones that don't work.

**Comment by uncheckederror** [comment]
I Will Fix This Bug? @Chattaeus

**Comment by uncheckederror** [comment]
@Chattaeus A new version of the website is live. Please close this issue once you've verified that it is fixed.
