### ISSUE TITLE
Error shown when submitting port request - Ops

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#249]
**Describe the bug**
An error was shown after pressing the Submit to Teli & BulkVS button for a port request. The request was submitted successfully and Ops has the correct port request number associated with the phone numbers being ported.

Affected order: https://ops.acceleratenetworks.com/Home/PortRequestUnified/981d40d6-773b-4731-ba57-759efb237670

**To Reproduce**
1. Go to ops.acceleratenetworks.com
2. Click on a port request with the details filled out that is unsubmitted 
3. Scroll down to Submit to Teli & BulkVS and press button

**Expected behavior**
A success modal should be shown, since the port was submitted :D

**Screenshots**
![image](https://user-images.githubusercontent.com/1683673/146457625-f972153d-e5f6-4670-954a-1f2a4a067b22.png)

**Comment by uncheckederror** [comment]
@danry25 This bug should be fixed now.
