### ISSUE TITLE
Order DIDs with upstream vendor when user sends us an order

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#25]
We should buy a DID with the upstream vendor when it is ordered through Number Search. Below are the API endpoints and details to do so.

1st Point: Use [SOAP Method DIDOrder](http://soapclient.com/soapclient?template=%2Fclientform.html&fn=soapform&SoapTemplate=%2FSoapResult.html&SoapWSDL=http%3A%2F%2Fapi.1pcom.net%2Fws2%2FDIDManagement.asmx%3Fwsdl&_ArraySize=2) on http://api.1pcom.net/ws2/DIDManagement.asmx
Teli: https://apidocs.teleapi.net/phone-numbers/order-single-number.html
BulkVS : Your gonna need to [explore their API](https://portal.bulkvs.com/assets/images/API-SOAP-HOWTO.pdf), the WSDL file causes soapclient.com to choke :c

**Comment by uncheckederror** [comment]
At this point we are continuing to handle this process manually by sending the order to the Erxes CRM and having a human handle it. When the sale volume of phone numbers increase in the future, we will have to revisit this.

**Comment by danry25** [comment]
This is a very risky strategy, as a good number can be purchased by a competitor between when an order is placed and when we manually process the order.

**Comment by danry25** [comment]
Here is how to order a DID with each vendor:
- [Teli endpoint](https://apidocs.teleapi.net/api/order-phone-numbers/order-single-number), provide token (the API token), number (the DID), call_flow=3110, channel_group=65 and cnam=enabled
- Endstream Endpoint DIDOrder on http://api.1pcom.net/ws2/DIDManagement.asmx to order, then we need to route it to a gateway using DIDRouteVoiceToGatewayBasic (will email Harel to double check)
- BulkVS [DnOrderRequest](https://github.com/AccelerateNetworks/NumberSearch/blob/2ba162392056038b8af91d5530230b86658f16b0/BulkVS/ServiceReference/Reference.cs#L455) endpoint, provide apikey, apisecret, dn (the DID), trunkgroup=SFO, cnamlookup=true, lidb="", messaging=false, portoutpin set to a random int. Double check that cnamlookup, messaging and lidb accept those types of parameters.

**Comment by uncheckederror** [comment]
Implemented the TeleMessage path for automated phone number purchases in 17c92dc.

**Comment by uncheckederror** [comment]
The DIDRouteVoiceToGatewayBasic endpoint requires a "GatewayIP" parameter. @danry25 What value should we use?

**Comment by uncheckederror** [comment]
Implemented the BulkVS path for automated phone number purchases in 88c7b9d.

**Comment by danry25** [comment]
> The DIDRouteVoiceToGatewayBasic endpoint requires a "GatewayIP" parameter. @danry25 What value should we use?

I will send the GatewayIP to you out of band, it should be treated similar to an authentication credential like a username and not be committed to the repository. It can change in the future too!

**Comment by uncheckederror** [comment]
Now that we have validated that setting the Gateway is unnecessary, I have removed that step.

Additionally I have completed my testing of all three purchasing methods and deploy the new build to production.

Please validate that they all work to your satisfaction.

**Comment by danry25** [comment]
BulkVS and Endstream seem to work fine, but buying numbers from Teli appears to not work. Wondering if our import of available numbers is just too old from them, IIRC they have an internal ID assigned to each available number.

Here is what I got when trying to order a Teli number:
![Screenshot from 2020-07-05 21-03-12](https://user-images.githubusercontent.com/1683673/86554901-bde61100-bf03-11ea-8c68-cfd0db89aa13.png)

Below are the numbers Teli shows as available, yet [we have a much broader list](https://acceleratenetworks.com/Search?Query=206*******) of available numbers in the same 206597 NPANXX block:
![Screenshot from 2020-07-05 21-05-25](https://user-images.githubusercontent.com/1683673/86554986-f71e8100-bf03-11ea-8603-19af9d49591a.png)

**Comment by uncheckederror** [comment]
Okay, I've pushed a new build that properly captures the success and failure responses from BulkVS. I've also resolved the bug that was blocking you from purchasing those two numbers from teli, and purchased the first number through the app. Please retest and let me know what you find.

**Comment by uncheckederror** [comment]
@danry25 Please retest all 3 number provider services and verify that the sales are going through on their end.

**Comment by danry25** [comment]
It seems I can't check out a mixed cart reliably, I had to remove 4259063030 since this number was no longer available on BulkVS:

![Screenshot from 2020-07-11 13-03-47](https://user-images.githubusercontent.com/1683673/87232967-05432600-c378-11ea-8d51-d60fbf682798.png)
![Screenshot from 2020-07-11 13-03-30](https://user-images.githubusercontent.com/1683673/87232969-06745300-c378-11ea-8070-a564a229b1e7.png)

**Comment by uncheckederror** [comment]
I have verified that this order went through. 

https://acceleratenetworks.com/cart/order/86960c3a-8823-4adb-94bb-297d0844466d

I am attempting to reproduce this bug.

**Comment by danry25** [comment]
The Local Routing Number is the wrong thing to check to verify whether a number is purchasable through Teli. Use https://apiv1.teleapi.net/dids/list?token=yourtoken&search=yournumber

This endpoint also accepts freeform queries like https://apiv1.teleapi.net/dids/list?token=yourtoken&search=425*******

**Comment by uncheckederror** [comment]
Please retest. @danry25 Per our discussion this has been resolved and a new build has been deployed to production.

**Comment by danry25** [comment]
This issue with verifying numbers are available to purchase through Teli looks to be resolved based on my testing,
