### ISSUE TITLE
Negative Orders on Website (Infinite Money Glitch)

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#250]
**Describe the bug**
On the website it's possible to select a negative quantity of something. It doesn't work to reduce the number in cart. When placing a negative order it shows up as 1 in cart regardless of negative quantity ordered.

**To Reproduce**
1. Go to our website.
2. Click on a product or service.
3. Scroll down. Or just enter "-(quantity)" of item or service.

**Expected behavior**
This should bottom out at 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/73979793/146629964-0dd50999-a180-4a30-b2cf-f3e609ef97b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 93.0

**Smartphone (please complete the following information):**
 - Device: idk, probably all of them
 - OS: does ios4 even work any more?
 - Browser
 - Version

**Additional context**
Still waiting on my refund for the -42069 phones I ordered...

**Comment by uncheckederror** [comment]
@Chattaeus @danry25 this bug is fixed on both the services and the hardware pages.
