### ISSUE TITLE
New Client Form doesn't show phone numbers added without full page reload 

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#251]
**Describe the bug**
Pressing Add under the "What does each of these phone numbers do for your business?" heading adds the number to the form data, but the row containing the phone number is not shown to the user, and duplicate numbers can be added.

**To Reproduce**
1. Go to a new client form
2. Scroll down to "What does each of these phone numbers do for your business?"
3. Fill in Phone Number, Description, and perhaps prefix then press Add
4. See that the number doesn't appear to be added, but if you press F5 or reload the page the number will be added.

**Expected behavior**
When the Add button is pressed, the form should show an updated list of phone numbers.

Duplicate phone numbers should not be accepted when submitted.

**Screenshots**
Before page reload and after pressing add multiple times:
![image](https://user-images.githubusercontent.com/1683673/146659211-0dcf1014-eef1-4c1e-bc38-f322faf09281.png)

After page is reloaded:
![image](https://user-images.githubusercontent.com/1683673/146659221-2c4a4831-a673-410c-ae1a-b3826a757254.png)

**Comment by uncheckederror** [comment]
This was a naming conflict between the HTML table elements when selected from JavaScript.
