### ISSUE TITLE
Port request split incorrectly - Ops

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#254]
**Describe the bug**
When submitting a port request with both a local and toll free number associated, a port request with BulkVS (specifically #1655883) with the local number was created, and a port request with both the local and toll free number was created with Teli (specifically #6109), yet the BulkVS port ID was logged for both phone numbers as is pictured below:

![image](https://user-images.githubusercontent.com/1683673/147169213-191c5cd1-4ecd-4ae7-9891-598fe0737622.png)

**To Reproduce**
1. Go to AccelerateNetworks.com/Lookup and run a port request with a local and toll free number attached
2. Head to Ops.AccelerateNetworks.com, find the order
3. Click on Related Port Request, then Submit to Teli & BulkVS

**Expected behavior**
The Teli port requests should only contain toll free numbers, while BulkVS's port requests should only contain local numbers. The correct LNP/Port request ID and vendor should be associated with the number in the Ops site.

**Comment by uncheckederror** [comment]
Port requests created with Teli should no longer include local numbers.
