### ISSUE TITLE
BulkVS Port API returning HTTP 400

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#255]
**Describe the bug**
Port request submission appears to have partially failed with BulkVS returning a HTTP 400, but port request ID 1656648 was created. We have asked BulkVS to confirm whether they reflect the same data as us for this port request.

Error text (pictured below):
```
Failed to submit port request to BulkVS: Call failed with status code 400 (Bad Request): POST https://portal.bulkvs.com/api/v1.0/portTn?OrderId= at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at NumberSearch.DataAccess.BulkVS.PortTNNote.PostAsync(String vendorOrderId, String username, String password) in /home/vsts/work/1/s/NumberSearch.DataAccess/BulkVS/PortTn.cs:line 132 at NumberSearch.Ops.Controllers.HomeController.UnifiedPortRequestAsync(String OrderId) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/HomeController.cs:line 3164 
```
**To Reproduce**
1. Go to Ops.AccelerateNetworks.com
2. Click on Orders, look for the order with 4254858600 associated with it
3. Scroll down to Submit to Teli and BulkVS, then press submit

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1683673/147703736-550e55aa-67fa-476a-83f2-daef1ea477a8.png)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser: Firefox
 - Version: 78.15.0esr (64-bit)

**Additional context**
Vendor input has been requested from BulkVS. Problem might be an API endpoint failure.

**Comment by uncheckederror** [comment]
The API call to update the "Note" data on the port request in BulkVS's system failed. Have they recently updated this API endpoint?

**Comment by danry25** [comment]
Unclear, waiting for this to be escalated to BulkVS's dev team. They have a link to this GitHub issue and should see your comment.

**Comment by uncheckederror** [comment]
The code that makes this API call is here: https://github.com/AccelerateNetworks/NumberSearch/blob/e15f9a9d6f520cb5fd63b0a74ea3b0ea4ee64b88/NumberSearch.DataAccess/BulkVS/PortTn.cs#L125
