### ISSUE TITLE
No visual response when attaching bill to port request

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#256]
**Describe the bug**
When I go through the website to submit a port request the bill attachment field doesn't show anything after I attach it. Which doesn't give me any indication if it is successfully attached. 

**To Reproduce**
1. Go to AccelerateNetworks.com
2. Add a phone number 
3. Go check out

**Expected behavior**
Show the file name so we can verify the file has been attached.

**Comment by uncheckederror** [comment]
@scottstrong206 @danry25 this should be fixed. Please try it now and then close this to confirm.

**Comment by danry25** [comment]
I can't get from the order confirmation page to the port information page on AccelerateNetworks.com now:
![image](https://user-images.githubusercontent.com/1683673/148484203-95a00b76-ced8-4923-b5d2-52136e1e46b6.png)
Nor does the direct link work: https://acceleratenetworks.com/Cart/PortingInformation/ab5c651e-a729-4b76-9feb-ef8fd69a1f0b

**Comment by uncheckederror** [comment]
This issue appears to be fully remediated - Dan
