### ISSUE TITLE
Ops - Can't view Quotes

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#258]
**Describe the bug**
I am unable to access https://ops.acceleratenetworks.com/Home/Quotes and receive this error
![image](https://user-images.githubusercontent.com/1683673/148872325-b67b9a34-bcd4-4354-98e5-05bce017f5b6.png)

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/Quotes
2. See error

**Expected behavior**
A list of quotes should be shown

**Comment by uncheckederror** [comment]
@danry25 this is fixed and deployed. Please try it now.
