### ISSUE TITLE
Ops - Track MAC address, quality and Serial Number of certain devices we stock locally

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#260]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This will enable easier loading of devices into gdms.cloud, dm.yealink.com and enable tighter inventory management and higher inventory churn.

**Is your feature request related to a problem? Please describe.**
We have all these phones in stock and we need to use their serial number and MAC to properly manage them in both FusionPBX and the vendor's device management system. When reselling imperfect devices, tracking the quality of the device would also be useful.

Additionally, when a TeleDynamics order ships they provide us the Serial Number and MAC address of the device along with a tracking number. It would be great to track this data.

**Describe the solution you'd like**
Add this data to our inventory page

**Describe alternatives you've considered**
Tracking on an out of band spreadsheet is what is currently done, though it gets out of sync and requires manual loading into Yealink and Grandstream's device management systems

**Comment by uncheckederror** [comment]
@danry25 can you provide a copy of this spreadsheet?

**Comment by danry25** [comment]
To recap @uncheckederror and my conversation, each product item should have a TeleDynamics order ID and a tracking # field.

**Comment by uncheckederror** [comment]
> To recap @uncheckederror and my conversation, each product item should have a TeleDynamics order ID and a tracking # field.

These fields are now live.

**Comment by danry25** [comment]
Everything on this issue is complete except what is listed below, closing this issue now.

Additionally, when a TeleDynamics order ships they provide us the Serial Number and MAC address of the device along with a tracking number. It would be great to track this data.
