### ISSUE TITLE
Ops - Failed to regenerate invoices

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#261]
**Describe the bug**
Regenerating invoices [on this quote](https://ops.acceleratenetworks.com/Home/Order/98234eb1-d077-4a7e-97f9-75274ba00041/NewInvoices) fails. The invoices are generated properly, but the below error is shown.

![image](https://user-images.githubusercontent.com/1683673/148885060-c8abe018-c6bf-4baa-a479-3168e0a203ee.png)

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/Order/98234eb1-d077-4a7e-97f9-75274ba00041/NewInvoices
2. Click on Regenerate Invoice
3. See error below top bar

**Expected behavior**
The invoices failed to regenerate :c

**Comment by uncheckederror** [comment]
@danry25 okay, this is fixed now.
