### ISSUE TITLE
Searching for 20679***** results in error

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#263]
**Describe the bug**
Searching for [https://acceleratenetworks.com/Search?Query=20679*****](https://acceleratenetworks.com/Search?Query=20679*****) or [https://acceleratenetworks.com/Search?Query=206791****](https://acceleratenetworks.com/Search?Query=206791****) or [https://acceleratenetworks.com/Search?Query=206705****](https://acceleratenetworks.com/Search?Query=206705****)

![image](https://user-images.githubusercontent.com/1683673/149018297-a5534c40-5b72-4186-a56b-8f4320f00572.png)

**Expected behavior**
Results (or lack thereof) should be shown.

**Comment by uncheckederror** [comment]
@danry25 these queries all result in a "No available numbers found!" response now.
