### ISSUE TITLE
Privacy policy needs updating according to google

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#266]
got this a couple days ago after google took down our old app
<img width="729" alt="Screen Shot 2022-01-19 at 12 10 09 AM" src="https://user-images.githubusercontent.com/44306072/150258916-1fbd0e22-6c61-417c-8469-8550d3c06f7d.png">

**Comment by piajesse** [comment]
actually after looking more closely at the current privacy policy
https://acceleratenetworks.com/privacy
it seems to only talk about the website and not the company as a whole.
should we do a complete rewrite of it to include what is collected for our apps.
or should we host another for the app
@danry25

**Comment by danry25** [comment]
We should make our privacy policy comprehensive for all services. The [Linphone](https://linphone.org/privacy-policy) and [Zoiper](https://www.zoiper.com/en/zoiper-privacy-policy) policies should act as a guide for what content we need to cover in our revised policy.

**Comment by uncheckederror** [comment]
Please attach a doc with the new privacy policy.

**Comment by piajesse** [comment]
After trying to clone what linphone used, we decided to only make a couple tweaks to the existing policy and fixing the issue that google pointed out. we will make changes again if they find an another issue
[Accelerate Networks Privacy Policy.docx](https://github.com/AccelerateNetworks/NumberSearch/files/7945483/Accelerate.Networks.Privacy.Policy.docx)

The main parts that were changed were

_This privacy policy discloses the privacy practices for the application AccelerateNetworks Mobile, and website addresses: *.acceleratenetworks.com and *callpipe.com._

And under sharing

_Accelerate Networks reserves the right to activate the debug logs in the AccelerateNetworks Mobile Application and in the software used to provide the Service. Such debug logs contain full protocol information for the calls, chat messages, contact lists, and other protocol events generated by the Users. This information may be shared with Belledonne Communications for the sole purpose of troubleshooting our services._

Along with adding the cherry street address.

**Comment by uncheckederror** [comment]
Updated privacy policy is live.

**Comment by uncheckederror** [comment]
@piajesse are we good?

**Comment by piajesse** [comment]
Date is wrong, should be effective today not 2 months from now

**Comment by piajesse** [comment]
Change the month in the date to January and we should be good, I'll then close this issue and submit this to google, and if another issue appears I'll reopen this issue

**Comment by uncheckederror** [comment]
> Change the month in the date to January and we should be good, I'll then close this issue and submit this to google, and if another issue appears I'll reopen this issue

This is done.
