### ISSUE TITLE
Partner Price List no longer works

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#275]
**Describe the bug**
An error is shown when going to the Partner Price List:
![image](https://user-images.githubusercontent.com/1683673/159382917-4936a3ea-e50f-4c4c-9314-19ef86c62c47.png)

**To Reproduce**
1. Go to https://acceleratenetworks.com/Hardware/PartnerPriceList
2. See error

**Expected behavior**
A price list of hardware should be shown.

**Comment by uncheckederror** [comment]
When our app tries to query the Teledynamics API for a VendorPartNumber, we get a 404 back which breaks the page. I have added some try catch logic to ignore failed requests.

".../api/v1/product/YEA-WH62-DUAL-UC/CheckQuantity" is the HTTP request that fails.

**Comment by uncheckederror** [comment]
@danry25 This fix is live. Thank you for this bug report.

**Comment by danry25** [comment]
Fixed YEA-WH62-DUAL-UC-YEAONLY and YEA-WH62-MONO-UC-YEAONLY VendorPartNumber to work, it appears TeleDynamics changed the SKU on us without warning.
