### ISSUE TITLE
Ops - Cannot mark order as Completed

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#276]
**Describe the bug**
I am unable to mark any order as done

**To Reproduce**
1. Go to any order not yet marked as done, say https://ops.acceleratenetworks.com/Home/Order/08abae11-8d47-4774-9a59-4f775c75a80a for example.
2. Click on the "Mark This Order as Completed" toggle
3. Scroll down to Update, press button
4. See no status change for the order.

**Expected behavior**
The order should be marked as done.

**Comment by danry25** [comment]
The issue persists when trying to mark any order as done, was the new build deployed yet?

**Comment by uncheckederror** [comment]
We broke the order form when we removed the field containing the OrderId, as the server no longer had a way to figure out what order we were trying to update. I have solved this issue by adding that id back to the form as a hidden field.

**Comment by danry25** [comment]
Ah, makes sense. FYI the OrderID is still displayed under Order Management in the Current Order ID field.

Let me know when the new build is deployed, just tested and could not mark this order as complete: https://ops.acceleratenetworks.com/Home/Order/08abae11-8d47-4774-9a59-4f775c75a80a

**Comment by uncheckederror** [comment]
@danry25 okay, new build is live.
