### ISSUE TITLE
Teli Inventory only partially shown on website

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#277]
**Describe the bug**
We are missing part of Teli's inventory of phone numbers

**To Reproduce**
1. Go to https://acceleratenetworks.com/Search?Query=206867****
2. See no numbers available

**Expected behavior**
500 available phone numbers are listed, by Teli, and their parent company owns this block of 1000 phone numbers so we should expect to see many of these numbers as available moving forward: https://apiv1.teleapi.net/dids/list?npa=206&nxx=867&token=OurToken

We can also iterate through to the next group of numbers by adding &offset=500 or similar to check for more results after the end of the current list.

**Comment by uncheckederror** [comment]
https://apiv1.teleapi.net/dids/nxxs?available=true&npa=206&token=OurToken

Returns only this:
{
    "code": 200,
    "status": "success",
    "data": [
        "408",
        "603"
    ]
}

But if we drop the availability parameter we get this:

{
    "code": 200,
    "status": "success",
    "data": [
        "864",
        "884",
        "904",
        "924",
        "944",
        "964",
        "984",
        "207",
        "201",
        "357",
        "462",
        "347",
        "445",
        "453",
        "567",
        "629",
        "693",
        "701",
        "743",
        "745",
        "866",
        "905",
        "858",
        "238",
        "946",
        "962",
        "501",
        "494",
        "577",
        "734",
        "922",
        "973",
        "407",
        "455",
        "801",
        "257",
        "826",
        "364",
        "204",
        "331",
        "512",
        "596",
        "260",
        "451",
        "299",
        "237",
        "312",
        "361",
        "428",
        "432",
        "444",
        "458",
        "720",
        "325",
        "420",
        "764",
        "957",
        "486",
        "694",
        "424",
        "488",
        "641",
        "900",
        "472",
        "317",
        "212",
        "259",
        "519",
        "749",
        "483",
        "889",
        "209",
        "489",
        "219",
        "340",
        "381",
        "607",
        "651",
        "777",
        "842",
        "886",
        "682",
        "938",
        "824",
        "751",
        "527",
        "452",
        "448",
        "433",
        "429",
        "362",
        "337",
        "323",
        "319",
        "279",
        "681",
        "728",
        "441",
        "328",
        "565",
        "480",
        "336",
        "487",
        "539",
        "552",
        "775",
        "855",
        "876",
        "899",
        "939",
        "408",
        "262",
        "604",
        "787",
        "707",
        "315",
        "717",
        "460",
        "937",
        "928",
        "789",
        "838",
        "687",
        "913",
        "283",
        "659",
        "388",
        "297",
        "582",
        "508",
        "785",
        "502",
        "275",
        "232",
        "686",
        "639",
        "457",
        "430",
        "278",
        "479",
        "529",
        "203",
        "282",
        "887",
        "247",
        "454",
        "309",
        "363",
        "652",
        "243",
        "367",
        "732",
        "495",
        "548",
        "546",
        "829",
        "934",
        "202",
        "636",
        "338",
        "397",
        "231",
        "216",
        "281",
        "569",
        "568",
        "492",
        "467",
        "324",
        "782",
        "339",
        "258",
        "825",
        "833",
        "350",
        "415",
        "426",
        "208",
        "735",
        "401",
        "513",
        "606",
        "524",
        "666",
        "249",
        "823",
        "385",
        "800",
        "898",
        "352",
        "778",
        "762",
        "625",
        "235",
        "792",
        "621",
        "624",
        "966",
        "806",
        "395",
        "285",
        "333",
        "737",
        "374",
        "742",
        "888",
        "542",
        "809",
        "456",
        "929",
        "518",
        "256",
        "623",
        "812",
        "788",
        "284",
        "783",
        "741",
        "244",
        "248",
        "466",
        "217",
        "417",
        "222",
        "288",
        "830",
        "923",
        "274",
        "538",
        "38",
        "784",
        "736",
        "402",
        "286",
        "431",
        "566",
        "241",
        "551",
        "632",
        "405",
        "729",
        "805",
        "594",
        "589",
        "558",
        "627",
        "794",
        "705",
        "536",
        "322",
        "588",
        "614",
        "289",
        "526",
        "932",
        "326",
        "926",
        "895",
        "200",
        "860",
        "329",
        "935",
        "590",
        "382",
        "832",
        "672",
        "496",
        "721",
        "722",
        "368",
        "561",
        "593",
        "649",
        "656",
        "752",
        "236",
        "970",
        "690",
        "839",
        "545",
        "557",
        "537",
        "841",
        "603",
        "844",
        "533",
        "635",
        "670",
        "677",
        "474",
        "710",
        "848",
        "709",
        "756",
        "758",
        "875",
        "761",
        "791",
        "413",
        "867"
    ]
}

Setting the availability parameter to false instead of true has no effect.

**Comment by uncheckederror** [comment]
@danry25 If we drop the available parameter just over a thousand numbers get ingested for the 206 area code. But the ingest takes 10 minutes rather than just 10 seconds for the 206 area code.

**Comment by danry25** [comment]
Closing as this is a bug in Teli's nxxs API

**Comment by danry25** [comment]
Teli Ticket 22959 has been opened
