### ISSUE TITLE
Ops - Allow set date and time of FOC/RDD

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#278]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This feature will allow us to schedule when we take over phone numbers from losing carriers, improving the customer transition experience and allowing us to schedule port requests to complete when the least labor hours will be needed to complete the customer transition.

**Is your feature request related to a problem? Please describe.**
A client requests a date 2 weeks in the future for us to cut over their phone numbers. This can be requested from [BulkVS](https://github.com/AccelerateNetworks/NumberSearch/blob/bce917b3e25e212b82da1dfa6c518bc94a5ac7ba/NumberSearch.Ops/Controllers/PortRequestsController.cs#L574-L575) but not for Teli.

**Describe the solution you'd like**
Add a date and time picker on the order in Ops with a default date of 3 days from now and a default time of 20:00:00

Update description in Ops to say the Requested Due Date (RDD) only applies to local phone numbers.

**Comment by uncheckederror** [comment]
Okay, this is live in the ops app. 

If a port request has a value for the Request Status, which is returned by the vendor after we submit the port request, then the Requested Due Date field is set to read only.

This date is only passed through for port requests through BulkVS.

Please verify this works the way you want @danry25

**Comment by danry25** [comment]
Having trouble when a port request is split into two separate port orders, it appears the RDD field is not greyed out [on this order](https://ops.acceleratenetworks.com/Home/PortRequests/8f18e40e-965c-49e0-b8a6-ffc9cb42e11f):
![image](https://user-images.githubusercontent.com/1683673/162520655-151cdbe3-b5e8-46b4-83e2-4cbfd825b380.png)

Additionally, datetime-local needs a polyfill like https://github.com/jonstipe/datetime-local-polyfill added.

**Comment by uncheckederror** [comment]
I have matched the behavior of the datetime picker in the RDD field to the behavior of the install date picker in the Mvc app. I have also fixed a scenario where the RDD wasn't being set on port requests. @danry25 please try it again.

**Comment by danry25** [comment]
Submitting port requests for local numbers now always immediately fails in Chrome or Firefox, and the RDD datepicker is a single blank field in Firefox.

Try submitting this order yourself: https://ops.acceleratenetworks.com/Home/PortRequestUnified/67a9c513-676d-4a5f-ba49-56f18aec8e9a

**Comment by uncheckederror** [comment]
@danry25 are we good on this?

**Comment by danry25** [comment]
Yes, we are good to go, I have verified this feature works :D
