### ISSUE TITLE
Enable the submission of Phone Numbers to be Ported in

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#28]
Right now there's no way for some one to submit a phone number that they would like to Port into their cart. This would be a good piece of functionality to add as Phone Numbers are commonly ported in when customer's are onboarded.

**Comment by danry25** [comment]
Here is the API doc to do a LNP check with Teli: https://apidocs.teleapi.net/lnp-portability/check-number-portability.html

There are a few other vendors out there, but for numbers that fail that test (nearly exclusively rural telecoms) we can manually process the client's order.

**Comment by uncheckederror** [comment]
I have implemented the porting process in 9a5af6b. This process does not use the Teli API, rather it merely verifies that the number doesn't already existing in the database and that it's a valid 10 digit number before allowing it to be added to the cart.

**Comment by uncheckederror** [comment]
I've added the portability checker call in 92d5690.
