### ISSUE TITLE
Priority Ingest from Peerless and Call48 every 15 minutes?

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#280]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Currently Peerless and Call48 have 40% to 50% churn every hour when we ingest our priority area codes from them. By ingesting more regularly (and purging the numbers no longer shown as available), we should display more accurate results and reduce customer frustration when attempting to buy phone numbers.

**Is your feature request related to a problem? Please describe.**
Often customers run into numbers no long being available for purchase when adding them to cart.

**Describe the solution you'd like**
Ingest priority area codes every 15 minutes for our high churn carriers, Peerless and Call48

**Additional context**
I am pretty sure Peerless and Call48 reserve the numbers they show us for a set period of time. Hopefully we can get number churn below the current 300 numbers that are dropped for each carrier on average for each hourly ingest by keeping this reservation of available numbers open...

**Comment by danry25** [comment]
Looks like we are getting numbers every 20 minutes from our vendors now in priority area codes, yet churn has remained just as bad with Peerless and Call48.

I have opened a ticket with Call48 to see if they can perform better, and I am investigating our options with Peerless to see if we can switch APIs.

![image](https://user-images.githubusercontent.com/1683673/166343672-61c29e3e-9479-4a99-b30f-b9374a0c8c18.png)

**Comment by danry25** [comment]
@uncheckederror How much time does using the ratecenter endpoint listed below add when just doing a priority ingest for Washington State and Oregon?

https://apicontrol.call48.com/apidocs#resources-get-rate-center-list-by-state-get

Looks like you disabled this in the past, IIRC when we were ingesting nationally: https://github.com/AccelerateNetworks/NumberSearch/blob/e130b0312ef23e59d4da6b88df6ebb590ae21062/NumberSearch.Ingest/Provider.cs#L158

**Comment by uncheckederror** [comment]
Ingesting numbers by ratecenter just for OR and WA takes 20 minutes to complete and pulls in ~19k numbers.

**Comment by danry25** [comment]
Crumb, I guess we could ratchet down to just ingesting hourly for priority area codes perhaps?

**Comment by uncheckederror** [comment]
@danry25 these changes are live and priority ingests now run on a 1 hour cycle.

**Comment by danry25** [comment]
@uncheckederror Awesome, churn as a percentage of number is down significantly (from around 50%) for Call48!

On Peerless do we currently ingest just the NPA, or NPANXX, or each ratecenter in priority area codes?

**Comment by uncheckederror** [comment]
On Peerless we just ingest numbers by their NPA. I don't see a way to get available NPANXX's or ratecenters through their API.

**Comment by danry25** [comment]
We can get the NPANXX by querying [getLergData](https://app.swaggerhub.com/apis/Peerless/PeerlessPortal/1.6.0#/lerg/getLergData) with the NPA parameter.

**Comment by uncheckederror** [comment]
> We can get the NPANXX by querying [getLergData](https://app.swaggerhub.com/apis/Peerless/PeerlessPortal/1.6.0#/lerg/getLergData) with the NPA parameter.

Our API key is not authorized to use this endpoint. Requests to this endpoint get a 401 response.
From the docs: "LERG information (super user only)"

**Comment by danry25** [comment]
I can't get Peerless's lerg endpoint to work unless I use it as a logged in user in a normal web browser.

Lets just query for these ratecenters and call it good? Make sure to exclude the area code when searching by ratecenter, as a ratecenter can contain multiple area codes if there is an overlay (eg: both 360 and 564)


**206 ratecenters**
`[ "BAINBDG IS", "DES MOINES", "RICHMNDBCH", "SEATTLE ", "VASHON " ]`
**253 ratecenters**
`
"AUBURN    ",
"DES MOINES",
"GIG HARBOR",
"GRAHAM    ",
"KENT      ",
"PUYALLUP  ",
"ROY       ",
"SUMNER    ",
"TACOMA    ",
"TACOMAWVLY"
`
**360 ratecenters**
`"ABERDEEN  ",
"AMBOY     ",
"ASHFORD   ",
"BATTLEGRND",
"BELFAIR   ",
"BLACKDIMND",
"BREMERTON ",
"BUCKLEY   ",
"BUCODA    ",
"CAMAS     ",
"CASTLEROCK",
"CATHLAMET ",
"CENTRALIA ",
"CHEHALIS  ",
"CHIMACMCTR",
"COPALIS   ",
"COUGAR    ",
"CRYSTAL MT",
"CURTIS    ",
"DEWATTO   ",
"EATONVILLE",
"ELMA      ",
"ENUMCLAW  ",
"FORKS     ",
"GRAYHARBCO",
"GRAYSRIVER",
"HAT ISLAND",
"HOOD CANAL",
"HOODSPORT ",
"KALAMA    ",
"KINGSTON  ",
"LA CENTER ",
"LKQUINAULT",
"LONG BEACH",
"LONGVIEW  ",
"MARYSVILLE",
"MONTESANO ",
"MORTON    ",
"MOSSYROCK ",
"MT VERNON ",
"NASELLE   ",
"OAK HARBOR",
"OCOSTA    ",
"OLYMPIA   ",
"ORTING    ",
"PACIFICBCH",
"PORT ORCH ",
"PORTLUDLOW",
"POULSBO   ",
"PT ANGELES",
"PT ROBERTS",
"PTTOWNSEND",
"RIDGEFIELD",
"ROCHESTER ",
"SALKUM    ",
"SAN JUAN  ",
"SHELTON   ",
"SILVERDALE",
"SKYKOMISH ",
"SNOHOMISH ",
"SO PRAIRIE",
"SO WHIDBEY",
"SOUTH BEND",
"STEVESPASS",
"TENINO    ",
"TOLEDO    ",
"UNION     ",
"VADER     ",
"VANCOUVER ",
"WHATCOMCTY",
"WINLOCK   ",
"WOODLAND  ",
"YACOLT    ",
"YALE      ",
"YELM      "`
**425 ratecenters**
`
"AMES LAKE ",
"BELLEVUE  ",
"BOTHELL   ",
"CARNATION ",
"EVERETT   ",
"FALL CITY ",
"HALLS LAKE",
"ISSAQUAH  ",
"KIRKLAND  ",
"MAPLE VLY ",
"NORTH BEND",
"RENTON    ",
"SILVERLAKE",
"SNOQUMPASS"
`
**503 ratecenters**
`"AMITY     ",
"ASTORIA   ",
"AUMSVLTRNR",
"AURORA    ",
"BAY CITY  ",
"BEAVER    ",
"BEAVER CRK",
"BEAVERTON ",
"CANBYNEEDY",
"CANNON BCH",
"CARLTON   ",
"CHARBONNEU",
"CLACKAMAS ",
"CLATSKANIE",
"CLOVERDALE",
"COLTON    ",
"CORBETT   ",
"DALLAS    ",
"DAYTON    ",
"DETROIT   ",
"ESTACADA  ",
"FALLS CITY",
"GARIBALDI ",
"GERVAIS   ",
"GOVENTCAMP",
"GRAND IS  ",
"GRANDRONDE",
"GRESHAM   ",
"HOOD LAND ",
"JEWELL    ",
"KNAPPA    ",
"LYONS     ",
"MCMINNVL  ",
"MILL CITY ",
"MOLALLA   ",
"MONITOR   ",
"MOUNTANGEL",
"NEHALEM   ",
"NEWBERG   ",
"NORTH PL  ",
"PACIFIC CY",
"PORTLAND  ",
"RAINIER   ",
"REDLAND   ",
"ROCKAWAY  ",
"SALEM     ",
"SCAPPOOSE ",
"SCIO      ",
"SEASIDE   ",
"SHERIDAN  ",
"SHERWOOD  ",
"SILVERTON ",
"ST HELENS ",
"ST PAUL   ",
"STAYTON   ",
"STFRD-SNDY",
"TILLAMOOK ",
"VERNONIA  ",
"WARRENTON ",
"WESTPORT  ",
"WILLAMINA ",
"WOODBURN  ",
"YAMHILL   "`

**509 ratecenters**
`"ALMIRA    ",
"ANATONE   ",
"ASOTIN    ",
"BENTONCITY",
"BREWSTER  ",
"BRIDGEPORT",
"CHENEY    ",
"CHEWELAH  ",
"CLARKSTON ",
"CLE ELUM  ",
"COLFAX    ",
"COLUMBIA  ",
"COLVILLE  ",
"CONNELL   ",
"COULEE DAM",
"COULEECITY",
"COWICHE   ",
"CRESTON   ",
"CURLEW    ",
"CUSICK    ",
"DALLESPORT",
"DAVENPORT ",
"DAYTON    ",
"DEER PARK ",
"DOUGLASCO ",
"EDWALLTYLR",
"ELK-GRNBLF",
"ELLENSBURG",
"ENDICOTT  ",
"EPHRATA   ",
"EUREKA    ",
"FARMINGTON",
"GARFIELD  ",
"GARRISON  ",
"GEORGE    ",
"GLENWOOD  ",
"GOLDENDALE",
"GRANDVIEW ",
"GRANGER   ",
"HARRAH    ",
"HARRINGTON",
"IONE      ",
"KENNEWICK ",
"KETTLE FLS",
"KLICKITAT ",
"LACROSSE  ",
"LIBERTY LK",
"LIND      ",
"LOOMIS    ",
"LOON LAKE ",
"LYLE      ",
"MABTON    ",
"MATHEWSCOR",
"MATTAWA   ",
"MEDICAL LK",
"METALINFLS",
"MOLSON    ",
"MOSES LAKE",
"MT HULL   ",
"NACHES    ",
"NESPELEM  ",
"NEWMANLAKE",
"NEWPORT   ",
"NILE      ",
"NORTHPORT ",
"OAKESDALE ",
"ODESSA    ",
"OMAK      ",
"OROVILLE  ",
"OTHELLO   ",
"PALOUSE   ",
"PASCO     ",
"PATEROS   ",
"PATERSON  ",
"POMEROY   ",
"PRESCOTT  ",
"PROSSER   ",
"PULLMAN   ",
"QUINCY    ",
"REARDAN   ",
"REPUBLIC  ",
"RICHLAND  ",
"RIMROCK   ",
"RITZVILLE ",
"ROCKFORD  ",
"ROOSEVELT ",
"ROSALIA   ",
"ROSLYN    ",
"SELAH     ",
"SOAP LAKE ",
"SPANGLE   ",
"SPOKANE   ",
"SPRAGUE   ",
"SPRINGDALE",
"ST JOHN   ",
"STARBUCK  ",
"STEVENSON ",
"SUNNYSIDE ",
"TEKOA     ",
"TIETON    ",
"TONASKET  ",
"TOPPENISH ",
"TOUCHET   ",
"TROUT LAKE",
"TWISP     ",
"UNIONTOWN ",
"WAITSBURG ",
"WALLAWALLA",
"WAPATO    ",
"WARDEN    ",
"WASHTUCNA ",
"WENATCHEE ",
"WH SALMON ",
"WHITE SWAN",
"WHITSTRAN ",
"WILBUR    ",
"WILLARD   ",
"WILSON CRK",
"YAKIMA    "`


**541 ratecenters**
`"ADRIAN    ",
"ALBANY    ",
"ALSEA     ",
"ANTELOPE  ",
"ARLINGTON ",
"ASH VALLEY",
"ASHLAND   ",
"ATHENA    ",
"AZALEA    ",
"BAKER     ",
"BANDON    ",
"BATES     ",
"BELLFONTAN",
"BEND      ",
"BLACKBUTTE",
"BLODGETT  ",
"BLUE RIVER",
"BLY       ",
"BOARDMAN  ",
"BONANZA   ",
"BROOKINGS ",
"BROWNSVL  ",
"BURNS     ",
"BUTTEFALLS",
"CAMAS VLY ",
"CANYONVL  ",
"CASCADELKS",
"CAVE JCT  ",
"CENTRAL PT",
"CHEMULT   ",
"CHILOQUIN ",
"CHITWOOD  ",
"CONDON    ",
"COOS BAY  ",
"COQUILLE  ",
"CORVALLIS ",
"COTTAGEGRV",
"COVE      ",
"CRATERLAKE",
"CRESWELL  ",
"CULVER    ",
"DAYS CREEK",
"DAYVILLE  ",
"DEPOE BAY ",
"DIAMOND LK",
"DRAIN     ",
"DUFUR     ",
"DURKEE    ",
"ECHO      ",
"ELGIN     ",
"ELKTON    ",
"ENTERPRISE",
"EUGENE    ",
"FISH LAKE ",
"FLORA TROY",
"FLORENCE  ",
"FOSSIL    ",
"FT KLAMATH",
"GILCHRIST ",
"GLENDALE  ",
"GLIDE     ",
"GOLD BEACH",
"GOLD HILL ",
"GRANTSPASS",
"GRASS VLY ",
"HAINES    ",
"HALFWAY   ",
"HALSEY    ",
"HARLAN    ",
"HARPER    ",
"HARRISBURG",
"HELIX     ",
"HEPPNER   ",
"HEREFDUNTY",
"HERMISTON ",
"HOOD RIVER",
"HORTON    ",
"HUNTINGTON",
"IMBLER    ",
"IONE      ",
"JACKSONVL ",
"JEFFERSON ",
"JOHN DAY  ",
"JORDAN VLY",
"JOSEPH    ",
"JUNCTIONCY",
"JUNTURA   ",
"KLAMATHFLS",
"LA GRANDE ",
"LAKESIDE  ",
"LAKEVIEW  ",
"LANGLOIS  ",
"LAPINE    ",
"LEABURG   ",
"LEBANON   ",
"LEXINGTON ",
"LINCOLN CY",
"LOBSTERVLY",
"LONG CREEK",
"LOSTINE   ",
"LOWELL    ",
"MADRAS    ",
"MALIN     ",
"MAPLETON  ",
"MARCOLA   ",
"MAUPIN    ",
"MEACHAM   ",
"MEDFORD   ",
"MEDICALSPG",
"MERRILL   ",
"MILTONFWTR",
"MITCHELL  ",
"MONROE    ",
"MONUMENT  ",
"MORO      ",
"MOSIER    ",
"MT VERNON ",
"MYRTLE CRK",
"MYRTLE PT ",
"NEWPORT   ",
"NO HARNEY ",
"NO POWDER ",
"NO UMPQUA ",
"NYSSA     ",
"O BRIEN   ",
"OAKLAND   ",
"OAKRIDGE  ",
"ODELL     ",
"ONTARIO   ",
"OREGONSLOP",
"OXBOW     ",
"PAISLEY   ",
"PARKDALE  ",
"PAULINA   ",
"PENDLETON ",
"PHILOMATH ",
"PHOENIX   ",
"PILOT ROCK",
"PINE GROVE",
"PORTORFORD",
"POWERS    ",
"PRAIRIE CY",
"PRINEVILLE",
"PROSPECT  ",
"PROVOTMPHY",
"QUINN     ",
"REDMOND   ",
"REEDSPORT ",
"RICHLAND  ",
"RIDDLE    ",
"RIDGEVIEW ",
"ROCKYPOINT",
"ROGUERIVER",
"ROSEBURG  ",
"RUFUS     ",
"SCOTTSBURG",
"SELMA     ",
"SENECA    ",
"SHADY COVE",
"SHEDD     ",
"SILETZ    ",
"SILVERLAKE",
"SISTERS   ",
"SO HARNEY ",
"SOUTHBEACH",
"SPRAGUERIV",
"SPRAY     ",
"STANFIELD ",
"STATELINE ",
"SUMMIT    ",
"SUMPTER   ",
"SWEET HOME",
"THE DALLES",
"THREE RVS ",
"TIDEWATER ",
"TOLEDO    ",
"TRIANGLELK",
"TYGHVALLEY",
"UKIAH     ",
"UMATILLA  ",
"UNION     ",
"VALE      ",
"VENETA    ",
"WALDPORT  ",
"WALLOWA   ",
"WAMIC     ",
"WASCO     ",
"WHITE CITY",
"WOLF CREEK",
"YACHATS   ",
"YONCALLA  "`

**564 ratecenters**
Already covered in other area code lists.

**Comment by uncheckederror** [comment]
@danry25 okay these changes are live.

**Comment by danry25** [comment]
The ingested phone number count looks a bit higher from these providers than last week, thanks for implementing this @uncheckederror
