### ISSUE TITLE
Ingest Write.as blog posts

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#283]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Bringing our blog posts into the main AccelerateNetworks.com site will improve our search ranking and hopefully improve revenue by enabling people to find our website easier and sooner.

**Is your feature request related to a problem? Please describe.**
Currently our blog is on a separate subdomain at https://blog.acceleratenetworks.com which does not help our website in search engine rankings, and also does not have the appropriate he

**Describe the solution you'd like**
Ingest blog posts from the Write.as API ([.Net Core client](https://github.com/DinoBansigan/WriteAs.NET#writeasnet)) and display these under https://acceleratenetworks.com/blog/happy-halloween (instead of https://blog.acceleratenetworks.com/happy-halloween )

**Describe alternatives you've considered**
I have tried monkeying with the CSS to fix up the header, but without the ability to edit the HTML of the header and footer my options to affect change are limited.

**Comment by uncheckederror** [comment]
The write.as public API rate limits the number of times we can query their API to ~10ish times per hour. To work around this I am going to query their API just once when the blogs page is first loaded and then store the response in our database.

**Comment by danry25** [comment]
[If we log in](https://discuss.write.as/t/new-rate-limits-on-publishing/2658) the API will permit many more queries since we are a paid user, [use the auth endpoint to do so](https://www.postman.com/extratone/workspace/extranet/documentation/15808119-22109e65-119d-4b03-8949-ea7c7d739d93) and it appears you pass the apiKey param [when initializing the WriteAs.Net client](https://github.com/DinoBansigan/WriteAs.NET/blob/master/README.md?plain=1#L39).

Can we reingest articles that are under 24 hours old a bit more regularly, say once an hour? Could we add a reingest all articles button in the ops app?

**Comment by uncheckederror** [comment]
[https://acceleratenetworks.com/blog](https://acceleratenetworks.com/blog)

and

[https://acceleratenetworks.com/blog?query=Are%20your%20internet%20costs%20set%20to%20explode?](https://acceleratenetworks.com/blog?query=Are%20your%20internet%20costs%20set%20to%20explode?)

**Comment by uncheckederror** [comment]
@danry25 still waiting on you to provide some direction here.

**Comment by danry25** [comment]
@uncheckederror Can we narrow the column width on https://acceleratenetworks.com/Blog to match https://blog.acceleratenetworks.com and increase the font size to match.

Additionally, lets link to https://acceleratenetworks.com/Blog in the footer and close issue #292

**Comment by uncheckederror** [comment]
I have decreased the column width to match the width of the page header. It's close but not exactly the same as the write.as blog page layout. Reducing the column width past the size of the page header makes it look weird. The font sizes are the same across both pages, although we use a thinner font that write.as.

**Comment by danry25** [comment]
@uncheckederror is this change in production yet? The page still looks the same, and this other change also appears to be unapplied: https://github.com/AccelerateNetworks/NumberSearch/commit/c656ba27f8e6f293f4a960aed4f203b2a6909a4e
