### ISSUE TITLE
Project doesn't build on macOS

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#284]
When using the "dotnet build" command on macOS this error is reported:

`NumberSearch.Ops -> /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Ops/bin/Release/net6.0/publish/
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/FirstCom/appsettings.Development.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Mvc/appsettings.Development.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/FirstCom/appsettings.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Mvc/appsettings.json. [/Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Mvc/NumberSearch.Mvc.csproj]
  NumberSearch.Tests -> /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Tests/bin/Release/net6.0/NumberSearch.Tests.dll
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/FirstCom/appsettings.Development.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Mvc/appsettings.Development.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/FirstCom/appsettings.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Mvc/appsettings.json. [/Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Tests/NumberSearch.Tests.csproj]`

After updating the .csproj files for FirstCom, Ops, and Mvc this error was reported:

`/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/FirstCom/appsettings.Development.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Mvc/appsettings.Development.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/FirstCom/appsettings.json, /Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Mvc/appsettings.json. [/Users/piajesse/Nextcloud/Work/Accelerate networks/Projects/NumberSearch/NumberSearch.Tests/NumberSearch.Tests.csproj]`

![image](https://user-images.githubusercontent.com/11726956/169594472-506525ad-a318-4a9d-a0f0-11a51dd96452.png)

**Comment by uncheckederror** [comment]
@piajesse does it work now?

**Comment by piajesse** [comment]
Works Great, thanks for the help, now to remove Kyle from the about page
