### ISSUE TITLE
Need to update the about page

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#285]
I'm working on removing Kyle and adding Joy to the about page, once I get changes pushed, I will need @uncheckederror help with updating prod

**Comment by uncheckederror** [comment]
Do we have picture of Joy and a blurb about her to replace the existing content for Kyle?

**Comment by piajesse** [comment]
yeah, I'm trying to figure out where do I add her photo to, I added it to `NumberSearch.Mvc/wwwroot/images/scaled/joy.jpg`, but I'm getting a 404

**Comment by piajesse** [comment]
other then the image not working, I have pushed everything in a #286, can you get the image working and crop if needed and push to prod @uncheckederror?

**Comment by uncheckederror** [comment]
Had to do a couple of commits worth of clean up, but these changes are now live on the website. https://acceleratenetworks.com/About
