### ISSUE TITLE
Errors in Ops Showing Inaccurate Port Info

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#289]
**Describe the bug**
Ops shows inaccurate port information i.e. shows Exception when in reality the port is Completed. An example of this is port 1667624, under number 4252715601 in ops.

**To Reproduce**
1. Go to Ops
2. Click on Port Requests
3. Scroll down to a port that has Exception as status
4. Check BulkVS or Teli and confirm port has actually gone through
5. See error

**Expected behavior**
The port requests should be trusted to show accurate info

**Screenshots**

**Desktop (please complete the following information):**
Danry25 also encountered the same problem (and asked the issue be filed)
 - OS: Windows/Linux
 - Browser Firefox/Firefox
 - Version 99.0.1/?

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by uncheckederror** [comment]
Alright, but something isn't right with this [port request ](https://ops.acceleratenetworks.com/Home/PortRequests/c9709ca8-3fb5-4ab3-a7f1-d7efd6888112) because 2 of the 6 numbers show a status of EXCEPTION. Do you want to mark the port as complete even when some of the numbers failed to port?

**Comment by danry25** [comment]
@uncheckederror the overarching status of a request should be Complete when the individual number statuses on a request are Complete.

The core issue we are experiencing is there is no way to remove numbers from a port request in Ops, even when we already had the vendor the port request was submitted to remove a phone number from said request.

**Comment by uncheckederror** [comment]
The remove button will show up on numbers in the port with a status of EXCEPTION. Once all the numbers in the port have a status of COMPLETE the the ingest app will mark the whole port as completed on the next pass and you'll have what you want.

**Comment by danry25** [comment]
Closing as this is resolved
