### ISSUE TITLE
Add Discount Code for 5G Internet

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#290]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**

This will allow us to meet current competitive ISP pricing and convert customers away from traditional ISPs.

**Is your feature request related to a problem? Please describe.**
I requested this discount code on issue #287 but it was not implemented :c

**Describe the solution you'd like**
Add a code named Partner that discounts 5G Internet - Static IP and 5G Internet by $10 a month.

**Describe alternatives you've considered**
We are currently manually modifying quotes and orders to reflect the correct price.

**Comment by uncheckederror** [comment]
@danry25 please validate this example of the coupon in use: https://acceleratenetworks.com/cart/order/97ebe179-904f-4ee5-9059-2f0ce08eecc9

**Comment by danry25** [comment]
This looks correct, thanks @uncheckederror !
