### ISSUE TITLE
Ignore capitalization, spaces and other formatting on coupons 

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#291]
**Describe the bug**
People are bad at typing coupons in properly, and often miscapitalize coupon codes or add or skip spaces when entering coupon codes.

**Expected behavior**
Can we delete all non-alphanumeric characters from a coupon code (eg: spaces, dashes, etc) and make coupon codes case insensitive when checking if a coupon code is valid?

**Comment by uncheckederror** [comment]
At the moment we from leading and trailing spaces, then we remove all spaces and convert all characters to the lowercase forms.

https://github.com/AccelerateNetworks/NumberSearch/blob/030abd2eededc2343700ad8aa648d0950862953b/NumberSearch.Mvc/Controllers/CartAPIController.cs#L1104

**Comment by danry25** [comment]
Leading space and trailing spaces cause an error saying "Failed to add Coupon  waive port to cart."

**Comment by uncheckederror** [comment]
So this is an issue where the parsed and regularized string from the API fails the check in Javascript where the expectation is that it will exactly match the string the user provided. If you refresh the page you'll see the coupon was added to the cart, despite the failure message from the whitespaces.

I have updated the JS to trim leading and trailing whitespaces to prevent this issue from reoccurring.

**Comment by danry25** [comment]
The whitespaces are getting trimmed, but an error "Failed to add Coupon  waive port to cart." is still being shown after hard reloading the page (Ctrl, Shift and R).

**Comment by uncheckederror** [comment]
Yeah, because I still have to deploy the new build.

**Comment by danry25** [comment]
Lol, my cart emptied so I figured you had just deployed a new build :D

**Comment by uncheckederror** [comment]
Alright, the new build is finally live. Please try it now.

**Comment by uncheckederror** [comment]
This change broke adding numbers to the cart. 

@danry25 this is why I ask you to verify the changes, because bugs like this slip through and no one's been able to purchase a number through the website for 10 days.

**Comment by danry25** [comment]
This works well based on my testing
