### ISSUE TITLE
Resources/Blog links to a different page then the blog button in the footer

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#292]
**Expected behavior**
Both links should link to the same place

**Current Behavior**
Right now resources/blog links to https://acceleratenetworks.com/blog while the one in the footer links to https://blog.acceleratenetworks.com.

**Additional context**
Also, https://acceleratenetworks.com/blog is 3 posts out of date, if we keep this version update to date, I think we should use /blog rather then blog.acceleratenetworks.com as it keeps the theme

**Comment by uncheckederror** [comment]
This issue is blocked by approval/feedback on #283.
