### ISSUE TITLE
Add ability to filter hardware by available features

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#293]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This would be a neat feature to have select the phones that matches the requirements you need/want, like PoE, bluetooth, amount of active extensions etc... Would be great for window shoppers 😛 

**Describe the solution you'd like**
I think we could implement this with a json string with all the devices and their info and have all the logic client side. We could have a filter button that opens a sub-menu (or a sidebar) and provides a checklist of features (features should have a link their descriptions) while also having a 2 ended slider for the amount of extensions supported, like for saying I want something with at-least 4 extensions, but not more then 5.

**Describe alternatives you've considered**
We could not implement this feature. I think @danry25 should approve this, which is why I assigned him to this issue.
The filter sidebar could always be visible with a header like "Filter"

**Comment by piajesse** [comment]
Also maybe making it so you can say you require that feature not be on a device e.g. WiFi for those zones that don't allow it.

**Comment by Chattaeus** [comment]
This would also be nice to have from our perspective in case anyone on the sales team or I were unsure of the features on a specific phone. Quicker than Google.

**Comment by danry25** [comment]
@piajesse Please leave feature implementation details to @uncheckederror for Number Search. In the future please tag with Internal or External as well, and don't tag with question when making a feature request.

**Comment by uncheckederror** [comment]
Right now we don't maintain a list for each device of the features that it supports. So we don't have this data to filter on. Where would we capture this data about the features/capabilities of each device from? Are we imagining this data as a list of tags associated with a device that you can filter on?

**Comment by danry25** [comment]
A list of tags associated with each device would be reasonable to maintain, I'm happy to fill this in for each device if you want to add a field for tags

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/195729620-8236d3cc-d2b7-44fb-adea-797fd67172af.png)

Using the Ops you can now update the tags for a specific Product on the Hardware page. Tags are a comma separated list. Once we have some valid tags for the public products I'll figure out how to enable filtering in the Mvc app.

**Comment by danry25** [comment]
When adding descriptions to resolve issue #318 I added tags including WiFi, Bluetooth, Ethernet, PoE, Touchscreen, Gigabit to the description of each phone, and I tagged the accessories as well.
