### ISSUE TITLE
Blog isn’t updating

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#295]
**Describe the bug**
A post has been edited but doesn’t show up on /blog yet, also there is another post that isn’t showing up on the website yet

**To Reproduce**
Compare https://blog.acceleratenetworks.com to https://acceleratenetworks.com/blog

**Comment by danry25** [comment]
Pretty sure this ingest happens every hour, or daily for the blog.

Please tag issues properly in the future @piajesse, and assign them to a person.

**Comment by piajesse** [comment]
I mean the picture for “VoIP - Is right for you?” has been updated on write.as but not the /blog

**Comment by uncheckederror** [comment]
@piajesse you can trigger then ingest using the refresh true query string now. Are we good?

**Comment by piajesse** [comment]
I will have to test after Joy posts a new article, will reopen if I run into an issue

**Comment by danry25** [comment]
Sending https://acceleratenetworks.com/blog?refresh=true does not seem to re-ingest the latest article to pick up the change that 1m was removed from the end of the very last line.

**Comment by uncheckederror** [comment]
You're getting a cached copy of the page. The caching times out after an hour, at which point you can try again.

Please make your edits using the Write.As editor, this page is a simple cached mirror of the content on that site. It's not intended to be used to review or edit the content displayed.
