### ISSUE TITLE
Blog shows up as privacy policy on page title.

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#296]
**Describe the bug**
Check this line https://github.com/AccelerateNetworks/NumberSearch/blob/master/NumberSearch.Mvc/Views/Blog/Index.cshtml#L2

**Comment by uncheckederror** [comment]
@piajesse https://acceleratenetworks.com/Blog Please verify the fix and close this issue if we're good.

**Comment by piajesse** [comment]
Looks Great, Thanks
