### ISSUE TITLE
Add Product Photos

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#299]
If we could add these photos, I would appreciate it :)

Yealink W53P: https://www.teledynamics.com/tdresources/26f8f8cc-48a3-48b9-a6ab-d47970cb4895.jpg
Yealink W53H: https://www.teledynamics.com/tdresources/efacc098-5888-44c0-b6f0-cf780e94404b.jpg
GUV3050: https://www.teledynamics.com/tdresources/67a5de87-a8cb-4b6f-a7ca-5be5ee537d2b.jpg
GRP Wallmount: https://www.teledynamics.com/tdresources/efa32c58-cdb1-4927-8358-1fa8b6081f94.jpg

**Comment by uncheckederror** [comment]
These photos are all live. Please verify this change and close the issue if we're good @danry25.

**Comment by danry25** [comment]
The changes are not correct, it appears some images got swapped, and the 

Yealink W53P should show a single cordless handset, instead it shows a GXP Wall Mount: https://acceleratenetworks.com/images/scaled/W53P-400.webp
Yealink W53H should show a cordless handset and baaestation, instead it shows a headset: https://acceleratenetworks.com/images/scaled/W53H-400.webp
Grandstream GUV3050 shows a cordless handset and base rather than a headset: https://acceleratenetworks.com/images/scaled/GUV3050-400.webp

Grandstream GRP2615 Wallmount was edited to show a cordless handset and basestation instead of a chunk of plastic: https://acceleratenetworks.com/images/scaled/GRP-Wallmount-400.webp

For this last one, I actually want us to use the same image as GRP Wallmount Small. The current GRP Wallmount Small image is upside down fyi.

This image should actually be Grandstream GXP Wall Mount, I mislabeled it when opening the issue: https://www.teledynamics.com/tdresources/efa32c58-cdb1-4927-8358-1fa8b6081f94.jpg

**Comment by uncheckederror** [comment]
Okay, new content is live. Please review this again @danry25.

**Comment by danry25** [comment]
Please delete the incorrect images linked to in my post yesterday from the repository.

Additionally, https://acceleratenetworks.com/images/scaled/Yealink-GUV3050-400.webp is misnamed, the headphones are Grandstream GUV3050, and have no association with Yealink.

Everything else looks good, thanks @uncheckederror !
