### ISSUE TITLE
Collect information required to process a port request

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#30]
In addition to the information we collect on #28, we also need to gather the following information to port a phone number. Ideally, we would have a review queue where an employee would check a port request before it is [submitted to this API](https://apidocs.teleapi.net/api/lnp-portability/create-order).

Often, clients do not know all of this information or provide us the billing address or an incorrect contact that is not listed as an authorized person on the account. We can usually clean this up with a quick review of the client's bill.

**Billing Phone** - Also known as the BTN. This is the number that is normally provided on a copy of your bill or statement in the upper right corner or is the first number listed on the bill.
**Location Type** - Designates if this is a business address or a residential address.
**Business Contact** - This is the name of the owner or contact who will be submitting the port order.
**Business Name** - Name of the business associated with the numbers being ported.
**Account Number** - The account number is usually found on the invoice or a copy of a bill from your current provider.
**Service Address** - The physical address of where these phone numbers are being used. This information is also on file with your current provider.
**Service City** - The city of the service address listed above.
**Service State** - The state of the service address listed above.
**Service ZIP** - The five digit ZIP code of the service address listed above.
**Partial Port** - Designates whether or not this will be cancelling all services on the account or leave remaining services and port only the specified numbers in the port order. Some carriers do not respect this request, please check with your old carrier!
**Partial Port Description** - Describe what services the old carrier should leave alone. Contact the old carrier to confirm they will leave these services intact.
**Wireless Number** - Set to "Yes" if this is a wireless or cellphone number being ported.
**Signature** - The signature is needed in order to submit a port order. It is perfectly fine to use the mouse to the best of your ability to sign for this port request. Teli uses [Signature Pad v1.5.3](https://github.com/szimek/signature_pad) with a size of 200px height and 400px width.
**Caller ID** - Sets Caller ID (aka CNAM) for all numbers in this port order, 15 character limit.
**Numbers** - The numbers that will be ported to Accelerate Networks on this port order.
**Bill** (file upload)

**Comment by uncheckederror** [comment]
@danry25 To implement some sort of review queue we would need to have authentication and authorization for internal customers.

How would we test the Porting API to make sure our code is working correctly?

**Comment by danry25** [comment]
Perhaps its best to just put it in an email or post to Erxes API then? That avoids auth and testing entirely. I don't want to stuff the review queue at Teli with needless ports...

**Comment by uncheckederror** [comment]
Yes, perhaps we should revisit those issues in the future.

For the initial implementation an email will be sent to Erxes for the order, which will include the numbers to port.

And then a second email will be sent to Erxes with a list of the phone numbers to port once they fill out the porting information.

The handling of the order and the porting request will remain once it reaches Erxes.

**Comment by uncheckederror** [comment]
This process is partially implemented. 

The remaining work items are:

1. The file upload for the image of the bill.
2. The file upload for the customer's Signature.
3. Create a database table to store this information.

**Comment by uncheckederror** [comment]
Dropping the requirement for a signature. Adding a new requirement for an account PIN or password.

**Comment by uncheckederror** [comment]
This work has been committed in 137ff4d. The billing image is current saved to the web server as a temporary file and then dis-guarded. We need to work out where to store the billing images.

**Comment by uncheckederror** [comment]
Rather than saving the file some where the requirement is to attach it to an outgoing email and send it off immediately.

**Comment by uncheckederror** [comment]
Images are now being forwarded as email attachments in 27f2c0e
