### ISSUE TITLE
Upgrade Invoice Ninja to the latest version

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#303]
Newer versions of Invoice Ninja have a more complete API to interact with and better documentation.

It is difficult to query information like monthly revenue from our current Invoice Ninja instance.

Our ability to create custom dashboards based off of the Invoice Ninja dataset and integrate them into the Ops app is limited by the existing API and could be improved by moving to a newer version of Invoice Ninja.

**Comment by uncheckederror** [comment]
The upgrade has been completed by @danry25 

Integrations to complete:
- Create Customer (Business Name, Person's name, Physical Address, Email)
- Quote Creation
- Invoice Creation
- Recurring Invoice Creation
- Adding tax rate to invoices
- Email lookup to match with existing clients
- Invoice or Quote Regeneration (New API should handle editing a quote or invoice rather than deleting and recreating with new invoice or quote #)
- Use Payment webhook to update Pizza Tracker status for an order

**Comment by uncheckederror** [comment]
@danry25 trying to query for a list of invoices and their clients results in an HTTP 500 response:

https://billing.acceleratenetworks.com/api/v1/invoices?include=clients

Trying to flip this query around doesn't get us anywhere because although the list of clients is returned, there invoices are not:

https://billing.acceleratenetworks.com/api/v1/clients?include=invoices

**Comment by danry25** [comment]
I think you need to look at a specific client using [/api/v1/clients/{id}](https://app.swaggerhub.com/apis/invoiceninja/invoiceninja/5.5.37#/clients/showClient) and set include=clients,invoices based on their example.

**Comment by uncheckederror** [comment]
Okay, I tried that method and it didn't work. But https://billing.acceleratenetworks.com/api/v1/invoices?client_id= did work to get a list of invoices for a specific client.

**Comment by danry25** [comment]
To recap our conversation, when someone runs an order we should add products and services to an invoice by creating a new invoice using [getInvoicesCreate](https://app.swaggerhub.com/apis/invoiceninja/invoiceninja/5.5.37#/invoices/getInvoicesCreate), then update it with the correct company_id, client_id, tax_name1, tax_rate1, and I think line_items using [updateInvoice](https://app.swaggerhub.com/apis/invoiceninja/invoiceninja/5.5.37#/invoices/updateInvoice), and use the same updateInvoice endpoint for regenerating the invoices in Ops.

For services, we should create a separate recurring invoice too using [getRecurringInvoicesCreate](https://app.swaggerhub.com/apis/invoiceninja/invoiceninja/5.5.37#/recurring_invoices/getRecurringInvoicesCreate) then add the aforementioned values to it using [updateRecurringInvoice](https://app.swaggerhub.com/apis/invoiceninja/invoiceninja/5.5.37#/recurring_invoices/updateRecurringInvoice) so all we need to do is set a start date manually and the recurring invoice will start billing.

If the quote checkbox is selected, lets create the recurring invoice as mentioned above, but generate separate quotes for monthly services and upfront products. Looks like we need to hit [getQuotesCreate](https://app.swaggerhub.com/apis/invoiceninja/invoiceninja/5.5.37#/quotes/getQuotesCreate) to create the blank quote, then update it using [updateQuote](https://app.swaggerhub.com/apis/invoiceninja/invoiceninja/5.5.37#/quotes/updateQuote).

**Comment by uncheckederror** [comment]
The first month of service goes on the initial invoice, a reoccurring invoice is also created at the same time for subsequent months. The customer is only linked to the initial invoice via email and the order, not the reoccurring invoice. This is a complete change from the old system.

**Comment by uncheckederror** [comment]
@danry25 Using the POST /clients endpoint to create a new billing client I can't seem to modify the contact record to give the client a first name, last name, or email address. I am trying to find a method to update the email of a contact associated with a billing client via the API. I have also tried the PUT /clients/{id} endpoint to no avail.

**Comment by uncheckederror** [comment]
Another issue that I am running into is creating new tax rate entries, so far I haven't been able to successful do so using the API endpoints.

**Comment by uncheckederror** [comment]
To create a billing client and add an email address for its contact we can use a combination of the POST /clients/ endpoint with a JSON body of just the name field  `{ "name": "billingName" }` and then we can capture the Id of the new billing client from the response and use to call PUT /clients/{Id} to update the contact record for this billing client with the email, first name, last name, and phone number with a JSON body mirroring the format of record, but only with the fields we're interested in. 
```
{
    "contacts": [
        {
            "first_name": "loll",
            "last_name": "lmao",
            "email": "lo213l@test.com",
            "phone": "2067696361"
        }
    ]
}
```

**Comment by danry25** [comment]
@uncheckederror Create Customer is not functioning properly, Person's name, Physical Address and Email are not being set.

![image](https://user-images.githubusercontent.com/1683673/213290617-0b7ddb08-c975-4410-8e4a-e834bb593e9a.png)

**Comment by uncheckederror** [comment]
> @uncheckederror Create Customer is not functioning properly, Person's name, Physical Address and Email are not being set.
> 
> ![image](https://user-images.githubusercontent.com/1683673/213290617-0b7ddb08-c975-4410-8e4a-e834bb593e9a.png)

Okay, I think know why client creation isn't working. To create a client you have to POST the name of the client to the /clients/ endpoint, then you have to use the PUT /clients/{client_id} endpoint to actually set the contact and address information.

**Comment by danry25** [comment]
When quoting a recurring service, we need to make a recurring quote in addition to preparing the recurring invoice.

**Comment by uncheckederror** [comment]
@danry25 how do we use the payments webhook?

**Comment by danry25** [comment]
Closing per @uncheckederror , the only thing left is using the payments webhook to make the pizza tracker happy (and provide a followup list for our Sales and Support teams to get payment from).
