### ISSUE TITLE
[FEATURE] Add Price Override to Product Orders

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#304]
Jesse wanted to update the price of 2 phones in an invoice to lower their per unit cost from the retail price to the partner price. From inside of the Ops app he could not do this. Instead he had to manually change the invoice in invoice ninja. This is not ideal because now the pricing in invoice ninja doesn't match with the pricing we have in the Ops app and the totals shown on the orders page will not agree with the manually updated invoice.

If the total price of each Product Item attached to an order could be overridden with a single value in the Ops app this could help us keep the Invoice and the Orders page in sync by treating the Ops app as the source of truth for both.

**Comment by danry25** [comment]
Closing as won't fix
