### ISSUE TITLE
Add New Videos to Website

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#308]
New Videos are being uploaded to the YouTube Channel and need to be added to the website as well.

The following links need to be added to the website under a new support page for the GRP2612.
Single Press Transfer
https://www.youtube.com/watch?v=20xe0THrO_8
Change Ringtone
https://www.youtube.com/watch?v=5fZSm8ny83M
Reboot
https://www.youtube.com/watch?v=tvlZ9KTyYSk
Factory Reset
https://www.youtube.com/watch?v=hpHtXEFHq8Q
Check Voicemail
https://www.youtube.com/watch?v=uNtvgiUpjSc
Speed Dial
https://www.youtube.com/watch?v=upgNsE_ptqg
Put Call on Hold
https://www.youtube.com/watch?v=EKQRVcI2BoA
Use Call Park
https://www.youtube.com/watch?v=RuN8jvcsDOY

There will be more soon. The final format will follow the same as the GRP2615 page but without Bluetooth.

In addition there will also be more coming for Yealink headsets that will need to be added to the website and have their own support pages as well. I will update issue when they're available.

**Comment by Chattaeus** [comment]
Additional new links for new videos. New pages for Yealink WH62 headset and BH72 may need to be created. These links will work but the videos will release over the next few days. The last of which on Jan 3rd.

Add to Grandstream 2615 page:
https://www.youtube.com/watch?v=tfLYkx_3ULg

Add to Grandstream 2615 page:
https://www.youtube.com/watch?v=MyEPaO8eZfY

Add to new WH62 page:
https://www.youtube.com/watch?v=_lVy7zoi178

Add to new WH62 page:
https://www.youtube.com/watch?v=a74alKfpTLE

Add to new WH62 page:
https://www.youtube.com/watch?v=IQtWRpv3YA8

Add to both new WH62 and BH72 pages:
https://www.youtube.com/watch?v=fJFUmZ67ouk

**Comment by uncheckederror** [comment]
@danry25 I need a thumbnail image for the GRP2612 and all the bullet point text needs to be reviewed. The text for last 2 videos reboot and reset are wrong and need to replaced by a real list of steps.

https://acceleratenetworks.com/Phones/GRP2612

**Comment by Chattaeus** [comment]
@uncheckederror Here are the steps for rebooting and factory resetting Grandstreams. Written so you can use the same language on all models.

Steps to Reboot Grandstream
Press center “dot” key to bring up the menu.
Scroll over to and select Reboot in the menu.
Confirm with the under-screen keys.

Steps to Factory Reset Grandstream
Press center “dot” key to bring up the menu.
Scroll over to and select System in the menu.
Scroll down to and select Factory Reset, almost at the bottom.
Confirm with the under-screen keys.

**Comment by uncheckederror** [comment]
These changes are live.

Should we be ending these support pages with an buy-it-from-us pitch for the particular model of phone they're looking at?

**Comment by danry25** [comment]
Yes, lets do a footer that pitches buy it from us :D

**Comment by uncheckederror** [comment]
How about this?

![image](https://user-images.githubusercontent.com/11726956/214181707-c726cd4f-59f1-4f8c-8df4-b8a0d0d978dc.png)

**Comment by danry25** [comment]
@uncheckederror  I want something to fill the white space below Table of Contents (or another way to make it symmetrical in desktop view) and descriptive emojis (music, racecar, pause, etc) for each line on the Table of Contents.

@Chattaeus Not 100% sure on the wording, what were you thinking?

**Comment by Chattaeus** [comment]
IDK, something like this maybe?
"If you’d like to upgrade your company’s phones to (phone model) you can order from our website here(link) or call us for a free quote (phone number)."

**Comment by uncheckederror** [comment]
@danry25 How about this?

https://acceleratenetworks.com/Phones/GRP2612

**Comment by uncheckederror** [comment]
> Add to new WH62 page: https://www.youtube.com/watch?v=_lVy7zoi178
> 
> Add to new WH62 page: https://www.youtube.com/watch?v=a74alKfpTLE
> 
> Add to new WH62 page: https://www.youtube.com/watch?v=IQtWRpv3YA8
> 
> Add to both new WH62 and BH72 pages: https://www.youtube.com/watch?v=fJFUmZ67ouk

@Chattaeus We don't have support pages for the WH62 or BH72. The audio on the BH72 video is bad.

**Comment by danry25** [comment]
@uncheckederror Please fix up these things then close this issue.
- [ ] Add emojis and formatting for:
  - [ ] GXP2135
  - [ ] GXP2170
  - [ ] T54W
  - [ ] DP720
  - [ ] DP722
  - [ ] DP730

@Chattaeus We still need videos for:
- [ ] Grandstream
  - [ ] GXP2140
  - [ ] GRP2613
  - [ ] GRP2612W
  - [ ] GRP2624
  - [ ] GRP2616
  - [ ] WP820
  - [ ] Grandstream Switch
- [ ] Yealink Hardware
  - [ ] T57W
  - [ ] CP935 Series
  - [ ] Cordless Handsets
- [ ] FusionPBX Features
  - [ ] Forward Ring Group
  - [ ] Follow Me for Extension
  - [ ] Edit BLFs/Speed Dials then provision
    - [ ] On  a specific phone
    - [ ] On a profile
      - [ ] Add provision button on profile to provision all phones on profile @piajesse ?
  - [ ] Update voicemail's email address & password, toggle greetings, view voicemails
  - [ ] Change Time Conditions
     - [ ] Add holiday
     - [ ] Adjust business hours
  - [ ] Change Phone Number Routing (Dialplan => Destinations)
  - [ ] Change Ring Group
    - [ ] Ring Delays
    - [ ] Alternate Destinations
    - [ ] Adding a destination and deleting a destination
  - [ ] Update extension label
  - [ ] Create new FusionPBX User & Associate with extension & delete user
  - [ ] Send a Fax
  - [ ] Check phone status under Status => Registrations and Operator Panel
  - [ ] Retiring an extension
  - [ ] Android & iOS setup
     - [ ] Add Generate MAC address button in FusionPBX @piajesse ?

**Comment by piajesse** [comment]
Both “ Add provision button on profile to provision all phones on profile” and “Add Generate MAC address button in FusionPBX” should be separate issues on our fusionpbx repo @danry25

**Comment by uncheckederror** [comment]
> @uncheckederror Please fix up these things then close this issue.
> 
> * [x]  Add emojis and formatting for:

@danry25 these changes are live.
