### ISSUE TITLE
Messaging API Webhooks and deploying to a test enviroment

### ISSUE THREAD

**Issue by dunkeltron** [AccelerateNetworks/NumberSearch#309]
Followup to today's conference call where we mentioned adding inbound webhooks and endstream integration to the Messaging API.

also if we could go ahead and host the messaging API somewhere that'd make testing the feature much easier

**Comment by uncheckederror** [comment]
Adding the endstream docs here so we can keep track of everything: https://portal.1pcom.net/download/SMSAPI.pdf

**Comment by danry25** [comment]
We are pending Harel's response with working API credentials.

**Comment by uncheckederror** [comment]
When submitting requests to First Com we POST UrlEncoded parameters like the username, password, and messageBody rather than JSON. But the response will be in JSON in the format of 
```
{
    "response": {
        "code": 0,
        "developertext": "",
        "dlrid": "11111111",
        "subcode": 0,
        "text": "OK"
    }
}
```

**Comment by uncheckederror** [comment]
The Messaging [project is live](https://sms.callpipe.com/) although it does not work because I haven't provided the API keys in its configuration file.

**Comment by uncheckederror** [comment]
Working on adding JWT based authentication to the Messaging project where the existing Ops app which includes IdentityServer4 is the token authority.

**Comment by uncheckederror** [comment]
Alright, you can generate a token by using the /Token endpoint and providing the same credentials that you use to log into the Ops app. Then you can can copy paste the token into the prompt provided by the "Authorize" button on the top right side of the Swagger doc. It will then be included for each request you make from the swagger doc to try out the endpoints.

Only the /Message/Outbound/FirstPoint endpoint works at the moment.

The Swagger documentation is weak at the moment I need to finish filling it out with example requests and what not.

**Comment by danry25** [comment]
@dunkeltron @thefinn93 Can you add support for the /Message/Outbound/FirstPoint endpoint to OrgSMS?

**Comment by thefinn93** [comment]
How should OrgSMS be getting a token? It looks like it's a JWT that expires in 30 minutes, so we'll probably need some kind of machine credentials.

**Comment by thefinn93** [comment]
Or should we be prompting users for their ops credentials, caching them in orgsms and re-sending them to the API every time we need a new token?

**Comment by uncheckederror** [comment]
This app is up @ https://sms.callpipe.com/index.html and seems to be working okay.
