### ISSUE TITLE
Lookup - An error occured

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#310]
**Describe the bug**
I searched a number in Bulk Lookup and got the following error:
![image](https://user-images.githubusercontent.com/1683673/214978581-219360e8-0cd0-4683-bcc5-98fefafb5ceb.png)

**To Reproduce**
I have been unable to reproduce this bug.

URL affected: https://acceleratenetworks.com/Lookup/BulkPort?dialedNumber=206-526-2345%0D%0A

**Expected behavior**
The number should have been looked up and a result shown.

**Desktop (please complete the following information):**
 - OS: Debian 11 x86_64
 - Browser Firefox
 - Version 102.7.0esr (64-bit)

**Comment by uncheckederror** [comment]
@danry25 seems to work now. One of the vendor API must have been down. 😅

**Comment by uncheckederror** [comment]
From the logs:

`Call failed with status code 503 (Service Unavailable: Back-end server is at capacity): GET https://apiv1.teleapi.net/lnp/check/portable/bulk?token=...&numbers=[2065262345]`

**Comment by danry25** [comment]
Closing as we are migrating away from this failing endpoint on issue #311

**Comment by danry25** [comment]
Reopening as the issue appears to be affecting all phone numbers now: https://acceleratenetworks.com/Lookup/BulkPort?dialedNumber=2068588757

![image](https://user-images.githubusercontent.com/1683673/218968848-cf7d5f9a-fdc8-4e92-a6ed-d713b1f56090.png)

**Comment by uncheckederror** [comment]
From the log 
```
2023-02-13 00:50:53.760 -08:00 [INF] Request starting HTTP/1.1 GET http://acceleratenetworks.com/Lookup/BulkPort?dialedNumber=2063253722 - -
2023-02-13 00:50:54.437 -08:00 [ERR] HTTP GET /Lookup/BulkPort responded 500 in 676.4122 ms
Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: GET https://apiv1.teleapi.net/lnp/check/portable/bulk?token=...&numbers=&numbers=[2063253722] Newtonsoft.Json.JsonSerializationException: Error converting value "
```

**Comment by uncheckederror** [comment]
@danry25 this fix is live.

**Comment by danry25** [comment]
It seems to be working :D
