### ISSUE TITLE
MMS Sending Support for Endstream

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#311]
**Describe the issue**
Teli's platform is shutting down, we need to deprecate their API endpoints and  migrate our services to BulkVS, ThinQ and 1st Point (aka Endstream)'s APIs.

**To Do for Tom**
- [x] Route Toll Free port requests to BulkVS's [validatePortability](https://portal.bulkvs.com/api/v1.0/documentation#/LNP/get_validatePortability) and portTN endpoints
- [x] Remove dependence on Teli's LRN API
- [x] Shrink scope of number ingest on Teli
  - [x] Deprecate entirely once Teli end date set
- [x] Migrate off Teli's E911 API
- [x] Migrate texting off Teli & BulkVS to 1st Point (aka Endstream)'s APIs

**To Do for Dan**
- [x] Identify new E911 API to be used
- [x] Complete ThinQ (formerly Teli) and Skytel (formerly Call48) setup
- [x] Port Toll Free numbers off of Teli
- [x] Ensure all phone numbers are E911 registered on new platform
- [ ] Remove Teli-related inbound and outbound routing
- [x] Migrate SMS webhooks for Toll Free and Offnet numbers

**Expected behavior**
A seamless transition for our clients, with no downtime or errata in inbound calling or SMS. Once 1st Point SMS migration is complete, short code texting, group MMS and similar should also work much better than current Teli implementation.

**Comment by uncheckederror** [comment]
@danry25 BulkVS appears to offer E911 APIs using their /e911Record and /validateAddress endpoint. 

Weird things appear to be happening with the TeliMessage number ingest process. I am investigating, but perhaps we should disable it?

We have no dependencies on Teli's LRNLookup endpoint.

**Comment by uncheckederror** [comment]
```
2023-02-16 00:01:24.249 -08:00 [INF] Ingesting data from TeliMessage
2023-02-16 00:02:24.956 -08:00 [ERR] Call failed with status code 408 (REQUEST_TIMEOUT): GET https://apiv1.teleapi.net/dids/npas
2023-02-16 00:02:24.956 -08:00 [ERR] [TeliMessage] No NPAs Retrived.
2023-02-16 00:02:32.078 -08:00 [INF] [TeliMessage] Found 10 Tollfree Phone Numbers.
2023-02-16 00:02:32.079 -08:00 [INF] [TeliMessage] Found 10 Phone Numbers
```

Oh boy, there's a lot of stuff that is broken in the ingest process at the moment.

My recommendation is that we disable the large ingest from Teli and stick to just the priority and tollfree ingests.

**Comment by danry25** [comment]
Sounds good, let's scale Teli down to priority ingests only.

**Comment by uncheckederror** [comment]
> Sounds good, let's scale Teli down to priority ingests only.

this is live.

**Comment by danry25** [comment]
**Commio APIs of note**
- Search [Tollfree Numbers](https://apidocs.thinq.com/#5c087c67-28b9-494b-99e2-ff1afec86f71)
  - Only allows searching 100 numbers at a time, only covers 833 to 888 NPAs
- Search [Local Numbers](https://apidocs.thinq.com/#165bab51-f37b-464e-b501-e3e18603b295)
  - No ability to search for custom NPA-NXX-XXXX
  - No clear way to get list of NPA-NXXes available
- Both endpoints currently lack custom searches to find specific toll-free or local numbers
- No apparent pagination when there are more than 100 results for a query :c
-  Ordering DIDs is a two-step process. 
  - [Purchase the Individual Number](https://apidocs.thinq.com/#2f98c51b-1db6-4dc3-b883-6ad26a0e5c1c)
    - Submit this JSON replacing XXXXXXXXXX with the phone number
    `{
  "order": {
    "tns": [
		{
			"caller_id": null,
			"account_location_id": null,
			"sms_routing_profile_id": null,
			"route_id": 4798,
			"features": {
			  "cnam": true,
			  "sms": false,
			  "e911": false
			},
			"did": XXXXXXXXXX
		}
    ],
    "blocks": []
  }
}`
  - [Complete Order](https://apidocs.thinq.com/#f01bd6c2-16d3-4f5d-b3ca-54505378d768)

**Skyetel APIs of note**
- [Creaate Offnet Phone Number](https://api.docs.skyetel.com/#tag/Phonenumbers/operation/Create%20Off-Network%20Phonenumber)
  - Registering owned numbers with Skyetel through this endpoint will give us an A attestation when routing via Skyetel for all outbound calls from valid numbers.
- [Find Available Phone Numbers](https://api.docs.skyetel.com/#tag/Phonenumbers/operation/Find%20Available%20Phonenumbers)
  - Supports Local and Toll Free (833 to 888)
  - [Order Phone Numbers](https://api.docs.skyetel.com/#tag/Phonenumbers/operation/Order%20Phonenumbers) to purchase
  - No apparent pagination when there are more than 100 results for a query :c
  - Custom search is supported with wildcards, does not work on website.

**Comment by danry25** [comment]
For E911 we need to access https://portal.bulkvs.com/api/v1.0/documentation#/E911/post_validateAddress perhaps when we save any address into an order, then hit https://portal.bulkvs.com/api/v1.0/documentation#/E911/post_e911Record to create the E911 registration when the Register for E911 button is pressed in Ops.

**Comment by danry25** [comment]
In Owned Numbers inside Ops it would be great to:
- Update ownership status (Underlying carrier & vendor)
- View and update a numbers E911 Registration
- Enable/Disable SMS
- Show if routed in FusionPBX

**Comment by uncheckederror** [comment]
The Register for E911 Service button the Order Editing page should work again now.

**Comment by thefinn93** [comment]
[API docs](https://github.com/AccelerateNetworks/fusionpbx-rest-api#use) such as they are. You'll want the `destination-details` action to see if a given number is routed in FusionPBX. This isn't deployed to prod just yet, but I can get you API keys and an for the test instance. Planning on deploying to prod next time I'm thinking about this outside of business hours.

**Comment by danry25** [comment]
@uncheckederror When I attempt to access https://ops.acceleratenetworks.com/Home/EmergencyInformation/2068589313 by going to Owned Numbers then clicking on Emergency I get a blank page.

Additionally if the Emergency button is hollow (not solid blue), I can't enter an E911 address for a given phone number.

**Comment by danry25** [comment]
@uncheckederror Can you add an endpoint that hits DIDSMSEnable to board a number for SMS, then tries to set EPID 265 every 30 minutes using DIDRouteSMSToEPIDBasic until its successful so its routed to sms.callpipe.com? That way we can onboard numbers to this platform :D

**Comment by danry25** [comment]
To Do for @danry25 
- [ ] Update E911 Registrations for RC to send SMS notifications
- [ ] Remove Teli inbound/outbound routing from FusionPBX
- [ ] Ensure Commio migrates Toll Free numbers to LCR
- [ ] Fill out form to board toll free number on 1st Point SMS/MMS
- [ ] Cancel unused 10DLC campaigns migrated to Commio
- [ ] Add Commio to outbound call routing

To Do for @uncheckederror
- [ ] Update Owned Numbers to reflect numbers migrated to BulkVS
- [ ] Add MMS support for 1st Point
- [ ]

**Comment by uncheckederror** [comment]
The Messaging API hosted at https://sms.callpipe.com/index.html now supports sending outbound MMS messages via the /message/send endpoint. To send an MMS message supply a URL to a downloadable file like a .txt or a .jpg in the MediaURLs array. If there are any values in the MediaURLs array the Message field will be ignored.

If you want the MMS to include a text message in the form of a .txt file you'll need to also include a .smil file to define the layout of the message. If you have questions or bugs please make a comment here. @danry25 @thefinn93

**Comment by uncheckederror** [comment]
Closing this out as I've broken the remaining work out into separate issues.
