### ISSUE TITLE
Order for only a service does not display invoice, creates duplicate recurring invoices

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#312]
**Describe the bug**
Customer submits order for 5G Internet with Static IP, gets black screen after submitting order, billing system shows 2 drafted recurring invoices.

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/Order/a13c57fe-5677-45e7-92dc-82829ebbbfba
2. See lack of any invoices being associated with order
3. Head to billing.acceleratenetworks.com and search for the client
4. Go to Recurring Invoices, see error where 2 drafted recurring invoices exist

**Expected behavior**
One Recurring Invoice should have been created with a start date of a month from the order date (and put into pending status with autobill set), and a normal invoice should be created to show the user immediately.

**Comment by uncheckederror** [comment]
> JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'NumberSearch.DataAccess.InvoiceNinja.ReccurringInvoiceDatum[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
> To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
> Path 'data.id', line 3, position 13.
> 
> FlurlParsingException: Response could not be deserialized to JSON: POST https://billing.acceleratenetworks.com/api/v1/recurring_invoices

This the error produced when we try to checkout with 5G Static IP on localhost.

**Comment by uncheckederror** [comment]
This fix is live. @danry25 please confirm the fix.

**Comment by danry25** [comment]
No invoice was generated in InvoiceNinja when testing on order https://ops.acceleratenetworks.com/Home/Order/a63dac1c-e72c-4327-a822-d469cece48df, just a recurring invoice still in Draft status (not pending).

**Comment by uncheckederror** [comment]
> No invoice was generated in InvoiceNinja when testing on order https://ops.acceleratenetworks.com/Home/Order/a63dac1c-e72c-4327-a822-d469cece48df, just a recurring invoice still in Draft status (not pending).

What do you expect to see in InvoiceNinja? 5G with Static IP is listed in the Mvc app as a monthly (reoccurring) service.

**Comment by danry25** [comment]
There should be a one time invoice generated for todays date that is shown to the end user, and the monthly (reoccuring) service invoice should be set to start 28 days in the future, with a status of Pending instead of draft

**Comment by uncheckederror** [comment]
What would be in the upfront invoice? How do we set a reoccuring invoice to start 28 days in the future with a status of pending?

**Comment by danry25** [comment]
The upfront invoice should be generated only if an order is placed that only contains services (reoccuring items we bill for).

You can set the date an invoice should start billing by setting next_send_date with a value like 2023-02-09 00:00:00

Make sure auto_bill is set to opt_out (that way we automatically bill their payment method on file) and status_id to 2 (so the Recurring Invoice has a status of Pending rather than Draft).

**Comment by uncheckederror** [comment]
@danry25 this change is live, please verify it works.

**Comment by danry25** [comment]
This issue is resolved
