### ISSUE TITLE
Ops - Regenerate Invoices creating duplicate quotes

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#313]
**Describe the bug**
When the Regenerate Invoices button is pressed on a quote with recurring and upfront invoices, 2 additional duplicate quotes are generated and the original quotes are not update. Both duplicate quotes are for the reoccuring quote, not for the upfront quote.

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/Order/3f5a5ed2-6137-46f6-812f-426dc739cfad
2. Click on Regenerate Invoices
3. Head to the billing system and look up client
4. See erroneous duplicate quotes under the Quotes section

**Expected behavior**
The original upfront and monthly quotes should be updated to reflect the additional services and upfront fees added to the order in Ops.

**Comment by uncheckederror** [comment]
@danry25 okay try regenerating this quote now, I think it works.

**Comment by danry25** [comment]
Quote regeneration does work :D
