### ISSUE TITLE
Add "AN-Mobile" to the phones section

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#316]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Advertising our app might be nice for users who don't want to pay for phones, or to replace all our "follow me" based users. It would also be helpful to point to this page within the app, playstore, etc, instead of the general Linphone app.

**Is your feature request related to a problem? Please describe.**
Our Linphone fork AN-Mobile hasn't existed on our site because its been true beta quality. while its still not perfect, its gotten better in the last couple weeks, to a point where we should start advertising it as a feature.

**Describe the solution you'd like**
Add a device called "AN-Mobile" and have @Chattaeus make some video on how to set it up and use some of its features including:
- [ ] Setup an account within Fusion PBX for the phone (This is dependent on @piajesse finishing up the provisioning system for linphone within FusionPBX).
- [ ] Place a call to 425 499 7999
- [ ] How to use the hold function.
- [ ] How to transfer calls within the app.

**Comment by danry25** [comment]
To setup Accelerate Networks Mobile, go to the [Apple App Store](https://apps.apple.com/us/app/accelerate-networks-mobile/id1560522124) for iPhone or [Google Play Store](https://play.google.com/store/apps/details?id=com.acceleratenetworks.mobile) on Android to install the app*.

Open Accelerate Networks Mobile once installed, allowing notifications, camera, microphone, calls and location permissions**. Agree to the terms then press Continue, press QRCode to scan the configuration QR Code or paste the URL (available in the organization's FusionPBX portal*** under Applications => Linphone), press Fetch and Apply, then place a test call by dialing 425-499-7999 which will play music.

Troubleshooting
If you run into any issues, head to the quadruple bar (upper left) => Settings => Advanced and toggle Debug Logs on, press the back arrow twice, recreate the issue that occurred in the app, head back into the quadruple bar => Settings => Advanced and pick Send Logs, describe what happened (Example: I was on the phone with X and Y thing happened) and email this to [support@acceleratenetworks.com](mailto:support@acceleratenetworks.com).

Notes:
\* Installation requires administrator access on the smartphone (iCloud or Google Account access), please contact IT if you do not have administrator access on the computer you are using. Accelerate Networks does not have administrator access to phones and does not offer general iOS or Android IT services.
 
If the Android device does not have Google Play, [download the .apk file here](https://git.callpipe.com/AccelerateNetworks/an-mobile-android/-/jobs) by clicking on the top Passed ✔️ job, then click Browse under Job artifacts on the right hand sidebar and download the file which has a tile beginning with "linphone-android-release" and ends in .apk

** All permissions except Contacts need to be granted for Accelerate Networks Mobile need to be granted for the app to function. 

Our app is open source software that does not use your contacts, files, data, location unless it is directly beneficial to serving you, the end user. Our [iOS](https://github.com/AccelerateNetworks/an-mobile-ios) and [Android](https://github.com/AccelerateNetworks/an-mobile-android) code are public so you can tell exactly what the app does. 

We appreciate you granting us these permissions and we do not use these permissions when not needed to help you!

*** Need help? Call or text 206-858-8757 or email [support@acceleratenetworks.com](mailto:support@acceleratenetworks.com) and we can help you access the FusionPBX portal. Do not go to FusionPBX.com, this will not direct to the organization's FusionPBX portal.

**Comment by uncheckederror** [comment]
@danry25 please add this as an item on the hardware page.
