### ISSUE TITLE
Create Individual Pages for Phones and Accessories

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#318]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
We want to improve the experience for customers of getting linked to a specific product to buy on our website. This will make it easier to help customers expand their use of our services by purchasing additional hardware after the initial install is completed.

**Is your feature request related to a problem? Please describe.**
Right now you can directly link to phones, but you cannot directly link to accessories. This makes it difficult to direct customer to specific headsets that the sales team is recommending that they purchase.

**Describe the solution you'd like**
We need to revamp the hardware page to a search/filtering feature and to add individual pages for each product displayed on the page so that we can provided more detail on them and link directly to them. We want to avoid redirecting the customer to the hardware vendor's website so that we can keep their focus on our services.

**Describe alternatives you've considered**
The current system could stay the same, but it doesn't mirror the way that other website work which creates an expectations problem.

The requirements for this feature are based on feedback from @scottstrong206 and @Chattaeus in this afternoon's meeting.

**Comment by uncheckederror** [comment]
@danry25 this issue covers directly linking to accessories on the website.

**Comment by uncheckederror** [comment]
@danry25 @scottstrong206 @Chattaeus the initial version is live. Let's hear your notes!

**Comment by uncheckederror** [comment]
Did a call with @Chattaeus to collect feedback on the new hardware item pages and the existing support pages. Based on our conversation:

- [ ] Support page for the T57W should link to T54W until it's page is done.
- [ ] Pages for the GRP2613 and GRP2624 should link to the GRP2615 until their pages are done.

**Comment by uncheckederror** [comment]
@scottstrong206 @danry25 please leave your feedback on the new hardware pages here.

**Comment by uncheckederror** [comment]
@scottstrong206 @danry25 please leave your feedback on the new hardware pages here.

**Comment by danry25** [comment]
Issues with current format:
- Images got compressed/Height/Width ratio is skewed on GRP2615, GRP2613, CP935W and other images
- Please fix image disparity between DP722 and DP730 (722 image is much larger).
- Please center phone images by removing cord from photo. See GXP2170, GXP2135 image.  
- Call to Action of "Buy Now" is missing, not pushing customers to buy our hardware
- More Info changed behavior unexpectedly, used to link to support page, now links to (often empty) info page on device?
  - Add Tutorials button that links to support page to Item Card on hardware page?
- Add Top Seller banner or emojis to items to highlight an items popularity
- If Support or Hardware page is not filled out, do not show More Info button on Hardware page

**Comment by uncheckederror** [comment]
@danry25 there is no "More Info" button. Can you be specific?

**Comment by danry25** [comment]
Sorry, I was referring to Learn More when saying More Info.

What Scott and I would like to see is a Buy Now button with quantity field, Learn More (which only shows up if the /Hardware/ModelNumber page exists) and Tutorials Button (which should only show up if the item's SupportLink is filled out in Ops linking to a /Phones/ModelNumber page).

Clicking on the card itself should take no action, but clicking on the item's picture should take you to the the /Hardware/ModelNumber page if it exists, otherwise it should take you to the SupportLink

**Comment by uncheckederror** [comment]
The whole card is clickable, so we can't have any text input fields on the card.

**Comment by uncheckederror** [comment]
For reference this is the experience that customers will expect when they use the hardware page: https://www.amazon.com/s?k=desk+phones&crid=VXCM30965DVU&sprefix=desk+phone%2Caps%2C164&ref=nb_sb_noss_1

**Comment by uncheckederror** [comment]
Our page has some advantages like no ads, greater density, and less visual noise. But it works the same way as the Amazon page.

**Comment by danry25** [comment]
We do not have the breadth of Amazon's inventory to sell, and many competitors UXes include an immediate way to add to cart or checkout with a single click from said search page, like on https://www.fredmeyer.com/search?query=pepsi%20nitro&searchType=default_search

**Comment by uncheckederror** [comment]
That was the argument for not having individual product pages, but the requirements have expanded which is why we updated our UX to include individual product pages hence the existence of this issue and the work I've done in support of it.

The page you've linked requires creating an registering for an account. You cannot directly add items to your cart until you've completed that loop, our system is faster and does not require this step.

Grandstream's own UX works the same way ours does, but a bit worse: https://www.grandstream.com/products/ip-voice-telephony/carrier-grade-ip-phones/grp-series-professional-ip-phones and TeleDynamics is again similar: https://www.teledynamics.com/#/catalog/category/VOIP_and_UC/SIP_Phones

If I add two buttons and an input field to each of the cards on the hardware and accessors page I can't guarantee that the heights of the cards will match, so their appearance will go back to being non-uniform in height which was one of Scott's requirements.

**Comment by uncheckederror** [comment]
> Looking in the Firefox inspector/debugger, the current cards have the images set to be 348px by 390px despite a source image that is 400px by 400px, resulting in the distortion obsserved @uncheckederror

This is a consequence of the responsive layout. The images are scaled down as the screen width decreases before we start reducing the number of columns in the layout.

**Comment by danry25** [comment]
The aspect ratio of the pictures needs to be maintained at a 1 to 1 ratio to avoid image distortion.

>The page you've linked requires creating an registering for an account. You cannot directly add items to your cart until you've completed that loop, our system is faster and does not require this step.

Take a look at Newegg then, you can add to cart right from their search page or any page listing the products in a category: https://www.newegg.com/p/pl?d=headset

Grandstream is not a good example since they never directly sell hardware, and TeleDynamics is registered, Business to Business sales only, and ended direct to consumer sales years ago.

>If I add two buttons and an input field to each of the cards on the hardware and accessors page I can't guarantee that the heights of the cards will match, so their appearance will go back to being non-uniform in height which was one of Scott's requirements.

Is it just the text description below an item that could make this non-uniform? If so, we can just have a target length for descriptions.

**Comment by uncheckederror** [comment]
@danry25 try it now

**Comment by danry25** [comment]
Looking better! Could we align the price, learn more, quantity and Buy Now buttons onto one line perchance?
![image](https://user-images.githubusercontent.com/1683673/228146516-0dc5c246-b7e2-4aa1-8454-f0af0bf1034d.png)

On the Hardware page, it would be ideal to put the price, quantity and Buy Now buttons onto one line as well.
![image](https://user-images.githubusercontent.com/1683673/228148998-362b82d8-2d8a-45da-9c0b-36661a089130.png)

The images of each product also need some TLC since 400 pixels appears to be a bit small for the Hardware page (showing 538px in a 1 to 1 ratio now) and some images (GRP2613 and GRP2615 compared to how nice the GRP2670 looks) aren't scaling down to 348px from 400px very well.

I think we should be targeting a higher resolution so these can be scaled more gracefully, any input on this? Images should also have consistent sizing, the handset you pick up from the phone across the GRP series and T5 series should be a consistent size, yet the handsets appear to be different sizes for each model. The handset should be our Banana :banana:  for scale?

**Comment by danry25** [comment]
@uncheckederror We are seeing significant customer confusion when clients see "⌛ Coming soon. If you need details now, call (206) 333-3341!", can we please not show the /Hardware/Model page when the feature and flavor text has not been filled in?

2 sales lost or delayed so far due to this particular issue.

**Comment by uncheckederror** [comment]
> @uncheckederror We are seeing significant customer confusion when clients see "⌛ Coming soon. If you need details now, call (206) 333-3341!", can we please not show the /Hardware/Model page when the feature and flavor text has not been filled in?
> 
> 
> 
> 2 sales lost or delayed so far due to this particular issue.

Okay interesting, so do you want me to not generate the device specific pages where the flavor text hasn't been filled out or to you just want me to break the links from the all hardware page and leave the individual pages alone?

**Comment by danry25** [comment]
@uncheckederror You stated the answer to this problem:

> do you want me to not generate the device specific pages where the flavor text hasn't been filled out

But then suggested breaking all the links. Why? How is breaking all the links a reasonable idea?

>or to you just want me to break the links from the all hardware page and leave the individual pages alone?

**Comment by uncheckederror** [comment]
If we don't generate the device specific pages, then you can't link to them directly. So https://acceleratenetworks.com/Hardware/GXP2160 for example would become a 404 until you filled out the content.

**Comment by danry25** [comment]
To recap, we are left with:
[ ] Getting product images displayed with a 1 to 1 ratio
[ ] Updating product images to Webpage format, assigned to @danry25 

Product Images ToDo
- Please fix image disparity between DP722 and DP730 (722 image is much larger).
- Please center phone images by removing cord from photo. See GXP2170, GXP2135 image.
- Add Top Seller banner or emojis to items to highlight an items popularity

**Comment by uncheckederror** [comment]
On my machine images are being displayed with a 1:1 aspect ratio on the Hardware page.

![image](https://user-images.githubusercontent.com/11726956/231542496-d185c17f-01fd-4b5b-b424-f49d6ed8adb8.png)

Where the image reports that it's intrinsic aspect ratio and it's rendered aspect ratio are both 1:1.

The bootstrap cards will scale the image up or down in resolution depending on the amount of space available in the layout. With the current layout that means that images have a maximum size of 348 by 348 pixels.

But if we expand the layout to include the full screen width by replacing the "container" CSS class with "container-fluid" the images are scaled up to a resolution of 794 by 794 pixels. Ideally we the images would be sized so that they can be down sampled from a higher resolution, rather than up-sampled from a lower resolution.

![image](https://user-images.githubusercontent.com/11726956/231543914-816a17fa-b3f9-40ba-8887-63791f1235e7.png)

Another way to get higher resolution images would be to change the layout of the page from three columns to two columns. Which gives us an image size of 538 by 538 pixels.

![image](https://user-images.githubusercontent.com/11726956/231545562-c7321581-3dd6-43dc-931e-a5be4aac095d.png)

Distortions of the images outside of this responsive scaling process are not from the Mvc app but rather the source images themselves.

The preferred format for images is now .webp rather than .jpeg or .png because it's faster for browsers to decode, scale, and it offers a better compression ratio that either of those two formats.

@danry25 How exactly do you think we could regularize the relative sizing of the source images? All of the images we currently use are directly from the vendor's media materials.

**Comment by danry25** [comment]
Its on me (or another support team member) to do some image cleanup to regularize these images @uncheckederror 

Will work on this and provide you new assets that are scaled consistently and exclude handset cords. Thinking we should target a larger size like 1200x1200 or 794 by 794 pixels in webp format so the images look good on both the hardware page and on the individual product page.

The ratio appears to be 348x348 on the main hardware page and 538x538 on specific hardware pages for me in Firefox now, so we don't have a ratio issue.
