### ISSUE TITLE
Cannot link to items in accessories tab

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#320]
**Describe the bug**
There seems to be no way to link to a specific accessory from a URL. https://acceleratenetworks.com/Hardware is the closest you can get.

**Expected behavior**
Linking a customer to https://acceleratenetworks.com/Hardware#AwesomeHeadset should take the customer to the awesome headset under the accessories tab.

**Comment by uncheckederror** [comment]
I believe this is a duplicate of #318.
