### ISSUE TITLE
Add a Support Page for Linphone

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/NumberSearch#321]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This will let us make clearer self-service guides, reducing chance of customers needing to contact support.

**Describe the solution you'd like**
markdown support with attachments, like what GitHub has for issues. a WYSIWYG editor (again, with image attachment support) would also be perfectly acceptable.

**Comment by uncheckederror** [comment]
The self-service support guides that we have are only updated when Thaddaeus or Dan provide content. The limiting factor is not the tooling, but rather their motivation to write, take photos, or film videos. Cloning Github's editor while cool, doesn't solve that problem.

We actually had a CMS for the support pages up until the middle of last year??? but it broke at some point and the content was rarely updated do to a lack of motivation. Over the past few months we've been building out this format of [support page.](https://acceleratenetworks.com/Phones/GRP2615) And it's gone through considerable changes as Thaddeus has provided more videos and Dan has provided feedback.

If you have specific changes or feedback on the formatting or content of the support pages, or perhaps ideas for new ones (FusionPBX setup?) I'd love to hear it.

**Comment by thefinn93** [comment]
I was specifically trying to add a Linphone hardware page with install and configuration instructions for Linphone Desktop. Lots of the steps could be clearer if I could include images.

**Comment by uncheckederror** [comment]
Okay, so if you want to provide the content in this issue, via email, or in a PR all of those work good for me.
 
Images live in this folder as statics assets: https://github.com/AccelerateNetworks/NumberSearch/tree/master/NumberSearch.Mvc/wwwroot/images/original

Or if you prefer, you can link/paste them into this issue and I'll get them into the project.

**Comment by danry25** [comment]
@thefinn93 I recall us discussing that you had written content for this a few months ago (Linphone Desktop installation, Provisioning and Contacts Provisioning), but it doesn't appear this issue contains this content.

Can we start with a written form and add images when the platform supports it?

**Comment by danry25** [comment]
To setup Linphone Desktop, download Linphone for [Windows](https://linphone.org/releases/windows/latest_app_win64), [MacOS](https://linphone.org/releases/macosx/latest_app) or [Linux](https://linphone.org/releases/linux/latest_app) and install Linphone using the file downloaded*.

Open the Linphone Desktop application once installed, allowing private and public network access if prompted. Choose Fetch Remote Configuration, and fill in the Provisioning URL (available in the organization's FusionPBX portal** under Applications => Linphone), press Fetch and Apply, then click on the dialpad to the right of the search field to dial 425-499-7999 which will play music. 

If the ring group 

* Installation requires administrator access on the computer, please contact IT if you do not have administrator access on the computer you are using. Accelerate Networks does not have administrator access to computers and does not offer general Windows or MacOS IT services .

** Need help? Call or text 206-858-8757 or email support@acceleratenetworks.com and we can help you access the FusionPBX portal. **Do not go to FusionPBX.com**, this will not direct to the organization's FusionPBX portal.

**Comment by uncheckederror** [comment]
You can see a draft of the Linphone Desktop page here: https://acceleratenetworks.com/Phones/Linphone

**Comment by danry25** [comment]
Could we swap out the image for something like this which shows a bit of the Linphone Desktop 🖥️ UI https://new.linphone.org/sites/all/themes/simple/images/footerlaptop.png

**Comment by uncheckederror** [comment]
@danry25 please add this as an item on the hardware page.

**Comment by danry25** [comment]
Added, closing issue.
