### ISSUE TITLE
Enable E911 Registration through the Owned Numbers page

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#325]
The owned numbers page exists to show the status of all the number on our network.

Owned numbers are ingested from our vendors (FirstPointCom, BulkVS) by calling their APIs.

Numbers will have one of four possible status: Porting In, Porting Out, Cancelled, Active.

On a regular basis the numbers on this page will be reingested from our vendors and their statuses updated on the owned numbers page.

If a number is ingested it is marked as Active. If it is not reingested then it is marked as Cancelled. If there is an open port request in our system for this number then we mark it as Porting In. To set the Porting Out status the number will first show as Cancelled and then we'll need a checkbox to mark it as a number that is ported out.

We want to show the status of the number, which client in FusionPBX the number is related to, the E911 address registered for this number, the client that it's related to in the billing system, sms enablement status and a button to trigger the workflow for that number. Show the Port Out pin, and a button to update it to something else for BulkVS numbers.

From Dan:
- Show current number status (Porting in, Active, Porting Out, Cancelled) and vendor (BulkVS, Endstream, Peerless, ThinQ)
- Link to domain that phone number is routed on in FusionPBX
- Manage E911 registration

**Comment by uncheckederror** [comment]
The existing billingIds for owned numbers are invalid because they are from the old billing system and link to no where in the new billing system.

**Comment by uncheckederror** [comment]
If an Owned Number is ingested and a matching ported numbers is found, but there is no value for "RequestStatus" set, the number should not be set to a Status of "Porting In" rather it should just be "Active."

**Comment by danry25** [comment]
> If an Owned Number is ingested and a matching ported numbers is found, but there is no value for "RequestStatus" set, the number should not be set to a Status of "Porting In" rather it should just be "Active."

This assumption is not quite right, BulkVS adds numbers to our account prior to the port completing in case the losing carrier slams the number over to us early, and so we can start making outbound calls with a STIR/Shaken attestation of A immediately.

We should wait till the port request is marked as complete or the OCN/SPID of the number changes to add it to our Owned Numbers list, and we should also have a whitelist of OCNs that our numbers are expected to be on.

**Comment by uncheckederror** [comment]
If BulkVS has it registered on our account it will be ingested as an Owned Number. Older numbers that we have Porting records for may not have a RequestStatus value. Initially they were all marked as "Porting In" even though they are not porting in, rather they are just regular active numbers. If the port request had just been submitted to BulkVS then numbers would have a RequestStatus of SUBMITTED so they would still be marked as "Porting In". We mark them as active if we can find either a port request with a blank or null RequestStatus or if its value is COMPLETE, otherwise we mark it as "Porting In". If we can't find a port request for the number we just mark it as Active.

I have given up and now I am just going to make a diagram so that we can agree on the workflow:
![ownednumberstatus](https://user-images.githubusercontent.com/11726956/235572052-66bb9a01-7e5d-4398-98ca-29c02f3442e9.jpg)

**Comment by uncheckederror** [comment]
I am noticing that some numbers from BulkVS are getting marked as Cancelled when it might be that they are not cancelled, but rather just that we weren't able to ingest them from BulkVS's API on the last couple of passes.

**Comment by uncheckederror** [comment]
Based on the dialed number I would like create a link into FusionPBX so that when you look up an Owned Number in Ops we can bump you out into the FusionPBX client related to that phone number. @thefinn93 would this be a use case for your new API?

**Comment by thefinn93** [comment]
Yep. You can use the `destination-details` endpoint to get the FusionPBX domain and uuid associated with an inbound number. I'll send you more details tomorrow.

**Comment by thefinn93** [comment]
So when you call `destination-details`, it should give you a `destination_uuid` and a `domain_uuid` (among other things. You will probably want to start tracking the `domain_uuid` mappings on your side, since FusionPBX makes use of them a lot and most endpoints require providing one. You can use the `domain-details` endpoint to convert the domain UUID into a domain name.

Once you have the domain name and destination UUID, the URL for a given destination is:

`https://{domain_name}/app/destinations/destination_edit.php?id={destination_uuid}`

**Comment by uncheckederror** [comment]
The current system for editing the Notes on Owned Numbers in the Ops app is awkward as when you edit a number you lose your place in on the big list of numbers. In line editing of rows or a pop up for editing a row that does not force you to leave your place on the page would be ideal based on feedback from @Chattaeus.

**Comment by uncheckederror** [comment]
Based on @danry25 feedback on the new Ops build we are done with this issue.
