### ISSUE TITLE
[FEATURE] Notify on Payment method attachment

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#327]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
We can prevent revenue fallthrough and increase new customer happiness by more tightly managing our quotes, letting the agent assigned to an order and orders@acceleratenetworks.com know when a quote is approved or a payment issue occurs.

**Is your feature request related to a problem? Please describe.**
We are seeing customers get quoted through AccelerateNetworks.com, sit on the quote for a few days or weeks, then approve and pay the quote in InvoiceNinja. Our sales and support teams are unaware of the quote approval or payment occurring, resulting in significant delays to installing their new service.

Payment issues have also cropped up, with Stripe saying the only way to be notified when a payment attempt fails is by listening to charge.failed or payment_intent.payment_failed failed event via webhooks:
https://stripe.com/docs/api/events/types#event_types-charge.failed
https://stripe.com/docs/api/events/types#event_types-payment_intent.payment_failed
https://stripe.com/docs/webhooks 

**Describe the solution you'd like**
Send an email to the agent on the quote and to orders@acceleratenetworks.com when each of the following occurs:
- Quote is approved and converted to invoice in InvoiceNinja
  - Also toggle the quote to be an order in Ops
- Invoice associated to a quote is paid in InvoiceNinja
- Stripe Webhook says payment failed

**Describe alternatives you've considered**
InvoiceNinja v4 used to email @scottstrong206 or myself depending on who generated the quote when said quote was approved or if the associated invoice was paid, but when generating quotes via API there is no alert when a quote becomes an invoice, or when that invoice is paid.

**Additional context**

**Comment by danry25** [comment]
We need to check each quote once an hour to see if the quote has a status of "Converted". If a quote is converted it will also list the new Invoice that was generated from the quote. Send an email to the agent on the quote and to [orders@acceleratenetworks.com](mailto:orders@acceleratenetworks.com) when this occurs

**Comment by uncheckederror** [comment]
This check is part of the priority ingest process and will run every half hour to look for Quotes in Mvc with upfront invoices in InvoiceNinja that have been converted to Invoices. If it finds one, it will update the Quote to an Order in Mvc and update the id of the upfront invoice and invoice links it will also send out an email to orders and the sales rep notifying them.

**Comment by uncheckederror** [comment]
Need to add a step for quotes to the pizza tracker for showing the quote has been approved.

**Comment by sewcialite** [comment]
It it possible to only receive an email about an order once it has been paid and is actionable by the support team?

**Comment by uncheckederror** [comment]
> It it possible to only receive an email about an order once it has been paid and is actionable by the support team?

Yes, it is. I will add invoice payment notifications to the process that notifies us of conversions from Quotes to Invoices in the billing system.

**Comment by uncheckederror** [comment]
Alright everything in this feature request is implemented and appears to be working. Except that we are not validating the payments with Stripe. I haven't implemented that check as I'm not really sure what the work flow would be for that process. 

Perhaps we could setup a listener for that webhook that would fire off an email to support to investigate the payment failure? If we get a failure notification from Stripe, what would we do with it? Who would fix it @danry25?

**Comment by danry25** [comment]
Could payment failures be emailed to support?

Ideally support would review the payment methods on file, remove the problematic payment method, re attempt processing payment with another payment method on file, and failing that contact the customer to add a valid payment method.

**Comment by uncheckederror** [comment]
Yeah, that really the only potentially viable workflow that I see here. Given that the rest of this work is done I am going to break this out into a separate issue and close this one.
