### ISSUE TITLE
Ops - Lookups, setting CarrierID on a lookup does not work

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#329]
**Describe the bug**
Going to Lookups, selecting an unidentified lookup and choosing a CarrierID does not appear to do anything. Likely related to #328 and the missing jQuery library that Ops tries to load

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Lookups/Edit/7cc81653-d6e3-43c6-8aa9-ac45a82e93ed
2. Click on CarrierID and select a carrier
3. Scroll down to Save and click the button

**Expected behavior**
Pressing Save should create a new carrier by copying the name, image URL, etc and just updating the SPID or OCN to what was shown on said number lookup.

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser Firefox and Chrome
 - Version Firefox 102esr, Nightly, and Chrome (current version)

**Additional context**
jQuery seems to be 404ing, perhaps this is related to the issue:
![image](https://user-images.githubusercontent.com/1683673/235344594-940f9925-b206-4462-bd60-13e6b2513576.png)

Examples:
https://ops.acceleratenetworks.com/lib/jquery-validation/dist/jquery.validate.min.js
https://ops.acceleratenetworks.com/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js

**Comment by uncheckederror** [comment]
@danry25 I have published a new build of the Ops app that I believe resolves these issues with saving an updated Lookup or Carrier record. Please retest to verify the fix.

**Comment by danry25** [comment]
Using CarrierID on a number in Lookups to create a new carrier doesn't appear to create a visible carrier in https://ops.acceleratenetworks.com/Carriers from my testing. I tried to resolve all the Oregon and Massachusetts Level 3 labeled lookups (as they are supposed to be labeled Lumen), but every time I select the carrier ID and save, that specific lookup disappears, but none of the other numbers with the same OCN and SPID disappear from lookups even if I do a hard page reload.

**Comment by uncheckederror** [comment]
Hmm, I think it might only be trying to attach lookups to carriers when a new carrier is created. I have update the process so that it will look through all the existing carriers to match them to the lookup OCNs when you initially load the lookups page and if you update a single lookup record with a carrier it will now find all the lookups with a matching OCN and also add that carrier to them. Please try it out again.

**Comment by uncheckederror** [comment]
I need to add a blub on the lookups page describing the workflow for creating Carrier entries from raw lookup records to prevent confusion on how to use both the Lookups and Carriers pages.

**Comment by uncheckederror** [comment]
I have added instructions and descriptions to the Lookups page and resolved the 404'ing scripts @danry25.

**Comment by uncheckederror** [comment]
![Lookups and Carriers](https://user-images.githubusercontent.com/11726956/235809922-55251e2a-b8ae-4b65-889c-c6091a10f817.jpg)
Here's the workflow as I understand it.

**Comment by danry25** [comment]
Closing as we have removed CarrierID
