### ISSUE TITLE
Check incoming secret in request body instead of query param

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/NumberSearch#330]
1. Please check the `serversecret` part of the request body for incoming SMS/MMS webhooks from 1pcom instead of the one we added to the query parameter of the request. please try to avoid committing the production secret, ideally use a different secret in test environments.
2. [the old incoming secret has been committed](https://github.com/AccelerateNetworks/NumberSearch/blob/e3c8f966dbc2c336c27f2a94ac2003400e5d55fc/Messaging/Program.cs#LL662C27-L662C57) and can no longer be assumed secret. We can go ahead and stop checking that now.

**Comment by uncheckederror** [comment]
I have removed the hardcoded token validation and replaced with a secret configuration key. The serversecret part of the request body seems to change on a regular basis, but I don't have a way to keep track of the current secret we are expecting to see or a way to ask the vendor for the current secret they are intending to send. They set and supply it to us, hence why we are not currently validating it. I believe the specific values are something that @danry25 negotiates with the vendor.

I have written code to validate both the URL token parameter, which is active and code to validate the serversecret but I have left the serversecret validation disabled until we can work with the vendor to understand their rotation schedule and come up with a method to verify the current serversecret.

If the token parameter were to get rotated right now it would break the Messaging API until we could update the configuration secret in the pipeline and redeploy it.

In sum, while this is a smart goal, we're not quite there yet.

**Comment by thefinn93** [comment]
> The serversecret part of the request body seems to change on a regular basis

well that sucks

> If the token parameter were to get rotated right now it would break the Messaging API

yup, that makes sense. Would it be too difficult to add multiple valid tokens? Then we can activate a new one, ask the vendor to start using it, and remove the old one once we see they are using the new one.

**Comment by uncheckederror** [comment]
> > If the token parameter were to get rotated right now it would break the Messaging API
> 
> yup, that makes sense. Would it be too difficult to add multiple valid tokens? Then we can activate a new one, ask the vendor to start using it, and remove the old one once we see they are using the new one.

Yeah, plenty of ways to a lookup up on many values. If the number of possible values is small we can load config secrets into a dictionary and if there are a lot we could store them in the database and query against it.

**Comment by thefinn93** [comment]
safe to assume it's a small number, i expect it to be 1 token most of the time and occasionally 2. I dont anticipate it ever exceeding 2
