### ISSUE TITLE
request: some minor S3 changes

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/NumberSearch#331]
1. Please change [`CannedACL = S3CannedACL.PublicRead`](https://github.com/AccelerateNetworks/NumberSearch/blob/e3c8f966dbc2c336c27f2a94ac2003400e5d55fc/Messaging/Program.cs#LL725C29-L725C29) to `CannedACL = S3CannedACL.Private` (I think that's a valid value based on [aws docs](https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/T_Amazon_S3_Model_S3CannedACL.htm)). This will reduce the chances of inadvertently exposing private customer media.
2. Please prefix incoming media with `incoming/`

**Comment by uncheckederror** [comment]
> 2. Please prefix incoming media with `incoming/`

This is ambiguous as `incoming/` could be prefixed to the bucket or the file itself. Can you provide an example path for an incoming media file?

Here is the current path structure: `$"{spacesConfig.ServiceURL}{fileRequest.BucketName}/{record.Id}{file}"` are you proposing $"{spacesConfig.ServiceURL}incoming/{fileRequest.BucketName}/{record.Id}{file}";
or $"{spacesConfig.ServiceURL}{fileRequest.BucketName}/incoming/{record.Id}{file}";

**Comment by thefinn93** [comment]
`/` is not a character for a bucket name, so the latter is the only one that's valid. I would like two folders in the bucket: `incoming` and `outgoing`

**Comment by uncheckederror** [comment]
I have updated the configuration of the Messaging API to save incoming MMS files to the incoming folder in our DO space. There's not commit to go with this change as it was a config key, but it's in prod now.

**Comment by uncheckederror** [comment]
Look like the files are correctly getting saved into the incoming folder, so I think we are good to go.

**Comment by uncheckederror** [comment]
@thefinn93 are we good on this?
