### ISSUE TITLE
Add markdown interpreter for Hardware Product pages.

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#332]
**Describe the bug**
Editing through OPs seems to assume that every line break is a bullet point and markdown does not work to edit the page. 

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Products/Edit/9327246e-8c42-4f10-aef9-e3ccf5e47a31
2. Add any text to the input fields
3. Apply changes
4. [See the exact text that's in the input field on the hardware page ](https://acceleratenetworks.com/Hardware/GRP2670)

**Expected behavior**
I would like to be able to use markdown in OPs.

**Screenshots**
Here's what I'm typing in on OPs
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/2a9f3ae2-2641-4dab-9c52-cdab3b455161)

Here's what I'm seeing on an.com. It's showing the asterisks and not formatting how I want it to. 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/71c1f2fb-2b01-4079-a416-3db245dc38bc)

And this is what I would expect it to look like from the markdown I threw into OPs
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/aa496cc1-8a48-4639-bd3a-6d28af1e5fc0)

**Comment by uncheckederror** [comment]
Yeah, as you've observed it's not markdown. It's just text, that will get mapped to bullet points.

**Comment by sewcialite** [comment]
Ah, my bad. This should have been submitted as a feature request then?

-Hannah

**Comment by uncheckederror** [comment]
> Ah, my bad. This should have been submitted as a feature request then?

Not a problem, I've updated it. Can you help me understand what kind of content you're trying to add to these product pages?
 
Adding an interactive markdown editor is not a trivial task, so perhaps if I understand what you're trying to accomplish I can come up with a more immediate solution.

**Comment by uncheckederror** [comment]
I've added a field on Hardware items where you can paste in Markdown. This content will replace the existing Description section.
