### ISSUE TITLE
Grandstream DP730 Image is mirrored

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#334]
**Describe the bug**
The DP730 product image is mirrored, causing "grandstream" to be backwards and illegible. 

**To Reproduce**
1. Go to https://acceleratenetworks.com/Hardware/DP730
2. See the mirrored photo

**Expected behavior**
I'd like the product image to be the proper way and legible.

**Screenshots**
See on AN:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/d621fed4-4d7b-49e8-b41a-360f72aa555b)

See on Grandstream
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/c4c89914-ae77-49e4-bfe0-4c7de5086727)

[Here is the replacement image](https://www.grandstream.com/hubfs/Product%20Images/DP/DP730_side_cradle_web.png)

**Comment by uncheckederror** [comment]
The image for this product has been updated here: https://acceleratenetworks.com/Hardware/DP730

**Comment by sewcialite** [comment]
Appreciate the change! Looks great :)
