### ISSUE TITLE
Image Confusing for DP720

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#335]
**Describe the bug**
The image that is currently representing the DP720 includes the base station in the background. We may want to update this to only show the handset.

**To Reproduce**
1. Go to https://acceleratenetworks.com/Hardware/DP720

**Expected behavior**
If the DP750 or DP752 is sold separately, could we have just a photo of the handset instead of a combo picture?
[See this example](https://www.grandstream.com/products/ip-voice-telephony/dect-cordless/product/dp720)

**Comment by uncheckederror** [comment]
The image for this product has been updated here: https://acceleratenetworks.com/Hardware/DP720

**Comment by sewcialite** [comment]
Thank you for making that less confusing!
