### ISSUE TITLE
 Image Confusing for DP750

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#339]
**Describe the bug**
The image that is currently representing the DP750 includes the handset and cradle. We may want to update this to only show the base-station if they are not sold together.

**To Reproduce**
1. Go to https://acceleratenetworks.com/Hardware/DP750

**Expected behavior**
If the DP750 is sold separately, could we have just a photo of the base instead of a combo picture?
[See this example](https://www.grandstream.com/products/ip-voice-telephony/dect-cordless/product/dp750) I quite liked the 3rd photo with it on it's angle. ;)

**Comment by uncheckederror** [comment]
@sewcialite I believe this is fixed.

**Comment by danry25** [comment]
Closing as fixed since the image looks correct. No response from @sewcialite
