### ISSUE TITLE
Ensure Messaging handles requests to send SMSs with >160 characters gracefully

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/NumberSearch#340]

**Comment by uncheckederror** [comment]
@thefinn93 how do you imagine this would happen? Are you looking for the Messaging app to upgrade the SMS to an MMS or should the message be broken into multiple SMSes.

**Comment by thefinn93** [comment]
I was thinking something simple, like refusing to deliver messages >160 characters and responding with an error message, but this was at a time that we thought the upstream carrier was silently failing to deliver our messages due to excessive character count, but it turned out to be a larger issue with them delivering any messages to T-Mobile.

**Comment by danry25** [comment]
Do we want to just handle these as MMSes when there are more than 160 characters? Additionally, here are [file size limits by carrier](https://support.bandwidth.com/hc/en-us/articles/360033211714-What-are-the-maximum-file-sizes-for-MMS-messages-for-the-major-carriers-in-the-US-) for attachments. Also, [apparently MMSes are limited to 1600 characters](https://simpletexting.com/how-many-characters-in-a-text-message/) and each emoji may need to be counted as 2 characters?

**Comment by danry25** [comment]
@uncheckederror Please convert a SMS to an MMS if it is over 160 characters of ASCII but under 1600 characters of ASCII. Every Unicode character counts as 2 characters. Reject any messages over 1600 characters.

@thefinn93 In Web Texting, please warn the user that they will be sending an MMS if the message is over 160 characters of ASCII but under 1600 characters of ASCII. Every Unicode character counts as 2 characters. Reject any messages over 1600 characters.

**Comment by uncheckederror** [comment]
I mentioned the wrong issue in 036cb83 but that's where I implemented an error response and rejection if a client submits and message with more that 160 characters.
