### ISSUE TITLE
Improve the E911 workflow in Ops

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#342]
In Owned Numbers inside Ops it would be great to:

- Enable/Disable SMS
- [x] Use 1st Point's DIDSMSEnable endpoint
- [x] Then use 1st Points DIDRouteSMSToEPIDBasic endpoint to route SMS to EPID 265
- [x] Make available both in Owned Numbers and on the Order Detail page in Ops.

- [x]  Update ownership status (Underlying carrier & vendor)
- [x]  View and update a numbers E911 Registration
- [x]  When an order is submitted, process its address using the [ValidateAddress](https://portal.bulkvs.com/api/v1.0/documentation#/E911/post_validateAddress) endpoint and store the response.
- [x]   In Ops
- [x]   On the order details change the Register for E911 button to hit the POST endpoint of [e911record](https://portal.bulkvs.com/api/v1.0/documentation#/E911/post_e911Record)
- [x]   In Owned Numbers
- [x]   Access the get [e911Record](https://portal.bulkvs.com/api/v1.0/documentation#/E911/get_e911Record) endpoint daily to query for E911 registration status, display this to the user
- [x]    Hit the POST endpoint of [e911record](https://portal.bulkvs.com/api/v1.0/documentation#/E911/post_e911Record) to update the registration.
- [x]  Continue logging all E911 changes to the E911 page of Ops
- [x]   Show if a phone number is routed in FusionPBX @thefinn93 please advise with API details

_Originally posted by @danry25 in https://github.com/AccelerateNetworks/NumberSearch/issues/311#issuecomment-1493661620_

**Comment by thefinn93** [comment]
To check if FusionPBX has a number routed, call the `destination-details` endpoint of the REST API. It will tell you the domain the number is assigned to and some other details if it exists. I'm not sure what the behavior will be for destinations that don't exist, I filed AccelerateNetworks/fusionpbx-rest-api#2 to follow up on that

**Comment by uncheckederror** [comment]
> To check if FusionPBX has a number routed, call the `destination-details` endpoint of the REST API. It will tell you the domain the number is assigned to and some other details if it exists. I'm not sure what the behavior will be for destinations that don't exist, I filed [AccelerateNetworks/fusionpbx-rest-api#2](https://github.com/AccelerateNetworks/fusionpbx-rest-api/issues/2) to follow up on that

Very cool, I am looking forward to using that endpoint. Thanks for implementing it.

**Comment by uncheckederror** [comment]
In order to register an Owned Number for E911 service we need to associate it with an Address. Based on my discussions with Dan we believe the best UX here is to have a button for owned numbers that creates a new Order for just that number. This will associate the number with the Address from the new Order and then you can use the OrderEdit page in the Ops app to Register it for E911 Service. This also creates a paper trail for re-registering numbers for E911 service if the location changes.

**Comment by uncheckederror** [comment]
@danry25 okay you can try this workflow out by starting on the Owned Numbers page in the Ops app. 

https://ops.acceleratenetworks.com/Home/OwnedNumbers/

Each entry on the page has a button outlined in blue labelled "Create an E911 Registration Order" that will bump you into the checkout page of the Mvc app for that specific number. After you submit the order with a valid address you can then look it up in the Ops app, click the "Edit" button and then in the Product Orders section click the "Register for E911" button to complete the process and assign the Address in the order for that number's E911 service. Within a day the original number on the Owned Numbers page will be automatically update with the E911 Registration information from the order you submitted.

**Comment by uncheckederror** [comment]
@thefinn93 automatic SMS enablement is in the Messaging API now. I would like to roll it out when you are around so that we can test it to make sure that it works right with OrgSMS. For now I am going to hold off on deploying this change.

**Comment by danry25** [comment]
@uncheckederror It appears these E911 address orders are creating a quote and expecting porting information. Additionally, instead of saying "Ported" in the upper right corner can we say E911 Enabled?
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/db08397e-1f8d-4c11-83a7-ca7e3d593a5f)

One other thing, do we need to manually press the Register for E911 button on orders like these? Here is an example order: https://ops.acceleratenetworks.com/Home/Order/c6781b55-1cbe-4ac5-b2db-1778f93a0944

**Comment by uncheckederror** [comment]
> One other thing, do we need to manually press the Register for E911 button on orders like these? Here is an example order: https://ops.acceleratenetworks.com/Home/Order/c6781b55-1cbe-4ac5-b2db-1778f93a0944

Yes, you need to hit the red "Register for E911" service button on the Edit order page to complete the process.

**Comment by danry25** [comment]
Could we remove this step by automatically registering for 911 these types of 911 Registration orders?

Additionally, if we have a billing client ID or a prior order related to a phone number, can we use this information to prefill the orders page?

**Comment by uncheckederror** [comment]
> Could we remove this step by automatically registering for 911 these types of 911 Registration orders?

Possibly, but I am not sure that this would be good UX as it would hide the error messages produced by the E911 registration process.

> Additionally, if we have a billing client ID or a prior order related to a phone number, can we use this information to prefill the orders page?

This feature is a significant increase in complexity. Querying for this information by maintaining context on prior orders is possible but it will take a fair amount of time to implement.

**Comment by danry25** [comment]
>Possibly, but I am not sure that this would be good UX as it would hide the error messages produced by the E911 registration process.

Could we show the error status in the orders list? That is front and center when you login, making it hard to miss.

> This feature is a significant increase in complexity. Querying for this information by maintaining context on prior orders is possible but it will take a fair amount of time to implement.

Yes, but it significantly lowers the effort per order required for our support team.

**Comment by uncheckederror** [comment]
Alright after thinking about this for a while I am removing this feature entirely, it was a mistake. 

I am going to add a form to the Owned Numbers edit page to register a number for E911 service the amount of work that would need to be done to support extending this workflow to meet the requirements that Dan has listed above is frankly nuts. So instead I am going to drop this process entirely and introduce a new much dumber process that maintains context on nothing and relies solely on the vendor for tracking E911 registration status.

In order to prevent mistakes like this feature in the future, I am going to require process diagrams for new features moving forward @danry25 @thefinn93.

Here is a diagram of how I understand the workflow that I am going to implement for this feature:

![e911Registration drawio](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/0bbe9fbb-8f5b-4938-a25f-013c181cc1a0)

Given this new process it seems to me that we should remove the E911 information from the Orders entirely including the button on the Order Edit page for E911 Registration so as not to confuse the situation as E911 registrations are not actually tied to specific orders in our system or the vendor's system.

**Comment by danry25** [comment]
I would like to retain the E911 registration information if possible. Could we restrict the scope of work for E911 enabling a number perchance to make this more tractable? Perhaps we could provide an order ID to associate a number with an address already in the system and an existing client?

**Comment by uncheckederror** [comment]
A draft of the E911 Registration form for Owned Numbers is now up. @danry25 please try it out and provide feedback.

**Comment by danry25** [comment]
I love the new E911 workflow @uncheckederror !

Can we change the text from danger (red) to green after registering the E911 address successfully?
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/af9f3403-3090-44f3-95ad-8f4fd92e2447)

**Comment by uncheckederror** [comment]
> I love the new E911 workflow @uncheckederror !
> 
> Can we change the text from danger (red) to green after registering the E911 address successfully? ![image](https://user-images.githubusercontent.com/1683673/250331768-af9f3403-3090-44f3-95ad-8f4fd92e2447.png)

Alright try it now.

**Comment by danry25** [comment]
The modal is green now after successful E911 registration, awesome work @uncheckederror !
