### ISSUE TITLE
Add EHS40 to the hardware page

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#346]
**Describe the bug**
We sell the EHS36 on the website but not the EHS40. If we list one, we should list the other. 

**Expected behavior**
Please add [this device](https://www.yealink.com/en/product-detail/accessories-ehs40) to the website.

**Comment by danry25** [comment]
The EHS36 has been removed from the website since it is not a USB capable device and we have replaced this with the EHS40 @sewcialite 

View it here: https://acceleratenetworks.com/Hardware/Yealink%20EHS40
