### ISSUE TITLE
Spelling error on Port Request Form

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#347]
**Describe the bug**
"being" is supposed to say "begin"

**To Reproduce**
1. Go to a [completed order form,](https://acceleratenetworks.com/Cart/PortingInformation/92afc16c-c006-4e18-a803-8b16e383e8ad) using Joy's as a reference. 
2. See the top wording. It is spelled incorrectly and I think there should be a comma. 
3. 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/3783464b-842c-4bc2-930d-422e849d3757)

**Expected Wording**
We need you to provide this information to bring your existing phone numbers over to our network. Without this information, we cannot begin transitioning you from your old phone provider.

**Comment by uncheckederror** [comment]
A new build is live, @sewcialite please verify that this bug is fixed.
