### ISSUE TITLE
Add additional hardware

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#35]
Could we add the following phones to the hardware page?
- Polycom Soundstation IP 7000 ($300ea, [picture](https://www.teledynamics.com/tdresources/11315553-a8da-4a45-b632-b8ced825957d.jpg))
  - Description: Light up your conference room with the vibrant sound quality provided by the Polycom Soundstation IP 7000! Supports 3 way calling, HD Voice & Power over Ethernet.
- Snom PA1 ($150ea, [picture](https://www.teledynamics.com/tdresources/SNO-PA1image1.jpg))
  - Description: Enable paging over speaker systems with the Snom PA1. The built in amp enables small scale deployments, while the numerous outputs can tie into existing amplifiers.
- Split GRP2612 listing, remove WiFi from GRP2612 description and create the GRP2612W ($85ea)
  - Description: Need a phone where only WiFi exists? The GRP2612W has you covered with powerful WiFi 5 (aka 802.11AC) support built in. Plug into power and dial away!

If the flavor text could be massaged so that this new row has a consistent line count that would be ideal.

**Comment by uncheckederror** [comment]
This issue is now resolved.

https://acceleratenetworks.com/Hardware
