### ISSUE TITLE
FirstPoint Number Purchase Fails - 10 Digits submitted, 11 Digits needed

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#352]
**Describe the bug**
Ops.AccelerateNetworks.com is showing this happy checkmark as though phone numbers were successfully purchased, when the vendor is clearly telling us they could not process our incorrectly formatted order:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/27fb7320-9ea7-407e-87f3-80b00b4420aa)

**To Reproduce**
1. Go to AccelerateNetworks.com
2. Click on Numbers
3. Search, select and purchase a number from FirstPoint
4. See error by clicking purchased number on order in Ops

**Expected behavior**
We should never show the checkmark to the right of a number unless the order was successfully placed and the number shows in our inventory in FirstPoint. The code returned by FirstPoint on Number Purchase needs to be validated as well, it appears we accepted -404 as a valid code.

**Comment by uncheckederror** [comment]
I have deployed a new build that I believe fixes this issue. Please try it again.

**Comment by danry25** [comment]
@uncheckederror This works now, woo!

Can we ensure that the green checkmark is only shown for FirstPoint number purchases when we get {"code":0,"text":"DID assigned from inventory, processed immediately. "} back as the raw response? Any other code or text should be considered a failure.

**Comment by uncheckederror** [comment]
> Can we ensure that the green checkmark is only shown for FirstPoint number purchases when we get {"code":0,"text":"DID assigned from inventory, processed immediately. "} back as the raw response? Any other code or text should be considered a failure.

This change is live now.
