### ISSUE TITLE
Notes on Owned Number cannot be updated

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#354]
**Describe the bug**
When you fill in a note on an Owned Number in Ops it does not save.

**To Reproduce**
1. Go to 4259053998
2. Fill in Unassigned in the notes field
3. Press Update
4. See that the note did not save

**Expected behavior**
The note should be saved to the Owned Number

**Comment by piajesse** [comment]
I've noticed this bug as well on Firefox 114.0.1 on mac

**Comment by uncheckederror** [comment]
@piajesse @danry25 can you try it now? I think I've fixed it.

**Comment by piajesse** [comment]
Worked for me

**Comment by danry25** [comment]
Works for me, closing this issue
