### ISSUE TITLE
Use higher quality AN Mobile Image

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#356]
@piajesse Please provide updated screenshots with the new blue theme so I can make an image like the one below for @uncheckederror to use in our Accelerate Networks Mobile documentation.

Additionally, screenshots are missing entirely on Google Play, and the Apple screenshots are outdated.
https://apps.apple.com/us/app/accelerate-networks-mobile/id1560522124?platform=iphone
https://play.google.com/store/apps/details?id=com.acceleratenetworks.mobile
![AN Mobile iOS](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/bbff9566-f55f-45f7-8822-655f45bc6382)

**Comment by danry25** [comment]
@uncheckederror Can you update to the image below and close this issue?

@piajesse What is going on with the iOS screenshots? I do not see the updated blue theme on the Apple App Store screenshots still.

![Accelerate Networks Mobile Android](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/4d42fb21-5c75-48e9-9c15-f4da566afc95)

**Comment by uncheckederror** [comment]
@danry25 new images are up please verify the change.

**Comment by danry25** [comment]
Looks good!
