### ISSUE TITLE
Add Reporting on Rep Performance

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#358]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
By using the data we have on quote generation and orders that are placed to show our sales reps when they are most effective, we can encourage them to use the most productive tactics to make sales

**Is your feature request related to a problem? Please describe.**
Currently there is no easy way to compare week by week or month by month how many quotes and sales each rep generated. Providing a graph and statistics on these to our sales team members would enable them to have better insight as to when they were most productive.

**Describe the solution you'd like**
Add a page in Ops viewable to those with both the sales and support roles that shows how many orders each rep made and the order status. Pending on #327 we should also track which quotes convert to orders for each rep.

**Comment by uncheckederror** [comment]
This is a cool idea but you haven't made any specific statements about what you want to see on this dashboard.

How do we know when our sales people are being the most effective? How can we then show that to them?

"Currently there is no easy way to compare week by week or month by month how many quotes and sales each rep generated."
I can add columns for quotes and orders submitted per week and per month by the sales rep's email. Is that what you are asking for?

Here's my first draft: 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/82149a9b-c848-45e2-b258-cdffbdb863b7)

**Comment by danry25** [comment]
This looks good, just would like to have a graph of the Orders by month for a given rep, perhaps this would be a separate page for a specific rep?

**Comment by uncheckederror** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/55bba6a5-e828-47e5-a903-f71f16541b10)

Alright here's another draft. I am still trying to work out the graphing.

**Comment by uncheckederror** [comment]
Alright I think it's mostly there with the graph: https://acceleratenetworks.com/ingest/salesdashboard
