### ISSUE TITLE
SMS Enablement Response Changed

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#360]
**Describe the bug**
The FirstPoint SMS enablement endpoint is responding with "0Order sent in! Provisioning may take some time, especially with SMS enablement." not in an XML format, this may affect your usage of the endpoint (it is safe to re-run this endpoint on FirstPoint SMS enabled numbers that are already boarded FYI).

**Comment by uncheckederror** [comment]
Good to know, thanks for the update.

**Comment by uncheckederror** [comment]
@danry25 Alright so the good news is that we are not validating the response of this endpoint so if the text of the response changes that won't break our app.

https://github.com/AccelerateNetworks/NumberSearch/blob/d598fc451ffc4149d97da296d363dd88a21f871c/Messaging/Program.cs#L407
