### ISSUE TITLE
MMSes being sent to shortcodes and numbers that don't accept MMS

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#361]
**Describe the bug**
We are seeing MMSes being sent to destinations that do not support MMS (non-cellular numbers, particularly shortcodes, toll free numbers and Bandwidth.com SMS enabled numbers). I am unclear if OrgSMS is sending these as SMSes or MMSes to sms.callpipe.com, but regardless it appears the affected messages could have been sent as SMSes.

**To Reproduce**
1. Go to text Wildflour Bakery at 18553393178 or Facebook shortcode 39041
2. See error in FirstPoint MMS CDRs

**Expected behavior**
These messages which are entirely text and below 160 characters should be sent as SMS, and a warning should be sent to the client if we cannot send an MMS.

**Screenshots**
Facebook 39041 Failed Reply
![39041 Failed Outbound MMS](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/e5d97ac1-7e2e-4094-a147-74d55a991051)
WildFlour 18553393178 Failed Reply
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/8b596822-9240-452a-837e-b4a55a896bd3)

**Additional context**
Are we processing the Reject Reason response code we get from FirstPoint when sending a text via SMS or MMS? This should be OK for texts that are sent. 

_No Route SMS Daily Limit Wholesale_
I see a number of Reject Reason "No Route SMS Daily Limit Wholesale" followed by our account # in our MMS logs, and we should be telling the user they have hit their MMS limit for the day (currently we have a 200 SMS and 100 MMS limit per day per phone number, an increase has been requested) when these rejections occur and ideally conveying to Support that they should touch base with the client (as the client is likely sending a form text message that is way too long).

_No Route in translations table for 39041_
Another Reject Reason we saw that meant the text was not delivered

_Bandwidth.com Interop Rejects_
We got these Reject Reason responses for 4 MMSes this past month, I believe all should have been sent as SMSes:
OCN: 006F interop fail/unsupported
OCN: 076F interop fail/unsupported
OCN: 006F interop fail/unsupported
OCN: 997E interop fail/unsupported

**SMS Limitations**
We need a single SMS message to be [under 160 GSM-7 Characters](https://www.twilio.com/docs/glossary/what-is-gsm-7-character-encoding) ([here is the list of GSM-7 characters](https://www.developershome.com/sms/gsmAlphabet.asp)) or under 70 characters if sent as Unicode.

**Comment by uncheckederror** [comment]
Based on my conversation with @danry25 sms.callpipe.com will send an message back to the registered client in the format of an SMS informing them that outbound delivery of the message failed with the upstream provider.

"Failed to send this MMS message to {toNumber}. It maybe an invalid address for this message type. Try sending text only."

**Comment by uncheckederror** [comment]
Ah okay so sms.callpipe.com already responds to message sending requests with a 400 Bad Request when they are rejected by the upstream provider. It also provides a boolean for the MessageSent field indicating success or failure along with description of the failure from the upstream provider in the Message field.

We immediately tell the client that sending the message failed and why. I don't think we should follow up with a fake SMS to the sender as that would incentivize clients to not parse or inspect our response to their message sending request.

In the future @danry25 if you want to test the behavior of sms.callpipe.com you can login using your ops credentials and try whatever requests you'd like from the Swagger docs.
