### ISSUE TITLE
Report when SMS routing is incomplete

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#362]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Right now clients to sms.callpipe.com do not get status when a phone number is not fully routed or becomes unrouted from our texting platform.

**Is your feature request related to a problem? Please describe.**
End user can send messages to nowhere without being informed that our application no longer handles their number's SMS and MMS.

**Describe the solution you'd like**
When we get a "Longcode not assigned to that account" response, provide the API client with this status.

If the DID is with Bandwidth.com advise that we need to ask BulkVS to move it for offnet SMS enablement, and if the number is toll free we need to complete the form and send it to 1st Point manually.

**Describe alternatives you've considered**
Manual reconciliation of SMS enabled numbers, which is error prone and can fall through the cracks easily.

**Additional context**
When this issue crops up you will get the following response from the DIDRouteSMSToEPIDBasic endpoint: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DIDRouteSMSToEPIDBasicResponse xmlns="https://api.1pcom.net/"><DIDRouteSMSToEPIDBasicResult><code>-2</code><text>Longcode not assigned to that account</text></DIDRouteSMSToEPIDBasicResult></DIDRouteSMSToEPIDBasicResponse></soap:Body></soap:Envelope>

**Comment by uncheckederror** [comment]
@danry25 when clients to sms.callpipe.com submit a webhook registration request to the POST /client/register endpoint they receive a verbatim copy of the message provided by Endstream's API when the DID registration endpoints are called.

https://github.com/AccelerateNetworks/NumberSearch/blob/091c468af9fef7073760644320443f5c578bfc23/Messaging/Program.cs#L447

**Comment by danry25** [comment]
Does sms.callpipe.com repeat checkRoutedAgain regularly for numbers that were not routed initially? Is there a way for clients to be informed when checkRoutedAgain returns true the first time?

**Comment by uncheckederror** [comment]
No. They can call the POST /clients/register endpoint again to get their current registration status with Endstream.

Neither sms.callpipe.com nor the OrgSMS clients track the status of the numbers with the upstream provider. Even if sms.callpipe.com pushed a message through to the registered webhook URL, OrgSMS wouldn't know how to handle it. I suppose sms.callpipe.com could pretend that the message was an SMS though, as OrgSMS doesn't have a way to tell the difference between a real SMS Message and a generated one.

**Comment by thefinn93** [comment]
Could we just have a field for each number for the status of it? Ideally returned via the `/client` endpoint. As it stands, webtexting is polling that to check the routing status of each number and confirming the webhook URL and secret are correct. If there was a list of problems, related to upstream routing or just generic, those could be checked for as well.

**Comment by uncheckederror** [comment]
> Could we just have a field for each number for the status of it? Ideally returned via the `/client` endpoint. As it stands, webtexting is polling that to check the routing status of each number and confirming the webhook URL and secret are correct. If there was a list of problems, related to upstream routing or just generic, those could be checked for as well.

Yeah, what if I were to give you a boolean for the upstream registration status and then a string with a description of the boolean. Where true is ready for messaging and false means there's a problem.

```
public bool RegisteredUpstream { get; set; } = false;
public string UpstreamStatusDescription { get; set; } = string.Empty;
```

**Comment by thefinn93** [comment]
Works for me

**Comment by uncheckederror** [comment]
@thefinn93 how's this change working out for you?

**Comment by thefinn93** [comment]
as discussed in the chat, it's difficult to test without a number in a state where it's not registered upstream, but from the testing I've been able to do without that it seems to work fine. Probably ok to close this.

**Comment by danry25** [comment]
I provided Finn with a number in a state that can never be completed and he tested this issue.
