### ISSUE TITLE
Bill for estimated time onsite

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#364]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**

This will allow us to capture the value of onsite labor more efficiently, increasing recenue

**Is your feature request related to a problem? Please describe.**

When an installer is onsite, it often takes 10 to 15 minutes per phone to install each phone (assembly, discussing with the user where it should be placed, etc), meanwhile a fax adapter or router setup take 20 to 60 minutes depending on complexity (wiring changes or programming client devices)

Based on what hardware is in cart 🛒, it would be good to estimate labor hours and bill for this time upfront.

**Describe the solution you'd like**
If a customer orders 6 phones, we should likely bill them for 1 hour of labor on top of the call-out charge.

**Describe alternatives you've considered**
We currently manually true up these bills, which doesn't set client expectations upfront.

**Comment by uncheckederror** [comment]
Alright so we bill for 15 minutes of install time for each hardware item and then a full hour per fax adapter. 

What if I added an "install time" field for each hardware item that you could set and update in Ops. Then based on what you added to your cart it would calculate the total amount of time needed for the install?

**Comment by danry25** [comment]
This seems like a reasonable solution to me, and gives the client the benefit of an immediate scope of work so they can schedule accordingly.

**Comment by uncheckederror** [comment]
@danry25 you'll need to update all of the Hardware items in Ops with values for the Install Time field.

**Comment by uncheckederror** [comment]
> ... a fax adapter or router setup take 20 to 60 minutes depending on complexity (wiring changes or programming client devices) ...

Neither fax adapters nor routers are listed on the Hardware page of the website. How do you propose we handle these?

**Comment by uncheckederror** [comment]
- [] Regenerate the one-time upfront invoice in the billing system when the Install Boolean is toggled from the Order Edit page.

I am dropping this requirement as I think it's better to directly control the regeneration of the invoices rather than having this happen automatically as you might want to change multiple things about and order before updating the invoices.

**Comment by uncheckederror** [comment]
@danry25 I think this feature is ready, can you try it out?

**Comment by danry25** [comment]
Lookin' good!
