### ISSUE TITLE
Ops - Unassigned Numbers showing stale FusionPBX routing data

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#366]
**Describe the bug**

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/OwnedNumbers/
2. Search the word Unassigned
3. Find a number with a domain showing under the FusionPBX column
4. Search for said number in FusionPBX under Dialplan => Destinations, choose Show All then fill in the search field
5. Note how the number does not show up in FusionPBX, yet Ops thinks the number is routed in FusionPBX

**Expected behavior**
The FusionPBX field should show "No Destination found in FusionPBX."

**Comment by uncheckederror** [comment]
@danry25 can you give me a specific example number? And tell me what's wrong with it. I am having difficultly debugging this issue.

**Comment by danry25** [comment]
Search the word Unassigned in Owned Numbers in Ops, see numbers like 6614025519 which still shows as being on Washington Policy. Routing has been removed in FusionPBX for nearly all of these numbers.

**Comment by uncheckederror** [comment]
> Search the word Unassigned in Owned Numbers in Ops, see numbers like 6614025519 which still shows as being on Washington Policy.

When we query for the destination and domain info for this number we get a valid response from the FusionPBX API with the values show on the Ops page.

> Routing has been removed in FusionPBX for nearly all of these numbers.

How can we tell if routing has been removed for a specific phone number? Right now we just link to the Destination Edit page if we can pull a valid destination_uuid.
