### ISSUE TITLE
[FEATURE] Capture ISP info in Order

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#367]
Add a text field for comments on the Order's ISP situation. 

- [ ] Track Notes on ISP
- [ ] Speed
- [ ] Cost
- [ ] Term Commitment
- [ ] When we need to follow up (initial contracting and recontracting) 
- [ ] Associate documents with clients

**Comment by uncheckederror** [comment]
@danry25 is their anything else you would want to track on the Quote/Order?

**Comment by uncheckederror** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/7210cb28-b871-4e83-b5d3-d95113d4ff70)

Here's a mock up of what it could look like to collect ISP info in on the Order form.

**Comment by sewcialite** [comment]
I think this is almost entirely on Dan as he sends out the information to receive quotes from our internet partners.

**Comment by uncheckederror** [comment]
> I think this is almost entirely on Dan as he sends out the information to receive quotes from our internet partners.

@danry25 is that how this process works?

**Comment by uncheckederror** [comment]
Alright so based on our discussion with Scott and Hannah at the meeting on 9/18 this ISP info should be part of the new client form rather than the order checkout page.

**Comment by danry25** [comment]
To recap our conversation, on the New Client Worksheet we need to:
-  Add a "Current Internet Connection" section 
  - A toggle for Contract (Yes/No, display contract date picker and # of months if yes)
  - A field for Cost
  - Bill Upload
  - Speedtest Result (and a link to SpeedTest.net)

**Comment by danry25** [comment]
Closing and merging with issue #368
