### ISSUE TITLE
[BUG] - Recent quotes are generating with no tax rate

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#374]
**What is broken?**
When you create a quote no tax rate is generated

**To Reproduce**
1. Go to view the quotes associated with https://ops.acceleratenetworks.com/Home/Order/a9bdda79-b92f-407f-a88f-efc57a79b26c

**Expected behavior**
A quote should have tax associated with it inside Washington State

**Comment by uncheckederror** [comment]
The upfront invoice associated with this order doesn't appear to exist any more.

**Comment by uncheckederror** [comment]
Okay, I was able to reproduce the issue in this quote: https://billing.acceleratenetworks.com/client/quote/cI2FO8xAKhFyA0kl7BGegJmjCIzP0aw2
https://acceleratenetworks.com/cart/order/b3c0724f-cada-42f1-92b3-63f525f4bdb2

**Comment by uncheckederror** [comment]
This was a bug in the validation logic that we added. It was checking that the loccode was in a range of 0 to 15. But the value of the loccode for SEATTLE is 1726. So it was not applying a tax rate. I have updated it to make sure the combined tax rate value is in a range of 0 to 0.15 which should work given that for SEATTLE it is 0.101. Additionally there was another bug where if the tax rate had a non-blank name we would not apply tax to Order. I have resolved this by doing the opposite.

@danry25 These changes are live please try them out by placing a quote on the website.
