### ISSUE TITLE
[FEATURE] - Spreadsheet Export of Numbers In Bulk

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#375]
**What is the problem that this feature solves?**
It would be very convienent to be able to export a list of the current carrier, last port date and such from the Numbers in Bulk page to assist in prospecting and sales.

**Describe the solution you'd like**
A button that exports a csv or other spreadsheet like file with the numbers listed in the order they were entered into the submission field in.

**How will this improve revenue or reduce our costs?**
Not having this feature slows down our sales team's productivity, and our support team can use it to show clients what numbers have been addressed for porting.

**Comment by uncheckederror** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/b9ca742d-c14c-4fac-aedb-99a2997de1e0)

I have added an Export to CSV button at the bottom of the page. It appears after you've run your initial query.

@danry25 this feature is live, please try it out.
