### ISSUE TITLE
[FEATURE] Get messaging receipts by Dialed Number

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#376]
**What is the problem that this feature solves?**
I am always frustrated when I send a message from OrgSMS but when I check the billing log on First Point Communication's website I don't see a record for the message I sent.

**Describe the solution you'd like**
I would like to be able to check if any message have been sent or received through the sms.callpipe.com API related to a specific dialed number.

**How will this improve revenue or reduce our costs?**
Not having this feature makes it difficult to discover where messages got lost in our messaging pipeline/stack and thus difficult to resolve or debug message delivery issues.

**Comment by uncheckederror** [comment]
@danry25 this feature is live. Please try it out!

**Comment by danry25** [comment]
Thanks for adding this!
