### ISSUE TITLE
[BUG] When an outbound message fails, a record of the message is not saved.

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#378]
**What is broken?**
Only requests to the /message/send endpoint that receive a success response are actually recorded by the API. We want to capture failures so that we can better understand what the clients of the Messaging API are doing wrong.

**Comment by uncheckederror** [comment]
Related to #377

**Comment by danry25** [comment]
This is complete and works well, thanks Tom!
