### ISSUE TITLE
[FEATURE] Add endpoint for finding out what messages have failed

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#379]
**What is the problem that this feature solves?**
Occasionally messages fail when sending to 1st Point. It would be good practice to identify the cause of failure (wrong/invalid phone number, error in configuration of Web Texting or SMS client, or an issue with sms.callpipe.com) so we can prevent recurrences of this in the future.

**Describe the solution you'd like**
Once issue #377 is resolved, provide an endpoint to show which messages have failed. Allow user to pick the date range they would like to query for.

**How will this improve revenue or reduce our costs?**
This will allow us to use our records of failed messages to resolve SMS deliver-ability issues rather than waiting for our clients to complain to us about a given issue.

**Comment by uncheckederror** [comment]
@danry25 this feature is live. Please review it. I wouldn't expect any of the data it proves for message prior to now, to show a valid failure status.
