### ISSUE TITLE
[FEATURE] Easier Swagger login to sms.callpipe.com

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#383]
**What is the problem that this feature solves?**
Our support team does not feel comfortable with the current token generation and authorization method, as it necessitates manual copying and pasting into the /login endpoint, then copying the result into the Authorize section.

**Describe the solution you'd like**
Add a link to Ops that takes you to the swagger page and prefills your token from Ops (since they use the same token).

**How will this improve revenue or reduce our costs?**
This will save support time and make it easier to verify and diagnose messaging issues.

**Comment by uncheckederror** [comment]
Rather than having support reps directly interact with sms.callpipe.com perhaps we should build out a dashboard inside of Ops that displays failed messages, client registrations, and client usage.

**Comment by uncheckederror** [comment]
Dan asked to have the register link removed for the list of unregistered phone numbers that we receive text messages for and #386 is to replace it, as we need the customer to pay for texting before providing it to them.
