### ISSUE TITLE
[BUG] - Orders inbox CC'ed multiple times on quotes

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#388]
**What is broken?**
It looks like the Orders inbox is CC'ed multiple times when a quote is generated on the website:

**Expected behavior**
The orders inbox should be CC'ed once.

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/afdb759f-4671-4e8a-8fe8-5fe2cd085347)

**Comment by uncheckederror** [comment]
@danry25 I believe this is fixed now. Please verify.
