### ISSUE TITLE
[BUG] Daily Briefing Emails have incorrect information

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#390]
**What is broken?**
 Daily Briefing emails have incorrect information in the new sections. It seems to be pulling old quotes from previous years, as well as pulling a quote that never installed for a 1 month follow-up post install.

**Examples**
1. Daily Briefing for 8/27/2023
- Quotes submitted today has a quote from 7/27/2021

2. Daily Briefing for 8/30/2023
- Quotes submitted today has a quote from 7/30/2021
- Follow up with Installs from last month has pulled in a quote that never installed. 

**Screenshots**
1. 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/9220582d-6b3e-411a-95ec-bd6998284808)

2.
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/04d0563c-ef7b-494e-b8a2-4a7444ebd7f7)

**Comment by sewcialite** [comment]
I personally don't mind adding a section to follow up on quotes, but I think it needs to be specific to quotes and not mixing quotes and installs.

**Comment by sewcialite** [comment]
An order came in on 8/28 at 4:12pm. It was too late for the 8/28 daily briefing, but it was not included in the 8/29 daily briefing. 

Order for reference: https://ops.acceleratenetworks.com/Home/Order/53fed876-8c2b-4772-8c6c-9e2e6587f60e

Not listed anywhere on the daily briefing. 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/bffc20e3-893b-4832-b212-0789a5e8fd39)

**Comment by sewcialite** [comment]
Hello. Today's daily ingest is not correct. The orders completed today are not correct as far as I can tell after looking in ops
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/59f44398-ea81-4adf-9dc1-bc719a3927cb)

**Comment by uncheckederror** [comment]
I have updated the daily briefing emails to show the completed date in the email.

**Comment by sewcialite** [comment]
Hey Support,

Here's everything you need to know about the orders in the Accelerate Networks system.


**Orders submitted today:**
Client Name - Install date

**Orders completed this week** 
Client Name - Install date

**Quotes submitted this week**
Client Name


**Incomplete orders from the last quarter**
Client Name - Install date


**Follow up with installs from last week:**
Client Name - Install date

**Follow up with installs from last month:**
Client Name - Install date

**Follow up with installs from last year:**
Client Name - Install date

Have a great day, hombres!

**Comment by sewcialite** [comment]
I am going to close this for now until I have other suggestions

**Comment by sewcialite** [comment]
I believe we could use a slight update to this. Could we update and add to the orders section? 

We had an order come in yesterday, that hasn't been paid. It is an existing client we will run their card on file. 

"Orders submitted today - Paid:
Client Name - Install date

Orders submitted today - UnPaid:
Client Name - Install date"

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/c560b564-ebfe-484d-a6d9-5c8e2eefe01f)

**Comment by uncheckederror** [comment]
@sewcialite does it look right now?
