### ISSUE TITLE
[BUG] - Flavor text presented when "Do not send a confirmation email" is inaccurate

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#391]
**What is broken?**
When "Do not send a confirmation email" is checked on the checkout page, the user still sees A confirmation email will be sent to <Email address provided> shortly."

**Expected behavior**
Hide this blue modal.

**Comment by uncheckederror** [comment]
This flavor text should now be hidden when emails are suppressed. Please verify this fix and then close this issue.
