### ISSUE TITLE
[FEATURE] Selectability/Copy-Pasteability for ease of use

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#393]
**What is the problem that this feature solves?**
In ops, the port request page under a client order links to BulkVS, but it would be really handy to be able to copy and past the number from the box as well so we can search in the email for the current status rather than typing by hand.

**Describe the solution you'd like**
I would like to be able to highlight/select text to copy it from the blue box.
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/7646e111-aef6-4182-8a84-c646e2c7c6f5)

**How will this improve revenue or reduce our costs?**
I don't think it will, but it will make our job easier

**Comment by uncheckederror** [comment]
> I don't think it will, but it will make our job easier

For future reference making your job easier counts as saving us money, or "reducing our costs" as your time is valuable. 💖

**Comment by uncheckederror** [comment]
This change is live in Ops. Please verify the fix and then close this issue.

**Comment by sewcialite** [comment]
It previously linked to the bulkvs ticket/site. Is it possible to retain the link and also make it select-able?

**Comment by uncheckederror** [comment]
Yes, try clicking on the column name. It is a link to the bulk VS website.
