### ISSUE TITLE
[BUG] Tracking Link does not correctly redirect

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#394]
**What is broken?**
When I click the tracking link, it takes me to a broken link in ops rather than the shipping partners tracking link.

**To Reproduce**
In an order that has the teledynamics tracking uploaded to ops, under assigned hardware, a blue button appears that says "tracking status"
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/b03a2139-b05c-4748-a9b6-b627d7519db2)

**Expected behavior**
I would like it to take me to the shipping partners tracking link or pull the tracking status

**Comment by uncheckederror** [comment]
think Hannah is right the manual entry sucks, so lets avoid that. It would be neat if you could just provide the Order # from TeleDynamics and then Ops would generate the product items for you and grab the MAC Address, Condition, Serial Number and Tracking link for you.

**Comment by uncheckederror** [comment]
Alright I have updated the Product Order system to ingest data from TeleDynamics based on the Order # in their system. This will autofill the correct tracking info, MAC Address, Serial Number, and Condition from their system so you don't have to manually copy and paste it over.

**Comment by uncheckederror** [comment]
Here's how it works @danry25 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/18c74374-4640-4d9d-b911-89acb53bcb67)
Ideally TeleDynamics could expose and endpoint like /api/v2/orders/{poNumbers} that accepted a comma delimited list of "OrderNumber" instead of a comma delimited list of "PONumber".

**Comment by uncheckederror** [comment]
You can test this feature in Ops by using the "Link to TeleDynamics Order" order button in combination with a valid Order # in the text input. If any Assigned Hardware items already exist you'll need to delete them, otherwise they will be skipped.

**Comment by sewcialite** [comment]
I am in the process of testing this with an order received this morning. It will likely be another day or two before I can fully close this issue. 

So far the flow is significantly better. Tracking actually links to what I expect! I like the "link to teledynamics" button

I am looking forward to the :pizza: tracker update to give clients a view into the status as well.

**Comment by sewcialite** [comment]
This is working well. Knock on wood. I will file any issues I run into as a new bug per[ this thread](https://github.com/AccelerateNetworks/NumberSearch/issues/402).
