### ISSUE TITLE
[FEATURE] Add additional status to the Pizza Tracker

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#396]
**What is the problem that this feature solves?**
We'd like more visibility into the status of an order in ops.

**Describe the buttons you'd like added**

Submitted > **_Invoice Paid_** > Processing > **_Pending Tracking_** > **_Shipped_** > Complete 

**How will this improve revenue or reduce our costs?**
This will give clients more information into the status of their order as well as giving us insight into the actual status of the order

**Comment by uncheckederror** [comment]
We really need to see when the invoices have been paid in Ops, because we can't order the hardware or do the install until the invoices have been paid.

**Comment by uncheckederror** [comment]
This is related to #327.

**Comment by uncheckederror** [comment]
Support can't move forward with an order until its clear that we've been paid. So it needs to be as clear as possible which orders have and haven't been paid in Ops.

**Comment by sewcialite** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/669ede2b-d122-43f9-b560-8b20eaff5fba)

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/12e5a47f-fc32-428e-a81f-9f0a11046edc)


The paid tag/status is looking amazing! Any eta on the Tracking and Shipping statuses?

**Comment by uncheckederror** [comment]
I am working building out those steps, but the data to support them mostly comes from TeleDynamics so were partially blocked on this issue until they respond to us and #402 is resolved.

**Comment by uncheckederror** [comment]
@sewcialite the shipping status is live now: https://acceleratenetworks.com/cart/order/614facb7-3dc7-444f-b81d-9a683e421350

**Comment by sewcialite** [comment]
Yeah boii! That looks so good! TY!
