### ISSUE TITLE
[BUG] Year not showing on orders

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#397]
**What is broken?**
The date shows MM/DD HH:MM even for orders submitted in previous years. 

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/Order
2. Use your eyes to see that the year is missing under Order Information
3. Question everything 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/acffda51-84ef-4696-a981-e6de60ecf955)

**Expected behavior**
MM/DD/YY HH:MM

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/d6c9e381-4d9f-4074-8ea2-07aaf2bac4d7)

**Comment by uncheckederror** [comment]
A meme in my github issue? https://media.tenor.com/sFGB4cW82U8AAAAC/jail-right-to-jail.gif

**Comment by sewcialite** [comment]
If y'all can do emojis, I can do memes 😜
