### ISSUE TITLE
[BUG] Big Red Error when Updating Order Status

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#398]
**What is broken?**
I toggled an order to complete, I then clicked the green "Update" button and then I recieved a big, red error message and the change did not save. This was an old order from 2021 I was trying to update. 

**To Reproduce**
I specifically was working on [this order](https://ops.acceleratenetworks.com/Home/Order/16c9414e-de2e-4256-823d-628db55541e9) in ops.

**Expected behavior**
I would like it to give me the green happy message and save my changes. 

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/9854f3d8-ea06-4dd2-9173-90765da3f02d)

Text of the error: 

Failed to update this order! 😠 Call failed with status code 404 (Not Found): GET https://billing.acceleratenetworks.com/api/v1/quotes/4198 at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response) at NumberSearch.DataAccess.InvoiceNinja.Invoice.GetQuoteByIdAsync(String invoiceId, String token) in /home/vsts/work/1/s/NumberSearch.DataAccess/InvoiceNinja/Invoice.cs:line 77 at NumberSearch.Ops.Controllers.OrdersController.OrderUpdate(Order order) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/OrdersController.cs:line 354

**Comment by sewcialite** [comment]
I received the same error for a different order. 

Same steps to reproduce. Toggle to complete, click update, receive error. 

[Ops order link](https://ops.acceleratenetworks.com/Home/Order/8895ab1f-dced-4889-9ec2-f165e83e44ba)

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/2977e216-c066-4de2-a64a-a5e5681e8e8c)

Text of the error:

Failed to update this order! 😠 Call failed with status code 404 (Not Found): GET https://billing.acceleratenetworks.com/api/v1/quotes/4251 at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response) at NumberSearch.DataAccess.InvoiceNinja.Invoice.GetQuoteByIdAsync(String invoiceId, String token) in /home/vsts/work/1/s/NumberSearch.DataAccess/InvoiceNinja/Invoice.cs:line 77 at NumberSearch.Ops.Controllers.OrdersController.OrderUpdate(Order order) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/OrdersController.cs:line 334

**Comment by sewcialite** [comment]
I received this error again, with the same steps to reproduce as the previous issues, but on a different order.

[Ops order link](https://ops.acceleratenetworks.com/Home/Order/58015989-4942-46e7-98d3-0f2143e903e0)

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/b211de94-9a5f-4a8b-815f-c7ef78508334)

Text of the error:
Failed to update this order! 😠 Call failed with status code 404 (Not Found): GET https://billing.acceleratenetworks.com/api/v1/quotes/1876 at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response) at NumberSearch.DataAccess.InvoiceNinja.Invoice.GetQuoteByIdAsync(String invoiceId, String token) in /home/vsts/work/1/s/NumberSearch.DataAccess/InvoiceNinja/Invoice.cs:line 77 at NumberSearch.Ops.Controllers.OrdersController.OrderUpdate(Order order) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/OrdersController.cs:line 448

**Comment by uncheckederror** [comment]
<img width="530" alt="image" src="https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/49a71b7a-3a54-42a8-b80c-39d95009a50f">

Rather than that large angry error message you'll get this smaller message that tells you exactly how to resolve the issue so that you can save your changes.

**Comment by sewcialite** [comment]
This is working well. Appreciate the quick fix.

**Comment by sewcialite** [comment]
I received this error again on a different [order](https://ops.acceleratenetworks.com/Home/Order/40fcd0e6-3eef-49f4-9175-e2252601f79e), but the new style error message did not happen.

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/6408fe5d-e759-4b8f-a568-89916c239e8f)

Text of the error:
Failed to update this order! 😠 Call failed with status code 404 (Not Found): GET https://billing.acceleratenetworks.com/api/v1/quotes/2339 at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response) at NumberSearch.DataAccess.InvoiceNinja.Invoice.GetQuoteByIdAsync(String invoiceId, String token) in /home/vsts/work/1/s/NumberSearch.DataAccess/InvoiceNinja/Invoice.cs:line 77 at NumberSearch.Ops.Controllers.OrdersController.OrderUpdate(Order order) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/OrdersController.cs:line 476

**Comment by sewcialite** [comment]
Hello, I encountered this error again with the same steps to replicate as above. [Order](https://ops.acceleratenetworks.com/Home/Order/56253120-7d0e-4fa9-af47-2d466b16b989)

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/36828f77-1174-4336-ab16-0ca59e9058d5)

Text of the error:

**Comment by uncheckederror** [comment]
> Hello, I encountered this error again with the same steps to replicate as above. [Order](https://ops.acceleratenetworks.com/Home/Order/56253120-7d0e-4fa9-af47-2d466b16b989)
> 
> ![image](https://user-images.githubusercontent.com/87674023/267122170-36828f77-1174-4336-ab16-0ca59e9058d5.png)
> 
> Text of the error: Failed to update this order! 😠 Call failed with status code 404 (Not Found): GET https://billing.acceleratenetworks.com/api/v1/quotes/2885 at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response) at NumberSearch.DataAccess.InvoiceNinja.Invoice.GetQuoteByIdAsync(String invoiceId, String token) in /home/vsts/work/1/s/NumberSearch.DataAccess/InvoiceNinja/Invoice.cs:line 77 at NumberSearch.Ops.Controllers.OrdersController.OrderUpdate(Order order) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/OrdersController.cs:line 476

For this order all 3 of the billing system Ids are in the old, no longer supported format. You can resolve this error by deleting them or replacing them with the current billing system Ids.
