### ISSUE TITLE
[FEATURE] Pagination on the orders page

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#399]
**What is the problem that this feature solves?**
I'm frustrated when I click on an order in [ops](https://ops.acceleratenetworks.com/Home/Order), update it, and it sends me back to page 1 even though I am on page 46. There is no easy way to get back to page 37 (or whatever page I am on) without clicking through all the pages. 

**Describe the solution you'd like**
I am not sure what the best solution would be. A few ideas I brainstormed were: 1) being able to type a page number in the address bar, 2) having a number input box at the page number clicker at the bottom or 3) infinite scroll:sparkles:

**How will this improve revenue or reduce our costs?**
I could get my work done faster and charge you less money. Also, it will make me less angry at ops. 

UGH I NEED TO GET TO PAGE 32 :grimacing: 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/4d1f11fd-6c90-421f-9075-c7e66591a634)

**Comment by sewcialite** [comment]
I would also appreciate the page selection to be put at the top of the page as well as the bottom of the page :pleading_face:

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/3203785b-7821-4ed3-9455-f3ca4be9b184)

**Comment by uncheckederror** [comment]
Okay, give the new orders page a try and tell me what you think @sewcialite
