### ISSUE TITLE
List all purchased numbers from each vendor, label numbers when ordering through Teli

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#40]
Can we export a CSV or table of what numbers were purchased from each vendor and for who?

Additionally, for Teli can we set the note to be the customer's business name followed by the person who placed the order's name, eg: Accelerate Networks - Dan Ryan

[This is API to set notes](https://apidocs.teleapi.net/api/my-phone-numbers/change-note-on-did) on Teli, sadly BulkVS and Endstream do not support labeling DIDs, hence the CSV to allow manual reconciliation of owned DIDs on each vendor.

**Comment by uncheckederror** [comment]
I have verified with @danry25 that this feature is now implemented.
