### ISSUE TITLE
[FEATURE] Contracts Quickly Available

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#400]
**What is the problem that this feature solves?**
It would be helpful to be able to quickly see when a client is under contract and/or the terms of their contract with AN. 

**Describe the solution you'd like**
I would like something to be visible in ops or on InvoiceNinja to show when a client has a contract. 

**How will this improve revenue or reduce our costs?**
Not having this feature cost us an ETF.

**Comment by uncheckederror** [comment]
Where do we keep the client contracts?

**Comment by danry25** [comment]
Formerly in Nextcloud (which both Scott and I have a copy of), future is TBD.

I'm open to attaching it in the billing system to the client or somewhere in Ops.

**Comment by sewcialite** [comment]
@danry25, per last week's meeting, and me looking at my notes, I made a [folder](https://drive.google.com/drive/folders/1gSF9Tz7fpzE9tEceYQgEwclTUHTU4d6V?usp=drive_link) in the google business account.

**Comment by danry25** [comment]
Closing as we have a business process to handle this now.
