### ISSUE TITLE
[BUG] Failed to Search a Number

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#403]
**What is broken?**
A clear and concise description of what the problem is.

**To Reproduce**
1. Go to https://acceleratenetworks.com/Search?Query=5648675309

**Expected behavior**
The current carrier and caller ID should be shown

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/71784487/b7907449-fe52-4904-87ae-9ea62c7b2402)

**Comment by uncheckederror** [comment]
@scottstrong206 can you give me some background info on this phone number? When we ask BulkVS about it, they claim it's not portable.

**Comment by uncheckederror** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/a1462127-a680-4c07-abdb-063b4f1b6824)

According to BulkVS's documentation this 404 response means that the phone number isn't portable.

**Comment by uncheckederror** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/b5a5cf4b-d1ba-4fa0-b8e6-34f61e7e42b3)
Alright I've updated the porting page to give a clearer error message in this scenario.

**Comment by uncheckederror** [comment]
@scottstrong206 @danry25 this number no longer leads to an error: https://acceleratenetworks.com/Search?Query=5648675309
