### ISSUE TITLE
[BUG] Cannot save PO Box Addresses

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#405]
**What is broken?**
I am trying to update an order. I cannot add a PO Box as an address

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/Order/f12b9b04-fa37-480d-8265-66dbf7f5eca1
2. Try to add their PO address
3. Cannot save address

**Expected behavior**
Save PO addresses in address field.

**Comment by uncheckederror** [comment]
@sewcialite I think PO Box info would go in the Address Line 2 field, not the primary address field.

**Comment by sewcialite** [comment]
OK should I update this request to say, "Address field is required, so I cannot update an order that has the client at a PO Box because the form expects me to fill out an address"

**Comment by sewcialite** [comment]
I cannot take a screenshot, but with this order, I cannot close it using the "remove 4 digit invoice number, mark complete, hit update" process because it is requiring an address to be put in the address field.

**Comment by uncheckederror** [comment]
Okay, do we not have an address for this client? I suppose you could use a fake address like Dan's.

**Comment by sewcialite** [comment]
All of their orders have shipped or come from PO BOX 1422 Lake Stevens Washington 98258

**Comment by uncheckederror** [comment]
Looks like that should work?
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/5436e3ab-2f70-420f-994a-0efc82296970)

**Comment by sewcialite** [comment]
Thank you, that worked. 

I added this to the ops guide
