### ISSUE TITLE
[FEATURE] Email Stripe payment failures to Support

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#406]
Could payment failures be emailed to support?

Ideally support would review the payment methods on file, remove the problematic payment method, re attempt processing payment with another payment method on file, and failing that contact the customer to add a valid payment method.

_Originally posted by @danry25 in https://github.com/AccelerateNetworks/NumberSearch/issues/327#issuecomment-1721947878_

**Comment by uncheckederror** [comment]
#327 "Payment issues have also cropped up, with Stripe saying the only way to be notified when a payment attempt fails is by listening to charge.failed or payment_intent.payment_failed failed event via webhooks:
https://stripe.com/docs/api/events/types#event_types-charge.failed
https://stripe.com/docs/api/events/types#event_types-payment_intent.payment_failed
https://stripe.com/docs/webhooks"

**Comment by danry25** [comment]
Closing as it seems out of scope for the NumberSearch project to be patching over holes in Stripe's platform
