### ISSUE TITLE
[FEATURE] Show Tracking to Clients in Completed Order View

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#407]
**What is the problem that this feature solves?**
Clients can see tracking!

**Describe the solution you'd like**
Tracking to be visible somewhere you desire on the webpage once tracking has been entered in ops

**How will this improve revenue or reduce our costs?**
It will make clients happy

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/e837160b-448f-4fa1-9685-f368dd9a7f54)

**Comment by uncheckederror** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/ec2b9d86-c654-49dc-8a76-f78d32dddf91)

**Comment by uncheckederror** [comment]
Try it out: https://acceleratenetworks.com/cart/order/eff0df15-b5da-4b4b-9920-7544140e4240
