### ISSUE TITLE
[FEATURE] Update Login Screen

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#408]
**What is the problem that this feature solves?**
It's not a problem, its just cluttered with old services we do not use anymore. 

**Describe the solution you'd like**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/a5e7720b-4f98-40ba-9862-fa8d8c8f971a)
I have the login link for everything but the webmail login. I think that's like witcher.mxrouting something? 

**How will this improve revenue or reduce our costs?**
It sure will look pretty.

**Comment by sewcialite** [comment]
Also, we don't use Aiden's nextcloud, we previously used Cascadian.cloud, which is now dead. 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/bfe89fbb-bddd-41c6-8ab2-3a2dc6565aab)

**Comment by uncheckederror** [comment]
> ... I have the login link for everything but the webmail login. I think that's like witcher.mxrouting something?

Can you give me a list of the new login links?

**Comment by sewcialite** [comment]
[TeleDynamics](https://www.teledynamics.com/#/home/dealer)
[osTicket](https://ticketing.acceleratenetworks.com/scp/)

I don't know the webmail login. That's a Dan question. 
And the github is just here on github

**Comment by uncheckederror** [comment]
Okay these changes are in.

**Comment by sewcialite** [comment]
This looks great! Thank you!
