### ISSUE TITLE
[BUG] 504 error on Messaging

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#409]
**What is broken?**
I cannot register users through "Messaging Users"

**To Reproduce**
1. Go to [Messaging Users](https://ops.acceleratenetworks.com/Messaging)
2. Fill in information in the "Register a Phone Number for Messaging Service"
3. Click Register
4. See 504

**Expected behavior**
It should register the user and not 504.

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/668544c1-a959-40c8-acb2-3fc24ff03def)

**Comment by uncheckederror** [comment]
This page kept timing out because it was trying to do too much work. To get around this problem I have drastically reduced the amount of work that it has to do now. The upside is that it loads much faster.

**Comment by sewcialite** [comment]
I don't have anything to test this with, so I am unsure how to proceed. Should I close it and assume it's good to go?

**Comment by uncheckederror** [comment]
@sewcialite is the Messaging Users page working for you now? If so, we can close this.

**Comment by sewcialite** [comment]
It loads much faster now, but I do not have a phone number to test registration, which is where it was 504ing for me

**Comment by danry25** [comment]
@sewcialite Mind trying your 2068589320 number?

**Comment by sewcialite** [comment]
This works! Yay!
