### ISSUE TITLE
Show purchased numbers on completed orders after the number is removed from database

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#41]
Currently when a number is ordered, we buy it with the upstream vendor. When the next ingest occurs, the number is removed from the database and zeros are shown in the order reference link that is emailed to the client and our orders team.

Can we show the ordered numbers persistently? Since we bought the number, the number not being available for purchase is expected behavior.

**Comment by uncheckederror** [comment]
You can visit this page to verify that this issue has been resolved.

https://acceleratenetworks.com/cart/order/d0ab6375-67a6-47a6-bc9a-7753e5731f52
