### ISSUE TITLE
[FEATURE] Check current SMS enablement - Track in Owned Numbers

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#411]
**What is the problem that this feature solves?**
We currently don't know what vendor holds SMS routing (NNID/eSPID) for a given phone number. This results in us not SMS enabling all phone numbers out of fear of breaking existing SMS enablement of a phone number.

**Describe the solution you'd like**
We can query for line type intelligence or carrier via Twilio to access this dataset where it exists. Make a query to https://lookups.twilio.com/v2/PhoneNumbers/+15108675310?Fields=line_type_intelligence and note the lineTypeIntelligence result.

API docs: https://www.twilio.com/docs/lookup/v2-api/line-type-intelligence

We should add two fields to Owned Numbers, one to contain the result line_type_intelligence and another that is 3rd Party SMS Vendor (according to Customer) so we can track who the actual SMS vendor is, and who the customer is paying for SMS services.

**How will this improve revenue or reduce our costs?**
Knowing this data will tell us what numbers have carrier_name's that aren't SMS enabled so we can do SMS enablement on these numbers without eliminating SMS enablements our clients have created without telling us, avoiding additional support burden from angry existing clients.

This will also allow us to prevent unauthorized SMS enablements by 3rd party vendors by SMS enabling every number with our preferred vendor and telling us which clients we need to follow up with and document their existing 3rd party provider, protecting our clients from SMS hijacking threats.

**When do we need to do this?**
On initial phone number ingest, and we also should have a button for support to re-run this check in Ops manually for a given phone number.

**Comment by danry25** [comment]
The SMS vendor query will be run once against all owned numbers with an Endsteam status of "Longcode not assigned to that account". The results will be displayed in owned numbers and as a column on the Messaging Users page. On the Messaging Users page there will be a button to run the query against a single owned number to get its current status with Twilio.

**Comment by uncheckederror** [comment]
@danry25 please give this a try here: https://ops.acceleratenetworks.com/Messaging

**Comment by danry25** [comment]
This looks good to me!
