### ISSUE TITLE
[BUG] Logo colors were flattened

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#412]
**What is broken?**
The arrow colors are incorrect in https://acceleratenetworks.com/images/scaled/accelerate.webp

**Expected behavior**
The image should look like this:
<img width="1198" alt="an" src="https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/af612d4a-b949-42b0-88de-ba7cde6978b5">

**Source Material**
Please use the xcf file sent to you.

**Comment by uncheckederror** [comment]
@danry25 Please verify this change is live in both Ops and the main website. You may need to clear your browser's cache.

**Comment by danry25** [comment]
Looks great in both Ops and on the main website, thanks Tom!
