### ISSUE TITLE
[BUG] - Cannot log into SMS via Swagger, 500 error

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#413]
**What is broken?**
I tried logging into the swagger page at sms.callpipe.com and got a 500 Internal Server error:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/6e73cb1f-4c21-495c-ae60-789630207e71)

**Expected behavior**
An authorization token should have been generated by this endpoint.

**Comment by uncheckederror** [comment]
@danry25 okay, I think this is fixed now. Please verify.
