### ISSUE TITLE
[BUG] Incorrect Carrier shown on Numbers In Bulk Lookups

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#414]
**What is broken?**
The Carrier for some phone numbers that we previously queried prior to porting is incorrect. This is due to the LRN query not being used when there is a cached result for a phone number in our database.

**To Reproduce**
1. Go to https://acceleratenetworks.com/Lookup
2. Enter (425) 348-9868
3. Press Search
4. See Verizon Wireless shown instead of the correct carrier

**Expected behavior**
Onvoy should be shown.

**Comment by uncheckederror** [comment]
@danry25 this fix is live. We are no longer using cached data for LRN lookups.
