### ISSUE TITLE
[FEATURE] Remove registered client from SMS.Callpipe.com

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#415]
**What is the problem that this feature solves?**
We are displaying numbers that have ported out in Messaging Users, as we are retaining routing information for SMSes for these numbers needlessly.

**Describe the solution you'd like**
Provide a button in Messaging Users in Ops to allow us to delete the SMS routing held in SMS.Callpipe.com if there is no upstream routing currently.

**How will this improve revenue or reduce our costs?**
This will make it easier to search Messaging Users while avoiding incurring support costs from SMS enabling non-client's numbers.

**Comment by uncheckederror** [comment]
To use this feature go to Messaging Users page and sort the numbers by the "Phone Number" column. Then click on a number with a "Remove" button. You should get a success message like the one shown in the screenshot below. Please try it out @danry25 

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/447244bc-8103-47f2-b73e-a7072f991c5d)

**Comment by danry25** [comment]
@uncheckederror How are we handling numbers like 9365824200 perchance?

**Comment by uncheckederror** [comment]
> 9365824200

Why does this number require handling?

**Comment by danry25** [comment]
9365824200 ported out a long time ago to a competitor (Weave), this phone number is currently not active under [Owned Numbers](https://ops.acceleratenetworks.com/Home/OwnedNumbers/9365824200), and we have a have a registration for it in sms.callpipe.com that I would like to remove so it does not show up in Messaging Users:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/564c0671-08cd-4627-81f3-5b99e18efaab)

**Comment by uncheckederror** [comment]
@danry25 search for that number in Ops now. If we can match an sms.callpipe.com registration to an inactive Owned Number then it will be marked as Removable on the Messaging Users page now.

**Comment by danry25** [comment]
Nice work @uncheckederror ! I see this button showing up now for 9365824200 which solves this issue :D

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/6a0dfa9e-4aa9-4064-a16b-5aa705594d59)
