### ISSUE TITLE
Order Doesn't Automatically Fill Information

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#416]
**What is broken?**
When adding Teledynamics order number to order in Ops, S/N and MAC didn't auto populate and no error code was given. Order updated with TD order number filled in.

**To Reproduce**
1. Go to order in Ops. (https://ops.acceleratenetworks.com/Home/Order/b2352d54-3e46-449b-af89-664e4c10c8f5)
2. Add Teledynamics order number.
3. Save and see nothing else happen.
4. Have to manually add MAC and S/N afterwards.

**Expected behavior**
According to @danry25 adding TD order number should automatically pull S/N and MAC address and fill that info in on the order form.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 118.0.1

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Comment by uncheckederror** [comment]
Per Dan I am hiding the details button. If an Order already has Product Items on it, delete them before using the "Link to TeleDynamics Order" button to regenerate them.
