### ISSUE TITLE
[BUG] Ops - New Order Search displays results multiple times

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#417]
**What is broken?**
Search appears to be broken in two distinct ways:
 - Searches sometimes show the same result multiple times (pictured below)
 - When there are no search results the list of all orders is shown (rather than a no results error)
 
 
 Both of these issues were introduced when resolving issue #399 which implemented a new search process. 

![Screenshot from 2023-10-13 16-16-09](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/210e7cb4-ed15-4715-b271-b95e6aa62a1d)

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/
2. Enter poss in the search field and click Filter
3. See multiple orders shown that all link to the same order page

**Expected behavior**
One order page should be shown.

Search UX across Quotes and Orders should be consistent.

**Comment by uncheckederror** [comment]
@danry25 what was the search query that produced this result?

**Comment by danry25** [comment]
Here is the query: https://ops.acceleratenetworks.com/?Query=poss

**Comment by uncheckederror** [comment]
@danry25 a build of Ops is live please try it out, I believe it solves these issue. Have you tried clicking on the options suggested by the search bar as you type?

**Comment by danry25** [comment]
The new build fixes the search issue, thanks @uncheckederror !

Search completion options appear to only be suggested in Chromium and not in Firefox based on my testing:

https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/b4cf92cc-bec4-411e-81a4-b5dd141b0239
