### ISSUE TITLE
[BUG] Title incorrect in Order Confirmation Email

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#418]
**What is broken?**
When an order is placed, a confirmation email is sent with a title like "Quote 10211 from Accelerate Networks" when this should ideally say "Order 10211 - Accelerate Networks"

Affected order: https://ops.acceleratenetworks.com/Home/Order/e578ab5d-32e3-4756-af6e-6d41dfc72825
Related email: https://ops.acceleratenetworks.com/Home/Emails/e578ab5d-32e3-4756-af6e-6d41dfc72825

**To Reproduce**
1. Go to AccelerateNetworks.com
2. Order a phone number
3. Receive an email that references your order as a quote

**Expected behavior**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/7a0a53e6-48d2-4f32-9d09-a0cba6c44c30)

**Comment by uncheckederror** [comment]
@danry25 I believe this is fixed now.

**Comment by danry25** [comment]
@uncheckederror Part of the wording change happened, but it is still being referenced as a quote:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/5247249d-3504-4fa9-bb48-4622645115c4)

**Comment by uncheckederror** [comment]
@danry25 alright try it now.

**Comment by danry25** [comment]
Ayyy, 3rd time is the charm :wink: 

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/74c62a28-e384-4a8c-80af-dabcdb16fd77)

Thanks for your hard work on this @uncheckederror !
