### ISSUE TITLE
[FEATURE] Ops Order Search Suggestions - Add Firefox Support

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#419]
**What is the problem that this feature solves?**
Searching orders shows suggestions of matching queries in Chrome and Chromium, but not in Firefox. This is a time saver that our team would appreciate having work in Firefox given the majority of the support team uses Firefox primarily.

Video of the feature gap: https://github.com/AccelerateNetworks/NumberSearch/issues/417#issuecomment-1763281360

**Comment by uncheckederror** [comment]
@danry25 okay, a new build is live in Ops. Please try it out in Firefox.

**Comment by danry25** [comment]
Seems to work for my oddball queries!
