### ISSUE TITLE
[BUG] Some Support Videos for DP722 point to DP720 Video on YouTube

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#420]
**What is broken?**
On the support page for the DP722 the first 2 videos point to the DP720 version of the video.

**To Reproduce**
1. Go to acceleratenetworks.com
2. Click on Suppot
3. Scroll down to DP722
4. See error in list.

**Expected behavior**
There is a DP722 specific video for both of those things that can be seen in this playlist. https://www.youtube.com/playlist?list=PLy8FSfLD62uPCyGUdT1bpxa5nCPiIzof_

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 118.0.1

**Smartphone (please complete the following information):**

**Comment by uncheckederror** [comment]
This fix is live: https://acceleratenetworks.com/Phones/DP722
@Chattaeus please verify the fix and then close this issue.

**Comment by Chattaeus** [comment]
Fix is good.
