### ISSUE TITLE
[BUG] Teledynamics order adding in ops not working

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#421]
**What is broken?**
I tried to add a Teledynamics order number to an ops order and got a nasty error

**To Reproduce**
1. Go to an order in ops
2. add the teledynamics order number
3. See error

**Expected behavior**
It's supposed to give me :tada: and be green

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/7265c664-edf2-489e-aba6-6ed41a8b1424)

Error.
An error occurred while processing your request.
Request ID: 00-054cf6925f4fdc549411d69a01303ce4-bdc5116cad3a22c5-00
Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by danry25** [comment]
Verified this did not work when attempting to link TeleDynamics order 0007746447 with [this order](https://ops.acceleratenetworks.com/Order/614facb7-3dc7-444f-b81d-9a683e421350)

Here is the URL used to link these two, below is the result: https://ops.acceleratenetworks.com/Order/614facb7-3dc7-444f-b81d-9a683e421350/CreateProductItems?teleDynamicsOrderNumber=0007746447

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/16ca9663-0d0b-4aa2-8ff2-8e453ebe643a)

**Comment by uncheckederror** [comment]
The fix for this is live.

**Comment by danry25** [comment]
Success! Thanks @uncheckederror 

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/50cc50ac-39e6-48a8-82f0-2fbaf298d419)
