### ISSUE TITLE
[BUG] Ops - 504 Gateway Timeout when registering a messaging client in Messaging users

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#423]
**What is broken?**
When I click the Register button on https://ops.acceleratenetworks.com/Messaging the page 504 Gateway Timeouts (but the registration does occur correctly)
![Screenshot from 2023-10-26 11-07-35](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/a696c97f-933a-45f3-a257-cdbc9798ac4e)

**Expected behavior**
The registration does occur correctly, its only the webpage that shows a 504 gateway timeout.

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/c53948e5-bbed-447e-9726-9843575dfa7e)

**Comment by uncheckederror** [comment]
I am not able to reproduce this issue. Perhaps next time it happens we can get some logs?

**Comment by danry25** [comment]
I'm pretty sure this issue is due to the client having thousands of messages that got replayed when the registration was triggered. Can we mark all messages prior to message tracking as delivered?

**Comment by uncheckederror** [comment]
> I'm pretty sure this issue is due to the client having thousands of messages that got replayed when the registration was triggered. 

Okay, that could certainly lead to a time out. We could set an upper limit on replaying failed messages. Perhaps 5 messages max?

> Can we mark all messages prior to message tracking as delivered?

I don't understand what this means. Can you be more specific? All messages received by sms.callpipe.com are "tracked".

**Comment by danry25** [comment]
All messages handled by SMS.Callpipe.com before the message replay feature was implemented are marked as not delivered, unless the client has been re-registered since then.

There appears to be some rate limiting logic for message delivery, only two to three messages per minute would be delivered to the SMS client during the replay period. If there is a replay limit implemented, I would like it to be 50 to 100 messages (or higher).

**Comment by uncheckederror** [comment]
@danry25 I think this is fixed, please try reregistering a client.

**Comment by danry25** [comment]
This appears to be fixed, closing.
