### ISSUE TITLE
[BUG] Failed Outbound MMS is reported as Upsellable

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#427]
**What is broken?**
We list 12063801161 as being upsellable to web texting instead of highlighting that this was a misformatted outbound MMS.

**Expected behavior**
List Outbound messages that failed in a separate section, eg Failed Outbound Messages. Relabel Failed Messages in the last 3 Days to Failed Incoming Messages (last 3 days)

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/3a1e9543-d3c1-4f94-bcfc-69c096028f6d)

**Comment by uncheckederror** [comment]
@danry25 This bug is fixed, please review it in Ops now. https://ops.acceleratenetworks.com/Messaging/Failed

**Comment by danry25** [comment]
Thanks for fixing this messaging upsell bug @uncheckederror !
