### ISSUE TITLE
[BUG] Text inaccurate when removing registration

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#428]
**What is broken?**
The text says " ✔️ Reregistration removed! "The registration for 2063291864 has been removed." "

**To Reproduce**
1. Go to Messaging Users and Remove a number, which should take you to a URL like https://ops.acceleratenetworks.com/Messaging/Remove?dialedNumber=2063291864
2. See error

**Expected behavior**
" ✔️ Registration removed! "The registration for 2063291864 has been removed." "

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/8f1c9483-a243-4b95-a509-8409fe9c4dfe)

**Comment by uncheckederror** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/e07d5406-ed48-4659-af65-3441b3fe6db3)

Can you provide any additional information on what you were doing when this bug occurred? I cannot reproduce it.

**Comment by danry25** [comment]
The only "bug" here is the flavor text needs to be updated when a number is removed from Messaging Users.

We don't have any numbers that are removable from Messaging Users at this time to reproduce this bug with.

**Comment by uncheckederror** [comment]
> The only "bug" here is the flavor text needs to be updated when a number is removed from Messaging Users.

The success message does tell you when a number is unregistered from sms.callpipe.com. As shown in both your screenshot and my screenshot. 

> Go to Messaging Users and Remove a number, which should take you to a URL like https://ops.acceleratenetworks.com/Messaging/Remove?dialedNumber=2063291864
> See error

I see no error message, the registration removal is successful. What do you think is wrong here?

The number in your text and the number in your screenshot are different. But I don't understand how you tried unregistering one number and end up registering another number. Can you please explain what you were doing that caused this page to error out?

**Comment by uncheckederror** [comment]
I see the 2 character difference between
> ✔️ Registration removed! "The registration for 2063291864 has been removed.
and
> ✔️ Reregistration removed! "The registration for 2063291864 has been removed.
where the existing string has "re" as its 3rd and 4th chars.

In the future please try to **emphasize** the minor changes you want made to text and leave out extraneous information.
