### ISSUE TITLE
Integrate with Peerless Networks as a new vendor?

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#43]
They seem to have [a decent API](https://app.swaggerhub.com/apis/Peerless/PeerlessPortal/1.3.1#/) and tons of available numbers, it might make sense to pull Peerless Networks into the mix.

**Comment by uncheckederror** [comment]
Peerless appears to have some sort of API rate limiting that we keep running into. This is making it hard to get consistent results from the ingest process. We need to work out a way to move past this rate limiting with them and then the next step is to figure out how to purchase phone numbers through their API.

- [ ] Fix the API rate limiting.

- [ ] Implement purchasing numbers.

**Comment by uncheckederror** [comment]
We are pausing work on integrating with Peerless until we can work out some solution with them to get around the API rate limiting. After we hit the limit not only can we not query for more numbers, but we can't query to verify that specific numbers still exist, or submit purchase orders. Until we get these blockers resolved there's nothing more to do here.
