### ISSUE TITLE
[BUG] Ops - Force Send does not work

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#431]
**What is broken?**
Using Force send to resend a sent or failed email does not work.

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/Emails/d2b45339-be38-44d4-a644-6701687cdc30
2. Click on Force Send
3. See error

**Expected behavior**
The email should be resent to the end user.

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/1b868863-67db-4723-981a-ff124049a3f4)

**Comment by uncheckederror** [comment]
@danry25 please retry force sending an email.
