### ISSUE TITLE
[FEATURE] Add "Fiber Internet" onto "Services We Provide" 

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#432]
**What is the problem that this feature solves?**
Fiber is so hot right now. We really want folks who are looking for keywords to find the keywords they are looking for through Accelerate.

**Describe the solution you'd like**
I am curious how @danry25 feels about swapping one of the lesser purchased services out for a blurb about Fiber Internet? 

"Fiber Internet"
Lightning Fast Communication
Upload and download files quickly
Up to xxGB speeds

**Comment by uncheckederror** [comment]
I believe at one point we did have an option for Fiber internet.

Perhaps we could drop this option and replace it with Fiber?

LTE Backup
$30 / mo
Always stay online!
No Overages
No Worries
Unlimited Use

Although I am unclear about what we are actually deploying to customers for cellular network modems. Are 5G Internet, 5G Internet - Static IP, and LTE Backup actually all the same thing?

**Comment by danry25** [comment]
None of our branded internet options are fiber based, only our partners like Ziply Fiber (BFI), Lumen (Fiber+ and DIA) and Astound (BCI or DIA) offer fiber internet services.

Adding this under services is not appropriate given we don't offer this as a service you can just add to your basket.

**Comment by uncheckederror** [comment]
@danry25 can we close this then?

**Comment by danry25** [comment]
Reopening with some proposed changes inspired by @sewcialite 
- Move the bottom call to action up the page above "We proudly participate in"
- Change the newly moved sections wording to "Connecting you with faster Fiber, Wireless and Wired Internet!" and "Help your business move faster & communicate better with quicker internet, better phones and seamless texting."
- Integrate https://pixabay.com/vectors/email-fast-service-internet-1975010/ or a similar image that evokes the idea of fast internet into this section

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/a4d45584-c498-4dd7-81d7-658cba5f1478)

**Comment by uncheckederror** [comment]
> * Integrate https://pixabay.com/vectors/email-fast-service-internet-1975010/ or a similar image that evokes the idea of fast internet into this section

Thank you for the screenshot of the changes, it made what you wanted clear. Those changes are live. 

Where do you want this "fast email" image placed?

**Comment by danry25** [comment]
I don't think the fast email image fits in in retrospect, this change looks quite a bit better than what was there before though. Thanks @uncheckederror !
