### ISSUE TITLE
[FEATURE] Return "Bulk Changes" in FusionPBX

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#433]
**What is the problem that this feature solves?**
I am always frustrated when I need to push bulk changes in Fusion and that option isn't there anymore

**Describe the solution you'd like**
I would like to have permissions to make bulk account changes again

**How will this improve revenue or reduce our costs?**
Not having this feature makes Dan annoyed I forget about Status > Registrations

**Comment by uncheckederror** [comment]
@sewcialite FusionPBX is @danry25's responsibility. If you need additional permissions then @danry25 can grant them.

**Comment by danry25** [comment]
@sewcialite This is not the FusionPBX repository. Closing this issue.
