### ISSUE TITLE
[BUG] Ops - Messaging Users, setting SMS to Email on a previously non-SMS enabled phone number does not work

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#434]
**What is broken?**
When registering a phone number for SMS to Email service, the SMS are routed to EPID 265 by accident if the phone number was not previously SMS enabled prior to setting SMS to Email

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Messaging/ToEmail
2. Enter a phone number that hasn't previously been SMS enabled and email under "Register a Phone Number for Messaging to Email Service"
3. Press Register
4. Wait until the phone number is registered
5. Note how its routed to EPID 265 rather than to an email address.

**Expected behavior**
The background SMS enablement process should run the sms to email SOAP endpoint rather than routing to EPID 265 when invoked by the "Register a Phone Number for Messaging to Email Service" form.

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/e48aec57-b6e9-4f41-8f9b-b8131a9ea473)

**Comment by uncheckederror** [comment]
@danry25 I believe this is working now. Please try it out.

**Comment by danry25** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/84c1fbf7-e63e-4e2c-8464-bfd58ec8e20f)
Looks like this is giving the appropriate warning now.
