### ISSUE TITLE
[BUG] Ops - Domain and Destination not ingested from FusionPBX

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#435]
**What is broken?**
Ops is showing that no domain or destination are set for a phone number, yet the number has been routed for weeks in FusionPBX:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/b4b1c9b9-54ff-4644-ad1b-5195ae4f4cc4)

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/OwnedNumbers/
2. Search 8482382512
3. Go to https://acceleratenetworks.sip.callpipe.com/app/destinations/destination_edit.php?id=705801d9-5f23-4318-ad44-7f1ef696392d
4. See the difference in what is shown (8482382512 is obviously routed in FusionPBX, but this does not reflect accurately in Ops)

**Expected behavior**
The domain and destination fields should list the routing instead of saying this in the FusionPBX column "No Destination found in FusionPBX." and "No Domain found in FusionPBX."

**Comment by uncheckederror** [comment]
Looks like we got back no data on a recent run. I've just re run it, and now there's valid data.

**Comment by uncheckederror** [comment]
Data still looks correct in Ops tonight.

**Comment by uncheckederror** [comment]
We got back no data on the run last night. I've added a check that will skip the process if we don't get a valid response for the AN Support number.

**Comment by danry25** [comment]
Closing as I confirmed this is fixed.
