### ISSUE TITLE
[BUG] Daily Emails not being sent since 11/16

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#437]
**What is broken?**
We have not been receiving the daily ingest emails from ops since 11/16. 

**Expected behavior**
Daily emails alerting us to the status of ops and current orders.

**Screenshots**
Last email received was 10am on 11/16. 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/41884c02-f5c8-40ef-a88a-4bd5adc2c040)

**Comment by danry25** [comment]
This issue is resolved:

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/6d09e4ba-fc28-4735-b6d5-7d931d33ef92)
