### ISSUE TITLE
[FEATURE] Include phone numbers that no longer have SMS provisioning in Daily Briefing emails

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#439]
**What is the problem that this feature solves?**
Occasionally a phone number that was Registered Upstream will become unregistered (and show a status of False). Informing our support team in the daily briefing email so they can correct this would be a good way to increase customer satisfaction and reduce how many tickets we receive.

**Describe the solution you'd like**
Include a section in the Daily Briefing email listing "Recently Unregistered Texting Numbers", which would be any number in https://ops.acceleratenetworks.com/Messaging that had its "Registered Upstream?" status change to False.

**How will this improve revenue or reduce our costs?**
Handling these edge cases without user interaction saves labor hours, and minimizes the problem for our clients.

**Comment by danry25** [comment]
Blocked by https://github.com/AccelerateNetworks/NumberSearch/issues/438

**Comment by uncheckederror** [comment]
@danry25 this has been live for the last week in the daily emails. Is it working the way you want?

**Comment by danry25** [comment]
I haven't seen it come up, but perhaps that is an issue I need to address as part of offboarding.

**Comment by danry25** [comment]
I have been benefiting from these being in the daily briefing emails, thanks for adding this!
