### ISSUE TITLE
[FEATURE] Adding Quote Status Indicator, Sales Notes field, and easy number lookup button

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#441]
**What is the problem that this feature solves?**
- We don't know if each quote is won, lost or in progress
- We don't have a good place to track sales notes (that should not be shown to the client)
- It is cumbersome to look up numbers that are being ported in that are already associated with an order to see if the customer has ported these to a competitor recently

**Describe the solution you'd like**
- Add a dropdown only viewable in Ops that says Won, Lost or In Progress, and set it to In Progress by default, show 
- Create a freeform text field like Notes that is only viewable in Ops, and label this as Sales Notes or Internal Notes
- Make a button on quotes that include ported numbers that sends you to the lookup page and prefills the numbers to lookup

All three of these should be visible on https://ops.acceleratenetworks.com/Home/Quotes and we should also make the Rep assigned to a quote visible on this page as well.

**How will this improve revenue or reduce our costs?**
This will allow our sales team to triage quoted leads more effectively, saving their labor for interacting with potential clients to generate new revenue.

**Comment by danry25** [comment]
All that remains to do on this task are:
- [ ] Add a dropdown only viewable in Ops that says Won, Lost or In Progress, and set it to In Progress by default, show
- [ ] Make a button on quotes that include ported numbers that sends you to the lookup page and prefills the numbers to lookup

**Comment by uncheckederror** [comment]
@danry25 these changes are live in Ops, please try them out!
