### ISSUE TITLE
[FEATURE] Export to CSV from Quotes

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#442]
**What is the problem that this feature solves?**
It would be very helpful to be able to obtain a spreadsheet of quoted deals so we can do data analysis on outstanding quotes.

**Describe the solution you'd like**
Add an Export to CSV button like the Owned Numbers page has

**How will this improve revenue or reduce our costs?**
This will enable easier quote auditing and management, allowing us to drive engagement with the sales team to use Ops.

**Comment by uncheckederror** [comment]
This button is live on the bottom of the Quotes page, enjoy!

**Comment by danry25** [comment]
Thanks for adding the export feature @uncheckederror , I tested it just now and it seems to work quite well!
