### ISSUE TITLE
[BUG] Flavor text on Port Completion emails lists wrong time of day

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#443]
**What is broken?**
When a confirmation email is sent to the customer notifying them the port request has completed, a time of 9am PDT is mentioned.

Looks like the wording error is on this line: https://github.com/AccelerateNetworks/NumberSearch/blob/dc421c56b2bfccb9408e79927377c4e608d4b9ec/NumberSearch.Ingest/PortRequests.cs#L156

**Expected behavior**
The port request completion notification email should state that port requests usually complete at 5pm Pacific Time.

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/f751de13-f882-4200-a122-9dc7906bec83)

**Comment by uncheckederror** [comment]
Looks like the fix for this bug is live, please retest @danry25.
