### ISSUE TITLE
[BUG] Date Listed on port request submission page incorrect

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#444]
**What is broken?**
The date shown on the port request submission success page (for the end user on AccelerateNetworks.com) shows the original order date, not today's date.

**Expected behavior**
Today's date should be shown

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/ca4dc27b-b664-47aa-a498-0d9595605809)

**Comment by uncheckederror** [comment]
I have changed this message to use the date that the Port Request was last updated, which should be the current time and date if you've just submitted it.
