### ISSUE TITLE
[FEATURE] Track the date a quote becomes an order

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#445]
**What is the problem that this feature solves?**
Currently the Orders list shows many inaccurate dates for quoted clients that were quoted months ago, but only converted to orders recently (putting them much further down the list).

**Describe the solution you'd like**
Update the timestamp of the order when it is converted to an order, save the date of the original quote and note it somewhere.

**How will this improve revenue or reduce our costs?**
Not having this feature makes analyzing how quickly we close out quotes harder.

**Comment by uncheckederror** [comment]
The field that tracks that in the db is named "DateConvertedFromQuote".
