### ISSUE TITLE
[BUG] - Outdated sales tax rate applied on new quote

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#447]
**What is broken?**
The wrong tax rate is being applied to new quotes and invoices.

Affected quote: https://ops.acceleratenetworks.com/Home/Order/4f76e0a1-0fff-46d3-baec-a5908eecc9fb

**To Reproduce**
1. Go order a product and use an address in the 98199 zip code (Seattle tax location code 1726)
2. Click on the invoice
3. Scroll down to the bottom of the invoice
4. See the outdated tax rate

**Expected behavior**
The current 10.25% rate for location code 1726 should be applied

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/cc2fb79c-5d40-44fe-a482-22a5a5025d04)
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/85c58ba8-4465-4635-85fb-30e74f729d33)

**Comment by uncheckederror** [comment]
A new build is live with the Q1 2024 data.
