### ISSUE TITLE
[BUG] Lookups fail for some phone numbers consistently

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#449]
**What is broken?**
I cannot lookup 4252008183 on https://acceleratenetworks.com/Lookup/BulkPort

**To Reproduce**
1. Go to https://acceleratenetworks.com/Lookup/BulkPort
2. Fill in 4252008183
3. Press Search

**Expected behavior**
A carrier of Verizon Wireless should be shown, just like the LRN query shows:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/7765ee4d-8c28-4942-9f60-7b029447cf87)

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/f9efb7c5-3dfd-4ff9-9bc8-f1f18f440206)

**Comment by uncheckederror** [comment]
@danry25 Please retest this issue. I believe that the fix is now live. 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/2b046fec-ae56-4796-b948-7473089efeea)
