### ISSUE TITLE
Fix next button on Ops application

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#45]
This seems to be the same bug as issue #38 where the next button is disabled on the 2nd to last page of results, though it is affecting the ops application and preventing users from going to the last page of available numbers after logging in and navigating to Numbers => Numbers and searching for available numbers.

![Screenshot from 2020-07-19 16-36-36](https://user-images.githubusercontent.com/1683673/87887944-42459300-c9de-11ea-846e-d95fa970aa68.png)

**Comment by uncheckederror** [comment]
@danry25 Can you verify that the Ops app has been added to the systemd file. Run this command "sudo systemctl restart numbersearch.service" in the release pipeline doesn't seem to be restarting the app on the web server.
