### ISSUE TITLE
[BUG] Lookup - Export to CSV no longer works

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#450]
**What is broken?**
The Export to CSV button is not functional

**To Reproduce**
1. Go to ['...'](https://acceleratenetworks.com/Lookup/BulkPort?dialedNumber=4252008183&csv=true)
2. See error

**Expected behavior**
A CSV should be delivered to the user containing data on the queried numbers.

**Comment by uncheckederror** [comment]
I have verified that this bug is reproduceable.

**Comment by uncheckederror** [comment]
This bug was introduced when we started requiring an Anti-Forgery token as part of the form POST submission in order to block certain kinds of scraping attacks. I have update the button to make a POST, rather than a GET request to generate the CSV.

@danry25 please retest.

**Comment by danry25** [comment]
It works, woo!
