### ISSUE TITLE
[BUG] Cannot add a toll free number to port request

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#451]
**What is broken?**
8662122226 cannot be added to [this port request](https://ops.acceleratenetworks.com/Home/PortRequests/eb102ab7-730a-44f1-bf40-49af3a108885).

Non-Toll Free numbers are able to be added without issue.

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/PortRequests/eb102ab7-730a-44f1-bf40-49af3a108885
2. Click on Add at the bottom of the page after filling in 8662122226 
3. See error

**Expected behavior**
Number should be added to the port request.

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/1cee935d-15b8-40e1-ac9a-23f71afe71fe)

**Comment by uncheckederror** [comment]
I have verified that this bug is reproduceable in Ops.

**Comment by danry25** [comment]
This bug is resolved
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/605e3a5d-aaec-47f4-bf27-95edb0b92f9a)
