### ISSUE TITLE
[BUG] Ops - Carrier Lookups, Match Existing and Verify Matches fails

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#453]
**What is broken?**
A clear and concise description of what the problem is.

**To Reproduce**
1. Go to [Ops - Carrier Lookups](https://ops.acceleratenetworks.com/Lookups)
2. Click on Match Existing or Verify Matches
3. Watch the application hang
4. See out of memory error

**Expected behavior**
The application should not run out of memory.

**Comment by uncheckederror** [comment]
We had too many records in the PhoneNumberLookups table so I cloned it to the phonenumberlookupsarchive table and then truncated it.

**Comment by uncheckederror** [comment]
@danry25 I believe this is resolved. Please retest it.
