### ISSUE TITLE
[FEATURE] Show voice routing destination in Owned Numbers

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#456]
**What is the problem that this feature solves?**
Sometimes phone numbers are routed to the wrong server, it would be helpful if Owned Numbers could nab the Trunk value from our carriers and display this so we know where a number is routing.

**Comment by uncheckederror** [comment]
Where is this information stored? When you say "our carriers" are you talking about looking up the number in FusionPBX, BulkVS, or FirstPointCom? The Trunk value you're looking for, is it a phone number or a URL? What value are you expecting to see?

**Comment by uncheckederror** [comment]
From /tnRecord in the BulkVS API display Routing => Trunk Group as the Trunk and Lidb as Caller Name in the Owned Numbers records. 

From FirstPointCom we reaching out for more info.

**Comment by uncheckederror** [comment]
I've updated the Owned Numbers, Owned Numbers Edit, and Messaging Users pages in the Ops app to show the Trunk Group values ingested by the Ingest app through the Owned Numbers ingest process from BulkVS. The data displayed on these pages is updated daily.

**Comment by uncheckederror** [comment]
@danry25 okay, give it a try and tell me how to make it better.
