### ISSUE TITLE
[FEATURE] Override ZIP Code with 1

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#458]
**What is the problem that this feature solves?**
We want the ability to trigger manual processing of a port request so that the notes under Partial Port are read by the porting team before submitting the port request.

**Describe the solution you'd like**
We have been told that instead of submitting a valid value for the ZIP code, submit just 1 and this will stop the fully automated port request processing flow.

**How will this improve revenue or reduce our costs?**
This will allow us to ensure the port requests are processed more smoothly.

**Comment by uncheckederror** [comment]
@danry25 okay, this feature is in. There is a small checkbox above the Submit button on the Port Request Edit page that you can check to overwrite the ZIP field with a 1 and force BulkVS to manually process the Port Request.

**Comment by danry25** [comment]
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/446aea47-c1fb-435a-a989-fd69b2d641f2)
