### ISSUE TITLE
[BUG] Service Address Typeahead Broken

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#459]
**What is broken?**
The Service Address field on a Port Request in Ops doesn't contain the properly formatted address, and no typeahead is offered.

**To Reproduce**
1. Go to a port request
2. Click on Update
3. See error

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/1091e236-4341-4d6b-bf1e-910a4c5eb790)

**Expected behavior**
The Service Address field should be populated by the full address by default, and typeahead should work on this field

**Comment by uncheckederror** [comment]
This typeahead works Win 11 Chrome and Edge. It also works on iOS Chrome and Safari.

**Comment by uncheckederror** [comment]
@danry25 this changes is live, please retest.

**Comment by uncheckederror** [comment]
> @danry25 this changes is live, please retest.

@danry25 please verify that the Service Address field in Ops is working as expected.

**Comment by danry25** [comment]
This bug is resolved, thanks @uncheckederror !
