### ISSUE TITLE
[FEATURE] Add button prompts to the bottom of Number Lookup page

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#461]
**What is the problem that this feature solves?**
Customers are not prompted to move on to checkout by the Number Lookup page, this UX is unclear and doesn't motivate them to complete the sale.

**Describe the solution you'd like**
Add two buttons to the bottom of this page.
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/856ab866-5d2b-474f-acfb-3123bdd49376)

**How will this improve revenue or reduce our costs?**
We will collect more port fees from self-serve users this way and make their onboarding process easier.

**Comment by uncheckederror** [comment]
@danry25 please verify that you are happy with the buttons on the Bulk page now.

**Comment by danry25** [comment]
Could we remove your from Review your Cart 🛒 so that it fits on one line in the mobile view of this page?

![Screenshot_20240619-223331](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/88d47f5a-85c0-4fd3-ab8e-4166cb6abd48)

**Comment by uncheckederror** [comment]
@danry25 okay, I have removed " your" from the Cart button.

**Comment by danry25** [comment]
Looking good!

![Screenshot_20240619-231657](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/639cd050-a727-4f29-8ecc-bf740b0460a0)
