### ISSUE TITLE
[FEATURE] Update Homepage Video

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#462]
**What is the problem that this feature solves?**
This updated homepage video more concisely conveys our value proposition.

**Describe the solution you'd like**
Please replace the homepage video https://acceleratenetworks.com/videos/acceleratenetworks2023.mp4 with AccelerateNetworks2024.mp4

**Comment by uncheckederror** [comment]
@danry25 @dunkeltron Okay, the new home page video is live. 🚀
