### ISSUE TITLE
[FEATURE] Validate email addresses

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#463]
**What is the problem that this feature solves?**
Sometimes clients submit orders with invalid email addresses like name@domain without a TLD.

**Describe the solution you'd like**
Validate that there is some text before and after the @ and the domain used resolves to a valid MX record.

**How will this improve revenue or reduce our costs?**
This will filter out the obviously invalid email addresses, making it more likely that we have a valid contact email address on file.

**Comment by uncheckederror** [comment]
@danry25 give it a shot with a domain that you know has no MX record and then a valid email address to verify that this works now.
