### ISSUE TITLE
[FEATURE] Improve Order Form Validation

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#468]
**What is the problem that this feature solves?**
This will help us collect more accurate data, ensuring it is easier to contact new customers.

It appears we were fuzzed by #Acunetix or a similar software given the content of the form that was submitted through our ordering system ([based on this article](https://eedle.com/2014/01/17/hackers-with-a-sense-of-humour-or-at-least-a-love-of-chinese-food/)).

**Describe the solution you'd like**

- [x] Validate the phone number entered in the Direct Phone Number field is portable
- [x] Unit Type should be required to have a value if the Unit field or Address 2 is filled out
- [x] First Name, Last Name and Business Name should not all have the exact same values

**Comment by uncheckederror** [comment]
- [ ] The install date needs to be at least 1 day in the future.
- [ ] When a validation error occurs we need to preserver the state of the checkout form, rather than just bumping them back to their cart.

**Comment by uncheckederror** [comment]
@danry25 okay, these changes are live. Try them out an tell me what you think.
