### ISSUE TITLE
[FEATURE] Update Carousel Images

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#469]
**What is the problem that this feature solves?**
The homepage images show older models of phones in the carousel.

**Describe the solution you'd like**
Show the GRP2670, DP716, T57W, T54W instead and remove the word Desk from Desk phones.

**How will this improve revenue or reduce our costs?**
This will nudge our customers towards buying more expensive phones.

**Comment by uncheckederror** [comment]
@danry25 I can't find the DP716 on the Grandstream website.

**Comment by danry25** [comment]
Crumb, I meant WP816 @uncheckederror

**Comment by uncheckederror** [comment]
@danry25 this is live, check it out!
