### ISSUE TITLE
Leading 1 is stripped from numbers below 11 digits in length

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#47]
[If I search for 11234](https://acceleratenetworks.com/Search?Query=11234), it seems this is interpreted as 1234. Ideally we would only strip the leading 1 digit when given a number over 10 digits in length.

**Comment by uncheckederror** [comment]
Ah, yes, this is a high quality bug.

**Comment by uncheckederror** [comment]
I have resolved this bug.
