### ISSUE TITLE
[BUG] CSV Export on Lookup page not working, Search page not processing bulk lookup

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#470]
**What is broken?**
On https://acceleratenetworks.com/Search under "Keep your Numbers" when you give it a list of numbers, you are redirected to https://acceleratenetworks.com/Lookup/BulkPort (your browser does a POST which returns a 400 Bad Request).

Separately, the https://acceleratenetworks.com/Lookup page has an Export to CSV button that shows up after you Search a number, but this redirects to https://acceleratenetworks.com/Lookup/BulkPort which does not work (your browser does a POST which returns a 400 Bad Request).

**Expected behavior**
Results should be returned from this endpoint

**Comment by uncheckederror** [comment]
@danry25 I have disabled caching for now which should resolve this issue.
