### ISSUE TITLE
[BUG] Ops - Address Field states "Please match requested format"

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#471]
**What is broken?**
On a port request, when you  press the update button, the prepopulated address field complains that the prepopulated address is not properly formatted.

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/PortRequests/a64edd50-5c69-4477-b2b3-28913f3260a2/9168001993
2. Click on Update
3. See error which prevents form submission

**Expected behavior**
The prepopulated address should be properly formatted for the form to accept

**Screenshots**
![Screenshot from 2024-07-28 11-57-47](https://github.com/user-attachments/assets/bae201b3-8aa0-46f5-ac0d-e5d76144f120)

**Comment by danry25** [comment]
Yes, exactly, the extra click followed by address selection seems a bit cumbersome.

**Comment by uncheckederror** [comment]
@danry25 this change is live. For existing port requests you'll have to select the correct address and update it one more time, then it won't ask for an update going forward. For new port requests, it should work as expected from the start.
