### ISSUE TITLE
[BUG]  Ops - Submitting a port request always submits with WA state

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#472]
**What is broken?**
The state submitted when pressing "Submit to BulkVS" is always WA, rather than the two letter state code shown in the state field:
/home/dan/Pictures/Screenshots/Screenshot from 2024-07-28 12-09-38.png

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/PortRequests/a64edd50-5c69-4477-b2b3-28913f3260a2/9168001993
2. Click on "Submit to BulkVS" 
3. Go to email sent to us by BulkVS confirming port request, or to their portal and lookup the port request
4. See WA listed in error

**Expected behavior**
The state code should be pulled from the state field

**Comment by uncheckederror** [comment]
@danry25 a new build is live that should pass through the State field from the Port Request form, rather than overwriting it with WA.
