### ISSUE TITLE
[BUG] Porting Information Form can be submitted with no address

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#473]
**What is broken?**
A porting information form was submitted with an address that shows in the client view, but not in the Ops view of the order.

**Expected behavior**
The address should be rendered in the Ops view of the order form.

**Comment by uncheckederror** [comment]
@danry25 I think this was a bug with how updating port requests on the port request edit page in Ops worked. The address would get wiped out by accident, please try it out now by updating some port requests.

**Comment by danry25** [comment]
Hmm, just as I closed this, the issue re-occured...

**Comment by uncheckederror** [comment]
Think I got it.

**Comment by danry25** [comment]
Yes, you did! It works, woo!

![image](https://github.com/user-attachments/assets/9d22482b-7d55-446b-840b-9d3ec1b3bd25)
