### ISSUE TITLE
[BUG] DataTables Breakage on Purchased Numbers

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#476]
**What is broken?**
Clicking on a purchased number gives you a DataTables error

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/NumberOrders/4255475225
2.  See error

**Expected behavior**
Where we bought the number and when should be shown

**Screenshots**
![image](https://github.com/user-attachments/assets/0c6116b3-8eb9-45ad-9369-a6131eb4750d)

**Comment by uncheckederror** [comment]
@danry25 this is fixed now.
