### ISSUE TITLE
[BUG] Completed port requests never show a green check mark

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#477]
**What is broken?**
In Ops under Orders completed port requests never show a green checkmark, and rather show a red ? even after the port request has completed.

**Comment by uncheckederror** [comment]
Looks like BulkVS updated the way they return TNs related to a specific port request. 

Now it looks like this:
```
    "TN List": [
        {
            "TN": "12063299442",
            "LNP Status": "COMPLETE",
            "RDD": "2021-08-27 20:00:00"
        },
]
```
They also used to include an OrderId field that we used to make sure a specific TN was related to the same port request OrderId we were interested in. That is no longer included, so I am going to quit using it which should fix this process.

@danry25 next time you submit a bug like this I need you to provide a specific, concrete example of the problem. It took me multiple hours to find an order where I could reproduce this issue.
