### ISSUE TITLE
[FEATURE] Update logging to reduce memory consumption

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#479]
**What is the problem that this feature solves?**
We're not taking advantage of format strings and parameters which is creating many unnecessary string allocations to support logging.

**Describe the solution you'd like**
Update all the calls to log strings to use format strings and parameters.

**How will this improve revenue or reduce our costs?**
This will reduce memory usage and may improve the performance across all of the apps in the Number Search project that log.

**Comment by uncheckederror** [comment]
I believe this work is complete. I will hold on to this issue for a few days to hunt for regressions related to this change.

**Comment by danry25** [comment]
Daily logs seem to be running about 105MB, is that what you were expecting?

**Comment by uncheckederror** [comment]
Everything seems to be working correctly.
