### ISSUE TITLE
[BUG] Re-register for E911 button not shown after successful registration

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#481]
**What is broken?**
When you register a number for E911 service using a URL ending in RegisterE911?serviceNumber= the button next to a phone number does not turn red and show the Re-registration option until you exit the order and look it back up.

**Screenshots**
![image](https://github.com/user-attachments/assets/3e30ab54-6807-4b9d-8753-c7d8af91bf94)

**Comment by uncheckederror** [comment]
@danry25 this is fixed. I tested it by registering the number for e7dae119-ff0b-460e-bc42-ed1b25c29132. You should double check it to make sure it's correct.

**Comment by danry25** [comment]
This works, thanks @uncheckederror
