### ISSUE TITLE
 Label numbers when ordering through Teli

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#49]
For Teli can we set the note to be the customer's business name followed by the person who placed the order's name, eg: Accelerate Networks - Dan Ryan - Ordered via API

[This is the API to set notes](https://apidocs.teleapi.net/api/my-phone-numbers/change-note-on-did) on Teli, sadly BulkVS and Endstream do not support labeling DIDs, hence issue #40 to allow manual reconciliation of owned DIDs on each vendor.

**Comment by uncheckederror** [comment]
This bug is resolved in b2f7b55. I have verified with @danry25 that notes for Tele numbers are now being set correctly in their system.
