### ISSUE TITLE
Send out invoice and porting information immediately

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#54]
This is business logic that I would like to automate. Rather than sending the current welcome email, if we could send the email outlined below if the order is from someone who is not a current client (eg: If their email domain matches an existing client and is not a free or multi-tenant domain like gmail, yahoo, cruiseshipcenters.com, etc) and generate an invoice, that would be ideal.

Here is the API for InvoiceNinja: https://app.invoiceninja.com/api-docs#/

```
Title: Order for <Phone Number> is complete!
Hello <First Name>,

The order for <Phone Number> is ready, let us know if you would like this number to forward to another phone number immediately.

To port this number to another provider, please pay this invoice <insert link to billing systemm> and submit a port out request with your new provider using the following information:

Account number: <Phone number, no dashes or spaces>
Business Name: <Business name, if set, otherwise skip this whole line>
Authorized Contact: <First Name and Last Name>
Address: <Full address, eg: 2318 E Cherry St, Seattle, WA, 98122>
PIN: <Get from BulkVS, if on a different carrier skip this line>

Original order: <Order URL>

If you need anything please let us know!

Sincerely,
Accelerate Networks
206-858-8757 (call/text)
```

**Comment by uncheckederror** [comment]
There are 3 fundamental things we need to do:

- [ ] Verify that we own the number after buying it
- [ ] Provide the port out information to the buyer or offer to host service for the number
- [ ] Maintain the broadest selection of numbers reasonably possible

**Comment by danry25** [comment]
Here is an [InvoiceNinja C# API client](https://github.com/TheUltimateC0der/API.InvoiceNinja). Looks like its autogenerated from the swagger docs.

**Comment by uncheckederror** [comment]
As of now when an order is submitted we use the Invoice Ninja API to find existing clients by email and create a new invoice for them based on the order. Then we ask Invoice Ninja to send out the invoice on our behalf. If the client doesn't exist in then we create a new client using the Invoice Ninja API.

**Comment by uncheckederror** [comment]
Not sure what to do about getting the porting information for a number that we now own on the customer's behalf.

**Comment by danry25** [comment]
Its mostly templating an email for each vendor, I will craft those up and attach them to this issue. Only BulkVS has port out PINs, which will need to be incorporated into the outbound email template.

For some reason, a bill and an email were not generated for the number order completed on 9/9/2020 11:54:52 AM, not sure if its due to the email format or what, just surprised the client doesn't even exist in the billing system...

**Comment by uncheckederror** [comment]
Just to clarify this is a special scenario where the buyer has only purchased a phone number. In this case we need to buy it from the vender, verify that we own it, and then pass the port out information from our vendor to the customer in an email.

**Comment by uncheckederror** [comment]
Per @danry25:
We need to send out different porting information for each underlying carrier that we purchased the numbers from.

For Teli and Endstream we need to send the customer this info:
- The First and Last Name attached to the order
- Business Name (if this field is filled in)
- Address
- List of phone numbers purchased
All of this information is captured in the order when a customer submits it.

For BulkVS, we need to set the "PortoutPin" value to be the same across all phone numbers attached to said order and include the same information that we send for phone numbers from Teli and Endstream.
