### ISSUE TITLE
Refactor Number Ingest as a systemd service

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#57]
Per our discussion, rather than having a cronjob invoke the number ingest hourly, it would likely make more sense to have Number Ingest running at all times, waiting for the next ingest cycle.

**Comment by uncheckederror** [comment]
@danry25 I have triggered a deployment of the new Ingest application to production. You will now need to do the following:

- [ ] Delete the existing cron job
- [ ] Create a systemd file to start NumberSearch.Ingest up.
- [ ] Respond to this so I can update the deployment pipeline to restart the app when a new release is completed.

**Comment by uncheckederror** [comment]
Add code to enable this feature in 5cc6561

**Comment by danry25** [comment]
I have added a systemd unit file and installed this on the server. Please let me know if there is anything else I can do!

**Comment by uncheckederror** [comment]
I have updated the release pipeline and verified that these changes are working as intended.
