### ISSUE TITLE
High Priority Ingests

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#58]
Could we ingest certain area codes multiple times a day from each vendor? Particularly 206, 360, 425, 503, 509, 541 and 564 are our important area codes to have accurate data for.

**Comment by uncheckederror** [comment]
@danry25 How often do you want these priority ingests to run?

**Comment by uncheckederror** [comment]
Based on my conversation with @danry25 high priority ingest should be run every hour.

**Comment by uncheckederror** [comment]
This feature is now deployed to production.
