### ISSUE TITLE
Rate limit ingests from select vendors

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#59]
Certain vendors like Peerless Networks have a hard cap of 100,000 numbers looked up per hour via API. If we could ingest numbers from them at a slower rate (eg: smear our API lookups across 3 hours) we would be well below their API limits.

Additionally, outside of high priority area codes (issue #58), we really only need 1 complete ingest per day per vendor.

This ticket relates to #43 and #58

**Comment by uncheckederror** [comment]
I am putting this on pause until we get implement the ability to purchase phone numbers through the peerless API.

**Comment by danry25** [comment]
Sounds good!

**Comment by uncheckederror** [comment]
Need to implement the ability to purchase numbers through the Peerless API. We will only enable number ingestion for the priority area codes from this vendor.

**Comment by uncheckederror** [comment]
@danry25 Should the "customer_name" field be "Accelerate Networks"?
