### ISSUE TITLE
Resell unassigned phone numbers that we own

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#60]
We have a fair number of phone numbers we own but have not assigned to clients (eg: We bought them for use as temporary forwarding numbers, but the port request has completed and the client does not need the numbers anymore).

It would be nice if NumberSearch could offer these numbers to our clients for purchase.

**Comment by uncheckederror** [comment]
So we'd need a page in the Ops app where you could manually enter a phone number to get it listed in the Number Search page in the Mvc app.

**Comment by danry25** [comment]
Exactly, a page should exist in the Ops app with a list of owned phone numbers imported from the vendors we integrate with currently, each with a field to mark it as unassigned or to tie it to a client.

**Comment by uncheckederror** [comment]
How would we query each of the vendors for the phone numbers we own?

**Comment by uncheckederror** [comment]
It looks like this feature is dependent on completing #61 first.

**Comment by danry25** [comment]
If a phone number has a note of Unassigned, we should offer it for sale @uncheckederror. Looks like #61 is now complete, which was the blocker on this issue.

**Comment by uncheckederror** [comment]
Okay, I will have to add this as a step to the ingest process.

**Comment by uncheckederror** [comment]
Okay, @danry25 please try buying a number we already own from the website.

**Comment by danry25** [comment]
@uncheckederror This works! Woohoo!

The only confusing part is the Billing Client ID is not set and the note saying the number is Unassigned is also not changed, so the number is still available for puurchase.

**Comment by uncheckederror** [comment]
Okay I've addressed this feedback in the new build. Please try it out.

**Comment by danry25** [comment]
Neat, that seems to work well! Is there any way we can parse old orders and apply the client ID and purchased on info to said numbers?

**Comment by uncheckederror** [comment]
Yes, that's issue #147.
