### ISSUE TITLE
Manage numbers assigned to clients

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#61]
Ingest our numbers from each vendor and track what client owns which phone number along with a text field for notes about each number.

Additional scope creep items that should be in separate issues after MVP of this feature:
- Pull client list from [InvoiceNinja API](https://docs.invoiceninja.com/api.html)
- Enable CNAM (caller name lookup) on all numbers ([Teli API](https://apidocs.teleapi.net/api/my-phone-numbers/enable-cnam-on))
- Allow Ops to set LIDB value so CNAM is correct for numbers ([Teli](https://apidocs.teleapi.net/api/my-phone-numbers/lidb-set-callerid-on), Bulk Solutions has an API for this too)
- Regularly validate that underlying number has not been ported away (use Local Routing Number API (aka LRN) to see  underlying carrier and track if this changes, trigger alert if so)
- Manage E911 Registrations
  - Integrate with Teli E911 API (show E911 registration attached to a number)

[CANCELLED PER DANIUM]
  - Integrate with FusionPBX (pending APIs being written in our [FusionPBX REST API](https://git.callpipe.com/fusionpbx/REST-API))
     - List all configured emergency caller ID numbers, flag numbers that are configured but not registered
     - Prompt users to reconfirm their E911 address when their IP address changes (use email address on file for voicemail or user account in the relevant domain)

**Comment by uncheckederror** [comment]
So we want Inventory the phone numbers that we own through each vendor that we integrate with and then store meta data about each phone number.

Could you send me an example query for each of these API integrations?

**Comment by danry25** [comment]
For FirstPoint/Endstream use DIDSearchInAccount (pass the auth.username, auth.password, ReturnAmount of 999999, then go area code by area code using DIDSearch.NPA). Harel has a better endpoint he will email you tomorrow FYI.

Teli has an endpoint to [list all numbers](https://apidocs.teleapi.net/api/my-phone-numbers/list-all) owned by the account. The [notes API](https://apidocs.teleapi.net/api/my-phone-numbers/change-note-on-did) and [LIDB API](https://apidocs.teleapi.net/api/my-phone-numbers/lidb-display-current-callerid-set) also provide the notes and the CNAM value set for each number.

BulkVS I will need to research further.

**Comment by uncheckederror** [comment]
I have to model and process for retrieving numbers that we own from endstream working.

**Comment by uncheckederror** [comment]
I have split off listing all the numbers we own in the Ops app into #75.

**Comment by uncheckederror** [comment]
Run the enable CNAM lookups only for numbers ingested through Teli and only on the first time that they are ingested.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/95821551-fbb2bc80-0cde-11eb-9276-0ede86888dc5.png)
![image](https://user-images.githubusercontent.com/11726956/95821585-0a00d880-0cdf-11eb-80bb-08851fab3d28.png)
