### ISSUE TITLE
Expose bulk LRN Lookup in MVC app

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#62]
If we could allow unauthenticated users to do bulk LRN lookups through a pretty looking webpage it could be quite helpful for our partners.

Format they would like to submit a list of numbers in:
```
+1 206-858-9310
2024561414
(206)858-8757 Random Jibberish that should be stripped
```
All non-numerical characters should be stripped, expect 1 phone number per line.

We already do singleton queries to [this API here](https://github.com/AccelerateNetworks/NumberSearch/blob/a21693c8d6ee26d85011828709f8bc40e6af121d/NumberSearch.Ops/Controllers/HomeController.cs#L144-L152).

PS: please update [all placeholder numbers](https://github.com/AccelerateNetworks/NumberSearch/blob/c06df54e3f533f61a48a73f687316c3c28bc14f8/NumberSearch.Ops/Views/Home/Tests.cshtml#L81) to 2068588757.

**Comment by uncheckederror** [comment]
I have updated all of the place holders on the Tests page in the Ops app to use the phone number you provided.

**Comment by uncheckederror** [comment]
@danry25 Of the field listed in the response on this page, which ones do you actually want to see?

![image](https://user-images.githubusercontent.com/11726956/91508961-ca487380-e88d-11ea-9d22-6e49f8569705.png)

**Comment by uncheckederror** [comment]
@danry25 Here's what the page looks like with the sample number list you provided:

![image](https://user-images.githubusercontent.com/11726956/91510078-e26dc200-e890-11ea-9f41-1a6f9d4828db.png)

**Comment by danry25** [comment]
Can we hide Code,  and both Status fields, then put the results in a columned table?

**Comment by uncheckederror** [comment]
@danry25 how's this?

![image](https://user-images.githubusercontent.com/11726956/91510957-67f27180-e893-11ea-90f0-435da8330c90.png)

**Comment by uncheckederror** [comment]
@danry25 Added the number that was queried for, to each row of results, to improve clarity. Are there any columns we can remove or combine here?

![image](https://user-images.githubusercontent.com/11726956/91511881-94a78880-e895-11ea-952f-a8952b11172d.png)

**Comment by danry25** [comment]
Can we drop CLLI, Fraud Risk, LATA, OCN Name Type, Ratecenter and State? Also, can we add a column containing the phone number submitted?

**Comment by uncheckederror** [comment]
@danry25 okay, check it out:

![image](https://user-images.githubusercontent.com/11726956/91513069-4942a980-e898-11ea-8f57-43ff3ac6a991.png)

**Comment by danry25** [comment]
Looks awesome Tom!

**Comment by uncheckederror** [comment]
I have updated the lookup page to have a larger text input area in bcf6b4e

**Comment by uncheckederror** [comment]
This feature has shipped to production and you can try it out here: 

https://acceleratenetworks.com/Lookup
