### ISSUE TITLE
No way to access bill uploaded with the submission of a port request

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#64]
How can we access the file uploaded by a customer that submitted a port in request in the Ops application? It appears the file is not exposed to the ops application.

**Comment by uncheckederror** [comment]
Right now the file uploads are just ignored. Could never get it to work quite right.

**Comment by danry25** [comment]
Interesting, could we hide the file upload button then?

**Comment by uncheckederror** [comment]
I am going to add instructions to ask them to respond to the port request confirmation email with a copy of their bill.

**Comment by uncheckederror** [comment]
I have managed to fix the file upload button on the Porting Information page. Now when a bill image is submitted through the form its sent out as an email attachment to the orders email address and the client.

**Comment by danry25** [comment]
Awesome, time to commit and close this issue then?

**Comment by uncheckederror** [comment]
@danry25 These changes are now live. Please try it out and provide feedback.
