### ISSUE TITLE
Do not show success prior to collecting porting info

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#65]
Customers should not see Success as the front page status or a green modal until after they have provided porting info.

Perhaps say there is just a little more to do to complete the order (and include a link in the initial order email to where they can submit porting information).

![image011](https://user-images.githubusercontent.com/1683673/91926517-470f8f00-ec8c-11ea-932b-96fb61139968.jpg)

**Comment by uncheckederror** [comment]
I have removed the success notification from this page.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/92036979-eb91df80-ed25-11ea-83ae-e6bc01c86167.png)

After the order is submitted they are just presented with the porting information form.
