### ISSUE TITLE
Add Sales Tax

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#66]
When an address is inside Washington State, please add Sales Tax using the [Washington State API for Sale Tax information](https://dor.wa.gov/taxes-rates/retail-sales-tax/destination-based-sales-tax-and-streamlined-sales-tax/wa-sales-tax-rate-lookup-url-interface).

When adding a non-existent tax rate to InvoiceNinja, please set the name of the rate to be the same as the percentage of the tax rate. (eg: 10.1% tax is named 10.1%)

**Comment by uncheckederror** [comment]
- [ ] Model the WA Sale Tax API.
- [ ] Calculate the sale tax to collect on the Order form.
- [ ] Add a column to the Orders table in the database to store the tax rate information.
- [ ] Add the tax amount as an item on the Invoice Ninja invoice generated by the Order form.
