### ISSUE TITLE
Discount number purchase fee

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#67]
If a Fax Server, Standard Line Toll Free Number or Concurrent Seat is added to cart, discount all numbers ported in or purchased to $0.

Additionally, could we add a notes field to orders and if this is filled in, not generate the bill for a customer automatically?

**Comment by uncheckederror** [comment]
I have split this into two issues. In this issue we will only handle discounting porting fees when "Services" are purchased.

**Comment by uncheckederror** [comment]
@danry25 Can you give me some example shopping cart scenarios and how you would expect this to work?

**Comment by danry25** [comment]
To clarify, mark one phone number per service from the service page as $0, then $2 a month per phone number for any additional numbers.
