### ISSUE TITLE
InvoiceNinja Integration - Duplicate Client Created

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#68]
Relates to issue #54, it seems our billing system now has two clients with the same name and email address when NumberSearch should have looked up the existing client by email address and billed the order using that existing customer profile.

**Comment by uncheckederror** [comment]
Can you provide an example?

**Comment by danry25** [comment]
Yes, look at [this customer profile](https://billing.acceleratenetworks.com/clients/145) and [the pre-existing one](https://billing.acceleratenetworks.com/clients/15).

**Comment by uncheckederror** [comment]
I am not sure how to handle this issue. We attempt to look up the user by getting a list of invoice ninja clients via their API and then we grab the first client from the list of clients that is returned and add the new invoice to that client.

I create a few new clients with that email address as part of the process where I developed the invoice ninja API integrations. So this might be an artifact left over from that development process.

**Comment by danry25** [comment]
Ah, ok. We should delete those clients and test this out!

**Comment by uncheckederror** [comment]
@danry25 Please do.

**Comment by uncheckederror** [comment]
@danry25 are we good on this?

**Comment by danry25** [comment]
I think so!
