### ISSUE TITLE
Number Portability Broken?

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#69]
I tried entering 2068589310 to try and port it a few minutes ago using the form, but it times out after a minute and gives the error below.

The LNP portability API is up and responds within 600ms, so it is not an upstream issue.
![Screenshot from 2020-09-02 12-33-00](https://user-images.githubusercontent.com/1683673/92028320-b29f3e00-ed18-11ea-9329-327c20a1c53d.png)

**Comment by danry25** [comment]
@uncheckederror Per our conversation the vendor's API was unresponsive and is returning inconsistent portability results. 

Seeing as we have had zero issues with portability over the past half decade and can port numbers in every major ratecenter in the US, lets disable this check moving forward and [edit the alert text](https://github.com/AccelerateNetworks/NumberSearch/blob/137ff4da1221b922c60b85960c00aa0435d9385a/NumberSearch.Mvc/Views/Porting/Index.cshtml#L38) to say "This phone number can likely be ported to our network!".

**Comment by uncheckederror** [comment]
If the phone number supplied by the user is 10 chars long and can be broken down into an npa, nxx, and xxxx and each portion can be parsed as an integer then it will continue on in the process even if the portability check fails or returns an error.
