### ISSUE TITLE
Verify that we own a number after buying it

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#71]
There are 3 fundamental things we need to do:

- [ ] Verify that we own the number after buying it
- [x] Provide the port out information to the buyer or offer to host service for the number
- [x] Maintain the broadest selection of numbers reasonably possible

_Originally posted by @uncheckederror in https://github.com/AccelerateNetworks/NumberSearch/issues/54#issuecomment-674447140_

**Comment by uncheckederror** [comment]
@danry25 I am breaking this out into a separate issue so that we can track the development of the API endpoints required enable the MVC app to verify that we own specific numbers and that they are routed correctly by placing calls to them.

**Comment by danry25** [comment]
I need to write/document APIs for the following things:
- [ ] Adding a phone number to FusionPBX (Dialplan => Destinations)
- [ ] Making a call to a phone number
- [ ] Pulling the call logs
- [ ] Deleting a phone number from FusionPBX (Dialplan => Destinations)

**Comment by uncheckederror** [comment]
@danry25 Given that we've opted out of creating FusionPBX integrations how can we verify that we own a number?

**Comment by danry25** [comment]
@uncheckederror If we buy a number from anyone besides FirstPoint/Endstream, it is safe to assume we own it. Otherwise it needs manual verification.
