### ISSUE TITLE
Create link in Ops app to link to invoice related to order

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#72]
When a bill is generated, link to it in the Ops application. Allow this field to be manually edited by the Ops app user.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/92178633-cec5dc80-edf7-11ea-9031-1cf530692790.png)

**Comment by uncheckederror** [comment]
@danry25 What do you mean that you want this field to be manually editable by an Ops application user?

**Comment by danry25** [comment]
Scratch that, this is fine. Feel free to close the issue!
