### ISSUE TITLE
Link to and submit port requests from Ops app

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#73]
We currently pull in port requests from our customers through the Ops app, it would be nice if we could
- [x]  Edit the port request information

- [x] Press a button to submit this information to our vendor

- [x] Provide a permanent link to the vendor's port request # on both the order and in the Owned Numbers section

Ingest LNP requests by getting a list of request IDs using the [LNP portability List](https://apidocs.teleapi.net/api/lnp-portability/list-orders) API, then use the [LNP portability CSV API](https://apidocs.teleapi.net/api/lnp-portability/request-csv-list) to get the phone numbers associated with each LNP request and the status of the port request for each phone number.

**Comment by uncheckederror** [comment]
Which vendor would we submit this port request information to ?

What endpoint would we submit this data to?

Can you give me an example URL of a port request in the vendor's system?

**Comment by danry25** [comment]
Take a look at the [Create Order](https://apidocs.teleapi.net/api/lnp-portability/create-order) endpoint to submit a port request, [List Orders](https://apidocs.teleapi.net/api/lnp-portability/list-orders) to get all port requests, and [Get Specific Information](https://apidocs.teleapi.net/api/lnp-portability/get-specific-information) to get the port request status, whether that be pending, has a firm date for the phone numbers to port, or has completed porting.

We will also need to gather signatures with a size of 200px height and 400px width and submit those. The upstream vendor uses [Signature Pad v1.5.3](https://github.com/szimek/signature_pad) to do this, or we could generate this automatically using the information and consent provided by the submitter.

**Comment by uncheckederror** [comment]
In f0841be I added the ability to update information in a Port Request in the Ops app. I also verified that there will always be a 1:1 relationship between an Order and a Port Request. We will not support the association of multiple port requests with a single order.

**Comment by uncheckederror** [comment]
In #89 we finished tuning up the port submission page in the Mvc app. The goal now is to integrate with the Teli port request submission API in the Ops app to enable the submission of porting information after it's been reviewed.

**Comment by uncheckederror** [comment]
Teli doesn't have a direct way to link to a single Port Request in their system. So instead if there's a Teli Id for the Port Request set in our system we'll give you a button that links to their general Port Requests page and then show you the Id of the request.
