### ISSUE TITLE
Add tax to the appropriate category in InvoiceNinja

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#76]
**Describe the bug**
Tax rates not applied in the correct category

**To Reproduce**
1. Go to AccelerateNetworks.com
2. Buy anything and enter an address in Washington State
3. Check out
4. See sales tax applied as a line item rather than a tax rate

**Expected behavior**
Apply tax rates by looking up the tax rate from Washington State, then matching the relevant % rate with the matching city/town name by using the [list of tax rates](https://app.invoiceninja.com/api-docs#!/tax_rate/get_tax_rates) endpoint. If tax rate with matching % and city/town name does not exist, create one using the [create tax rate](https://app.invoiceninja.com/api-docs#!/tax_rate/post_tax_rates) endpoint.

**Additional context**
Applying tax this way is a great way to make paying our sales tax to Washington State hard, as it prevents the automated sales tax report from working properly in InvoiceNinja.

**Comment by uncheckederror** [comment]
@danry25 How do you associate a tax rate with an invoice?

**Comment by danry25** [comment]
It appears you will need to set "tax_name1": "10.1%", "tax_rate1": 10.1, when creating the invoice. I have sent you an example query to show this out of band.

**Comment by uncheckederror** [comment]
Okay so before I assign the tax rate to the invoice I have to get a list of all the available tax rates in the system. Then I can see if the rate already exists and use it if it does. If it does not then I'll have to create a new tax rate entry and use that.

**Comment by danry25** [comment]
Exactly. Please label the tax rate with the appropriate locality as its name too!

**Comment by uncheckederror** [comment]
@danry25 Just to confirm, you want the "Name" field to be the billing City and the "Rate" field to be the decimal tax rate provided by the state Sales Tax API.

**Comment by danry25** [comment]
Name should be the rate name (returned by the WA Sales Tax Rate Lookup URL Interface), state and loccode/code with the first letter of each word for the rate name being capitalized, state set to WA and a dash thereafter before the loccode/code.

Examples:
```
Seattle, WA - 1726
Benton County, WA - 0300
Kittitas County - Mvet, WA - 1950
```

**Comment by uncheckederror** [comment]
These changes have been deployed to production. Please test them out and close this issue if you're satisfied @danry25.

**Comment by danry25** [comment]
This is implemented correctly and seems to work well, thanks @uncheckederror !
