### ISSUE TITLE
Show Service Provider Name in addition to the OCN

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#78]
**Is your feature request related to a problem? Please describe.**
Relates to issue #75, show Service Provider Name in addition to Operating Carrier Number (the 4 digit code shown under the Service Provider column in the Ops app), both should be moved to show up under either the Edit button of a number, or under a new info button?

**Describe the solution you'd like**
Move these two pieces of data to show up on a separate menu, as in most cases it is not useful information.

**Comment by uncheckederror** [comment]
This is resolved in 0ce5cba.
