### ISSUE TITLE
Additional LRN Lookup API

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#80]
**Describe the bug**
Occasionally the current LRN Lookup API fails to return a result.

**To Reproduce**
Query the LRN Lookup API day in and day out, watch for the occasional timeout or failure.

**Additional context**
When failures occur, we can fallback to querying FirstPoint (aka Endstream) at [this API endpoint](http://www.endstream.com/endstreamws/OCNLATAdip.asmx?op=RequestOCNLATA) and get the same full set of results.

**Comment by uncheckederror** [comment]
This changes the Owned Phone number lookup process in the ingest application and also Lookups page in the Mvc web app.

**Comment by uncheckederror** [comment]
So this API is a completely different SOAP service from the one we currently use to interact with Endstream.

http://www.endstream.com/endstreamws/OCNLATAdip.asmx?WSDL

**Comment by danry25** [comment]
I do not appear to have working credentials for this API, I will reach out to FirstPoint/Endstream and request these!

**Comment by danry25** [comment]
We can also use the BulkVS LRN API, apparently it assumes we want a simple query without OCN, port date and LATA, but if we use any of the methods below besides option 1 we can get the full dataset:
```
Option 1: "simple" or leave the format option blank. This output will provide the LRN
Example 1: http://lrn.bulkCNAM.com/?id=(YOUR ID)&did=(TELEPHONE NUMBER)&ani=(TELEPHONE NUMBER)&format=simple
Example 2: http://lrn.bulkCNAM.com/?id=(YOUR ID)&did=(TELEPHONE NUMBER)&ani=(TELEPHONE NUMBER)

Option 2: "xml" This output will provide an XML wih OCN, LATA, and LEC as XML
Example: http://lrn.bulkCNAM.com/?id=(YOUR ID)&did=(TELEPHONE NUMBER)&ani=(TELEPHONE NUMBER)&format=XML

Option 3: "text" This output will provide an XML wih OCN, LATA, and LEC as text
Example: http://lrn.bulkCNAM.com/?id=(YOUR ID)&did=(TELEPHONE NUMBER)&ani=(TELEPHONE NUMBER)&format=text

Option 4: "text" This output will provide an XML wih OCN, LATA, and LEC etc... as json
Example: http://lrn.bulkCNAM.com/?id=(YOUR ID)&did=(TELEPHONE NUMBER)&ani=(TELEPHONE NUMBER)&format=json 
```

**Comment by uncheckederror** [comment]
Worth noting that we're not getting a last ported date back from this BulkVS api.

**Comment by uncheckederror** [comment]
Based on the last Owned Numbers ingest run BulkVS seems to have the LRN lookup range as Teli. There is no scenario for the numbers we own where BulkVS is able to capture LRN information that Teli is not. Neither are able to return information on number with an 800 NPA.

**Comment by uncheckederror** [comment]
800, 833, 844, 855, 866, 877, 888 NPA should be ignored because they are toll free numbers than cannot be looked up via LRNs.
