### ISSUE TITLE
Show counter on Caller ID field of Port Request Form counting up to 15 characters

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#82]
**Is your feature request related to a problem? Please describe.**
This is a feature request. Currently we state the 15 character limit, but there is no indication how close to the limit a user is when entering a Caller ID

**Describe the solution you'd like**
Ideally, there would be a character counter, and we should also validate that only alphanumeric characters and spaces are included in this string. Other punctuation, emojis, etc are not permitted for caller ID values. When entered into the form, a warning should appear.

**Comment by uncheckederror** [comment]
A-z 0-9 and spaces are the only allowed characters.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/93163455-0839fa00-f6cc-11ea-94ea-16ab4c918af5.png)
