### ISSUE TITLE
Quantity of items and per item price not shown on /Cart/Checkout

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#85]
**Describe the bug**
After pressing Review Your Order from the cart and getting redirected to https://acceleratenetworks.com/Cart/Checkout the customer is only shown the total price for each line item (eg: GRP2613 $130) rather than the quantity, unit price and line item total for each item.

**Expected behavior**
Show the line item quantity and unit price in addition to the line item total.

**Screenshots**
![Screenshot from 2020-09-13 15-29-48](https://user-images.githubusercontent.com/1683673/93030268-916f0500-f5d6-11ea-94d3-5e8b8aca3b09.png)
Form that needs help:
![Screenshot from 2020-09-13 15-28-38](https://user-images.githubusercontent.com/1683673/93030270-9469f580-f5d6-11ea-85fe-61637e9407e0.png)

**Comment by uncheckederror** [comment]
@AlexScheller This is nearly identical to #87. Both will require you to make 1 line changes to the "Orders" view used by the Cart controller.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/93651384-25214680-f9c6-11ea-801b-aa52db42b99a.png)
