### ISSUE TITLE
Reduce quantity of duplicate clients

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#86]
**Describe the bug**
When an existing client places an order and uses a different email address than what we have on file, a new client profile is generated.

**Expected behavior**
Ideally we would attach the new bill to the correct client profile in the billing system.

**Additional context**
If we could do soft matching, eg: When an email comes from @clientsdomain.com attach it to their account rather than making a new account.

We will also need a way to blacklist of shared domains like @yahoo.com, @gmail.com, @cruiseshipcenters.com and so forth so that users from those domains have a new client profile created automatically.

**Comment by uncheckederror** [comment]
Closing for now to investigate a manual only process.
