### ISSUE TITLE
Mention taxes in checkout process

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#87]
**Describe the bug**
We do not mention that sales tax will be assessed on sales inside Washington State.

**To Reproduce**
1. Select a number
2. Check out with an address in Washington State
3. Note that the order shows no taxes
4. See the actual invoice from InvoiceNinja with sales tax added on

**Expected behavior**
A clear and concise description should be "Total (USD) - Plus state and local taxes" for the final line item.

**Screenshots**
![Screenshot from 2020-09-13 15-28-38](https://user-images.githubusercontent.com/1683673/93030425-e0696a00-f5d7-11ea-9588-dbe33769f3d1.png)

**Comment by uncheckederror** [comment]
@AlexScheller I found you a bug.

**Comment by uncheckederror** [comment]
Here's the offending line in the view: https://github.com/AccelerateNetworks/NumberSearch/blob/427ef3452f4a1868ed6f7fb3af21b48fa7eba609/NumberSearch.Mvc/Views/Cart/Order.cshtml#L125
