### ISSUE TITLE
Ingest Toll Free Phone Numbers

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#90]
**Is your feature request related to a problem? Please describe.**
We don't offer any Toll Free phone numbers.

**Describe the solution you'd like**
We should ingest Toll Free phone numbers from our providers.

**Describe alternatives you've considered**
Continuing to not have any Toll Free phone numbers available through our website.

**Additional context**
Teli and BulkVS have specific endpoints for querying for Toll Free numbers. Endstream includes them along with their regular numbers. We need to add a column in the database and mark them as Toll Free when they're ingested.

**Comment by danry25** [comment]
API for Teli Tollfree: https://apidocs.teleapi.net/api/order-phone-numbers/list-tollfree-numbers

**Comment by uncheckederror** [comment]
Standard, Premium, Executive, and now Tollfree tags.

**Comment by uncheckederror** [comment]
We are now ingesting Tollfree numbers from both Teli and BulkVS and exposing them through the Numbers page in the Mvc webapp.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/103473095-91dc0900-4d49-11eb-8694-6f335ad2778a.png)
