### ISSUE TITLE
Issue adding Sales Tax Amount on Invoice Ninja

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#92]
Hey Tom,

I can’t add a custom sales tax amount on Invoice Ninja. I need 8.7% percent for a particular business which isn’t a option.

Is there a way for me to customize the sales tax amount?

**Comment by uncheckederror** [comment]
Yeah, Danny mentioned this issue yesterday. I can add a page in the Ops app so you can create custom sale tax amount, although I believe there's also a way to do this from inside of Invoice Ninja.

**Comment by danry25** [comment]
@uncheckederror & @scottstrong206 To recap what we discussed, ideally we would create a tax rate add form in the Ops app that would take an address (or partial address like a zip code), add the appropriate tax rate to InvoiceNinja, then tell the user the name and 4 digit code associated with the tax rate.

There is a way to add tax rates under Settings => Tax Rates in InvoiceNinja, but unlike the automatic tax rate lookup Tom has created for the orders system on acceleratenetworks.com, we usually add tax rates without including the city or tax location #, making it a manual process to classify each invoice to remit sales tax (quite laborious).

If we just have good data from the start, our sales tax reporting will be much easier overall.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/94879386-eb642d00-0414-11eb-80df-ab003e6e7db8.png)

**Comment by uncheckederror** [comment]
@danry25 and @scottstrong206 okay, this feature is now deployed in the Ops app at https://ops.acceleratenetworks.com/Home/TaxRates
