### ISSUE TITLE
Add Phone Number below the Talk to Us button

### ISSUE THREAD

**Issue by scottstrong206** [AccelerateNetworks/NumberSearch#93]
Can we add our phone number (206) 858 8757 underneath the Talk to Us button?

**Comment by danry25** [comment]
@scottstrong206 Would you mind:
- [ ]  Adding the additional details we discussed about this issue

- [ ] Updating this issue to have a descriptive title

- [ ] Using the Issue Template

- [ ]  Including the example screenshot I provided of the change you would like to see

This way Tom can understand and implement the change more effectively.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/94374546-e7a57300-00c1-11eb-8773-6bac26a31fd9.png)

**Comment by uncheckederror** [comment]
@scottstrong206 Please verify that you're good with this fix.

**Comment by scottstrong206** [comment]
Thanks Tom, that looks great!
