### ISSUE TITLE
Short circuit area code searches 

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#94]
**Is your feature request related to a problem? Please describe.**
When you enter an area code in the number search it does not recognize it and just executes a general search for those characters.

**Describe the solution you'd like**
I would like area codes to be automatically recognized and wild card characters to be automatically appended when they enter 3 numbers that match with a known area code.

**Comment by danry25** [comment]
Please advise the user that this is being processed as an area code specific search, eg: using the Boostrap success text modal or similar.

**Comment by uncheckederror** [comment]
@danry25 how about this:
![image](https://user-images.githubusercontent.com/11726956/95029069-5d798380-065a-11eb-8554-5491a5c0cd0f.png)

**Comment by danry25** [comment]
Looks good to me, feel free to implement this!
