### ISSUE TITLE
Pressing Port with a blank field results in an error

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#95]
**Describe the bug**
When someone goes to [this page](https://acceleratenetworks.com/Porting/CheckPortability?Query=), generally by going to [Number Search](https://acceleratenetworks.com/Search) and pressing Port without entering anything they will see an error page

**Expected behavior**
Loop the user back to [Number Search](https://acceleratenetworks.com/Search) and show some text advising them they need to enter a phone number.

**Screenshots**
![image](https://user-images.githubusercontent.com/1683673/95004952-14b4c280-05a7-11eb-8d1e-ce66cef1d1d3.png)

**Comment by uncheckederror** [comment]
This is the page they'll now be redirected to if they click the Port button without entering a number: 
![image](https://user-images.githubusercontent.com/11726956/95030764-b5b68280-0666-11eb-89b9-d61a4b1cc8fc.png)
