### ISSUE TITLE
Bill uploaded with Port Request is not retained, nor is it passed to the vendor

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#96]
**Describe the bug**
A port request is submitted with a pdf of the old provider's bill, but this bill is not accessible through the Ops app, nor is it passed along to the vendor when the port request is submitted.

**Expected behavior**
When a bill is attached to a port request, it should be presented in the Ops app when viewing the port request details and also passed along to the vendor.

**Additional context**
See port request 4991, it is an example of where this issue occurred.

**Comment by uncheckederror** [comment]
@danry25 Please provide durable storage for me to put the files into.

**Comment by uncheckederror** [comment]
Per @kylek206 the bill upload doesn't work and breaks the porting request process at the moment.

**Comment by uncheckederror** [comment]
I have just verified that this bug doesn't occur in the development environment on Windows 10 running locally from Visual Studio. But it does fail on the production Debian 10 machine.

**Comment by uncheckederror** [comment]
2020-11-13 22:44:01.937 -08:00 [ERR] HTTP POST /Porting/AddPortingInformation responded 500 in 26.0661 ms
System.NullReferenceException: Object reference not set to an instance of an object.
   at NumberSearch.Mvc.Controllers.PortingController.AddPortingInformationAsync(PortRequest portRequest) in /home/vsts/work/1/s/NumberSearch.Mvc/Controllers/PortingController.cs:line 381

**Comment by uncheckederror** [comment]
This is the line the Email object is created.

**Comment by uncheckederror** [comment]
@danry25 is this still happening?

To what persistent storage should the bill images be saved?

**Comment by danry25** [comment]
Do we want to just use [Azure Blob Storage](https://azure.microsoft.com/en-us/pricing/details/storage/blobs/) or another S3 compatible API? I doubt we are going to use a full gigabyte of storage anytime soon, and @piajesse has indicated that setting up Minio (a self hosted S3 API) is not a priority currently.

**Comment by piajesse** [comment]
I can spin up minio pretty fast, I just wanted to do some testing on it first. But for now I'd recommend wasabi, as its S3 api and $6/TB/month, unlimited bandwidth

**Comment by uncheckederror** [comment]
Ok this works now. You can submit a bill image as part of the port request form and then retrieve it from the port request page in the Ops app using the "Losing Carrier Bill" button at the top. @scottstrong206 @kylek206 @danry25

As an example check out this port request: https://ops.acceleratenetworks.com/Home/PortRequests/aaf1ea50-7c9e-4732-a4aa-9cceac325b83

![image](https://user-images.githubusercontent.com/11726956/106313046-6f3ff180-621c-11eb-99c0-4f69b3e6e948.png)
