### ISSUE TITLE
Billing Telephone Number as a dropdown listing all numbers on port request

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#97]
**Is your feature request related to a problem? Please describe.**
Users seem to not understand what a billing telephone number is and input bad data in this field.

**Describe the solution you'd like**
Since the BTN has to be on the account, and we are almost always porting all numbers from providers, the BTN should be in the list of numbers that a user has selected to port to us.

A BTN is an active phone number on the account we are porting phone numbers from, and it is the primary phone number on the account often acting as the account number itself, shown in the upper right corner of the bill for Centurylink, Frontier & Ziply Fiber bills.

Perhaps we should show the prior paragraph as informational text too?

**Comment by uncheckederror** [comment]
Yeah, we can do that. We could also make them select the billing phone number a dropdown list of numbers that they are porting in.

**Comment by uncheckederror** [comment]
Help text for Billing Telephone Number:  The primary phone number on the account often acting as the account number, shown in the upper right corner of the Centurylink, Frontier & Ziply Fiber bills.

**Comment by uncheckederror** [comment]
@danry25 how does this look?
![image](https://user-images.githubusercontent.com/11726956/95373463-e3334400-0891-11eb-9703-35b0237e3229.png)
