### ISSUE TITLE
Hard to see which toggle is selected in the Port Request form

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#98]
**Is your feature request related to a problem? Please describe.**
Its hard to know at first glance which side of the Location Type and Partial Port buttons is selected.

**Describe the solution you'd like**
Could we switch to a bootstrap button that only colors the selected side of the toggle, leaving the unselected side of the toggle white with a thin line around the edge to define it as a button?

**Comment by uncheckederror** [comment]
@danry25 how about this?
![image](https://user-images.githubusercontent.com/11726956/95030432-8acb2f00-0664-11eb-907b-9dedb09a9436.png)

**Comment by danry25** [comment]
Looks great, thanks Tom!
