### ISSUE TITLE
Email client when port date is set and when port completes

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#99]
**Is your feature request related to a problem? Please describe.**
Our vendors provide the date on which a phone number will port via API as the foc_date [in this API](https://apidocs.teleapi.net/api/lnp-portability/get-specific-information) when looking up a specific port request. Whether or not the port has completed is also provided as request_status. Please get the values for a specific number by looking inside numbers_data in the JSON.

Examples (without token):
https://apiv1.teleapi.net/lnp/get?request_id=3939&token=
https://apiv1.teleapi.net/lnp/get?request_id=5030&token=
https://apiv1.teleapi.net/lnp/get?request_id=4951&token=
https://apiv1.teleapi.net/lnp/get?request_id=4936&token=

**Describe the solution you'd like**
We should email the customer when their port completion date (otherwise known as FOC or Firm Order Commitment date) is set, and once the port request completes we should also email them to let them know the port has completed.

**Describe alternatives you've considered**
Let them know manually, usually hours after the port request is updated. Unreliable human handled process :c

**Additional context**
The vendor usually emails us that a port has completed at 9am PST on the day of the FOC date. They are less consistent on letting us know a FOC date has been set, though this generally happens only between 6:30am PST and noon PST.

**Email Templates**

Template for Port Date Set (aka FOC date being set to a date in the near future):
Title: Port completion date set for `<first phone number in port request>`
```
Hi <customer name>,

Good news, your old provider is going to release your phone numbers to Accelerate Networks on <insert date here>!

Feel free to **review the order here**, and let us know if you have any questions.

Numbers porting to Accelerate Networks:
<List of all phone numbers and FOC dates (even if a number is pending FOC date)>

Sincerely,
Accelerate Networks
206-858-8757 (call or text)
```
Template for a port completing:
Title: Your phone number has switched to Accelerate Networks successfully!
```
Hi <customer name>,

Great news, your old provider has released your phone numbers to Accelerate Networks!

Feel free to **review the order here**, and let us know if you have any questions. It is now safe to cancel phone service with your old provider for the numbers that have ported in the list below.

Numbers tied to this port request:
<List of all phone numbers, FOC dates (even if a number is pending FOC date) and porting status>

Sincerely,
Accelerate Networks
206-858-8757 (call or text)
```

**Comment by scottstrong206** [comment]
Can I have it send me an email when a port request completes? I need an internal reminder to complete DocuSigns for ISPs.

**Comment by uncheckederror** [comment]
Per @danry25 the success email should look like this: 
> Hello person,
>
> The port request for the numbers listed below has been set to
> 11/12/2020, port requests usually complete at 9am PDT on the day of port
> completion.
>
> Numbers which will port:
> 4257787339
> 4256408980
>
> Sincerely,
> Accelerate Networks
> 206-858-8757 (call/text)

**Comment by uncheckederror** [comment]
@scottstrong206 it will CC the orders inbox when it send out the porting notification to the customer.
